### ISSUE TITLE
Intranet Relay Chat Client is broken

### ISSUE THREAD

**Issue by quardbreak** [NebulaSS13/Nebula#1037]
#### Description of issue

Intranet Relay Chat Client is broken.
If you try open it, every user on same network will act like one user (like there's only one client).

#### Difference between expected and actual behavior

You must have your own client session.

#### Steps to reproduce

Take two PDA, download Intranet Relay Chat Client on them and open it.
Create channel and try perform the chat process, first on the first device, then on another device.

#### Specific information for locating

Dunno, it's Intranet Relay Chat Client

#### Length of time in which bug has been known to occur

Dunno.

#### Client version, Server revision & Game ID

513, nebula downstream with almost same code like on upstream.

#### Issue bingo

- [ ] Issue could be reproduced at least once
- [X] Issue could be reproduced by different players
- [ ] Issue could be reproduced in multiple rounds
- [X] Issue happened in a recent (less than 7 days ago) round
- [X] [Couldn't find an existing issue about this](https://github.com/NebulaSS13/Nebula/issues)

**Comment by afterthought2** [comment]
Should be fixed in mentioned PR.
