### ISSUE TITLE
Network Mainframe Icon broken

### ISSUE THREAD

**Issue by ghost** [NebulaSS13/Nebula#1062]
#### Description of issue
Network Mainframe Icon is broken

#### Difference between expected and actual behavior
Have icon instead of no icon

#### Steps to reproduce
Walk to a mainframe and look at it

#### Specific information for locating
The issues is in on_update_icon() proc
it was not updated to match current icon, so it can be fixed via changing icon state in it

#### Length of time in which bug has been known to occur
N/A

#### Client version, Server revision & Game ID
N/A

#### Issue bingo

- [x] Issue could be reproduced at least once
- [x] Issue could be reproduced by different players
- [x] Issue could be reproduced in multiple rounds
- [x] Issue happened in a recent (less than 7 days ago) round
- [x] [Couldn't find an existing issue about this](https://github.com/NebulaSS13/Nebula/issues)

**Comment by MistakeNot4892** [comment]
Seems to be fixed on dev.
