### ISSUE TITLE
Action checks don't allow unicode characters, even if BYOND is 513

### ISSUE THREAD

**Issue by quardbreak** [NebulaSS13/Nebula#1065]
#### Description of issue

See title

#### Difference between expected and actual behavior

Should use char identify outside ISO only if byond version is under 513

#### Steps to reproduce

Push commit with unicode char

#### Specific information for locating

https://github.com/NebulaSS13/Nebula/blob/9f6c979e41c76dc67650fb38596e2689ef95a02c/test/check-paths.sh#L55

#### Length of time in which bug has been known to occur

dunno

#### Client version, Server revision & Game ID

513 fork

#### Issue bingo

- [X] Issue could be reproduced at least once
- [X] Issue could be reproduced by different players
- [X] Issue could be reproduced in multiple rounds
- [X] Issue happened in a recent (less than 7 days ago) round
- [X] [Couldn't find an existing issue about this](https://github.com/NebulaSS13/Nebula/issues)

**Comment by afterthought2** [comment]
I think this is fine for the upstream Nebula. It's a unit test; it cannot be gated by BYOND version, and we have no need to use non-latin1 characters. If you do, just modify this test downstream.
