### ISSUE TITLE
when reinforced the glass disappears

### ISSUE THREAD

**Issue by SolatK** [NebulaSS13/Nebula#1074]
#### Description of issue
when reinforced the glass disappears

#### Difference between expected and actual behavior
it shouldn't!

#### Steps to reproduce
1)split 2 steel and glass sheets
2)click on the glass sheets with steel
3)lose some glass and steel
4)You have no reinforced glass
5)Cry

#### Issue bingo

- [x] Issue could be reproduced at least once
- [x] Issue could be reproduced by different players
- [x] Issue could be reproduced in multiple rounds
- [x] Issue happened in a recent (less than 7 days ago) round
- [x] [Couldn't find an existing issue about this](https://github.com/NebulaSS13/Nebula/issues)

**Comment by SierraKomodo** [comment]
Seems to work fine for me in testing. If you have steel in one hand and glass in the other, the reinforced glass will appear on the ground on the tile you're standing on.

**Comment by SolatK** [comment]
yes i have updated steps to reproduce

**Comment by MistakeNot4892** [comment]
Result stack is being dropped into the loc of the target stack, which means if you do this with the bare minimum glass in the target stack it is dropped into nullspace.
