### ISSUE TITLE
APC fixing is bugged

### ISSUE THREAD

**Issue by ghost** [NebulaSS13/Nebula#1093]
#### Description of issue
APC resets it construct_state to null after being bashed if its completely broken.

#### Difference between expected and actual behavior
APC must be fixable

#### Steps to reproduce
Use Drop-Bomb verb to nuke any APC until it is broken completely
Attempt to fix it using tools/frame/circuitboard
APC bugs and spits out a runtime
`[08:48:56] Runtime in unsorted.dm, line 827: Machine The DDD APC (/obj/machinery/power/apc) ([0x2007545]) (space) (10,26,5) (/turf/space) violated the state assumptions of the construction state /decl/machine_construction/wall_frame/panel_open/hackable!
proc name: crash at (/proc/crash_at)
usr: The unknown (/mob/living/carbon/human) ([0x3000095]) (the plating) (9,26,5) (/turf/simulated/floor/plating) (coltrane97)
usr.loc: The plating (/turf/simulated/floor/plating) ([0x10110a5]) (9,26,5) (/area)`

#### Specific information for locating

/obj/machinery/power/apc

#### Issue bingo

- [x] Issue could be reproduced at least once
- [x] Issue could be reproduced by different players
- [x] Issue could be reproduced in multiple rounds
- [x] Issue happened in a recent (less than 7 days ago) round
- [x] [Couldn't find an existing issue about this](https://github.com/NebulaSS13/Nebula/issues)

**Comment by comma** [comment]
The issue seems to be that explosions delet the circuitboard, which makes state invalid and that's it for the machine.
Just bashing it with toolbox doesn't seem to do that.

**Comment by comma** [comment]
Yeah it was explosion_act propogating to contents of the machine, and qdeling the circuitboard.
I'll override it somewhere to avoid this.
