### ISSUE TITLE
Oxygen Regenerator icon is broken

### ISSUE THREAD

**Issue by ghost** [NebulaSS13/Nebula#1095]
#### Description of issue
It is not visible because its **layer/level** var (shows underfloor)

#### Difference between expected and actual behavior
Has icon / no icon

#### Steps to reproduce
See a oxygen regenerator

#### Issue bingo

- [x] Issue could be reproduced at least once
- [x] Issue could be reproduced by different players
- [x] Issue could be reproduced in multiple rounds
- [x] Issue happened in a recent (less than 7 days ago) round
- [x] [Couldn't find an existing issue about this](https://github.com/NebulaSS13/Nebula/issues)

**Comment by MistakeNot4892** [comment]
Icons works fine, it just hides under floor tiles like other pipes.
https://user-images.githubusercontent.com/2468979/104389239-1e2ecd00-558f-11eb-84e5-3b6708164fd1.mp4
