### ISSUE TITLE
Persistent books cut Cyrillic letters after rounds

### ISSUE THREAD

**Issue by quardbreak** [NebulaSS13/Nebula#1099]
#### Description of issue

Persistent books cut Cyrillic letters after rounds.
All content in book disappears for some reason. 

#### Difference between expected and actual behavior

Books should move all info, not cut it!

#### Steps to reproduce

1. Write book, place it into shelf and wait for new round to get book.
2. Notice what there's no Cyrillic letters!

#### Specific information for locating

persistent bookz code 

#### Length of time in which bug has been known to occur

discovered yesterday/today

#### Client version, Server revision & Game ID

513, almost-up-to-date nebula fork

#### Issue bingo

- [X] Issue could be reproduced at least once
- [X] Issue could be reproduced by different players
- [X] Issue could be reproduced in multiple rounds
- [X] Issue happened in a recent (less than 7 days ago) round
- [X] [Couldn't find an existing issue about this](https://github.com/NebulaSS13/Nebula/issues)

**Comment by MistakeNot4892** [comment]
As discussed on Discord this seems to be a BYOND bug with `json_decode()`. Only solution would be using plaintext files (csv or the original style of persistence record) instead of JSON.

**Comment by quardbreak** [comment]
Will be resolved on 513.1540

**Comment by MistakeNot4892** [comment]
There's a PR up for a workaround for early version and it'll be addressed by Lummox so I'm going to go ahead and close this one.
