### ISSUE TITLE
Can crawl under machinery

### ISSUE THREAD

**Issue by quardbreak** [NebulaSS13/Nebula#1103]
#### Description of issue

You can crawl under machinery when lying.

#### Difference between expected and actual behavior

You should unable to get on machinery by crawling.

#### Steps to reproduce

1. Toggle lying.
2. Move on tile, for example, with vending machine.
3. Achieve the bug.

#### Length of time in which bug has been known to occur

Discovered today.

#### Client version, Server revision & Game ID

513, almost-same-neb version

#### Issue bingo

- [X] Issue could be reproduced at least once
- [X] Issue could be reproduced by different players
- [X] Issue could be reproduced in multiple rounds
- [X] Issue happened in a recent (less than 7 days ago) round
- [X] [Couldn't find an existing issue about this](https://github.com/NebulaSS13/Nebula/issues)

**Comment by afterthought2** [comment]
Caused by
```
/atom/movable/CanPass(atom/movable/mover, turf/target, height=1.5, air_group = 0)
    . = ..() || (mover && !(mover.movable_flags & MOVABLE_FLAG_NONDENSE_COLLISION) && !mover.density)
```

Unsure how to resolve.
