### ISSUE TITLE
Grabs, disarms and handcuff 

### ISSUE THREAD

**Issue by SolatK** [NebulaSS13/Nebula#1125]
#### Description of issue
Grabs and handcuff are broken. While in the grab, you can remove the handcuffs in a second. Disarming also works very strangely. After successful disarming, the character does not lose the ability to move, and when trying to take him into the grab, he can simply crawl away.

#### Difference between expected and actual behavior
handcuffs should not come off in a second

#### Steps to reproduce
1) Grab someone
2) Handcuff him
3) He starts spamming with resist
4) Handcuffs removed in a second
5) Break your arm trying to take away his handcuffs by disarming
6) Use sleeptoxin and welded locker next time

#### Issue bingo

- [x] Issue could be reproduced at least once
- [x] Issue could be reproduced by different players
- [x] Issue could be reproduced in multiple rounds
- [x] Issue happened in a recent (less than 7 days ago) round
- [x] [Couldn't find an existing issue about this](https://github.com/NebulaSS13/Nebula/issues)

**Comment by MistakeNot4892** [comment]
Can't reproduce the rapid handcuff removal, it takes 2 minutes on my test instance.
The crawling away thing isn't a bug, that's just how crawling works. You need to upgrade to an aggressive grab to pin them in place, maybe by tasing them first.

**Comment by MistakeNot4892** [comment]
Turned out to be an issue with psionics, has been resolved.
