### ISSUE TITLE
Circuitboard names are mangled

### ISSUE THREAD

**Issue by comma** [NebulaSS13/Nebula#1172]
#### Description of issue

All circuitboard items names are cut off, e.g. instead of `circuitboard (air alarm)` it's `air alarm)`

#### Difference between expected and actual behavior

Full name is expected
It makes slav smileys at me in actual

#### Steps to reproduce
1. Spawn /obj/item/stock_parts/circuitboard/fire_alarm
2. Observe name

#### Specific information for locating

/obj/item/stock_parts/circuitboard
Probably T_BOARD() macro

#### Length of time in which bug has been known to occur

Noticed couple days ago

#### Client version, Server revision & Game ID

idk

#### Issue bingo

- [x] Issue could be reproduced at least once
- [ ] Issue could be reproduced by different players
- [x] Issue could be reproduced in multiple rounds
- [x] Issue happened in a recent (less than 7 days ago) round
- [ ] [Couldn't find an existing issue about this](https://github.com/NebulaSS13/Nebula/issues)

**Comment by SierraKomodo** [comment]
Sounds like someone's using a `=` instead of a `.=` to me

**Comment by SierraKomodo** [comment]
Further digging looks like a possible shenanigan with the `T_BOARD()` define being weird with the concatenation operators.
