### ISSUE TITLE
Unable to repair emagged airlock

### ISSUE THREAD

**Issue by quardbreak** [NebulaSS13/Nebula#1208]
#### Description of issue

See title.

#### Difference between expected and actual behavior

Able to repair airlock after using emag on it

#### Steps to reproduce

1. Emag airlock
2. Try to repair it

#### Specific information for locating

airlock

#### Length of time in which bug has been known to occur

Dunno, heard from player today

#### Client version, Server revision & Game ID

513, nebula fork

#### Issue bingo

- [ ] Issue could be reproduced at least once
- [ ] Issue could be reproduced by different players
- [ ] Issue could be reproduced in multiple rounds
- [X] Issue happened in a recent (less than 7 days ago) round
- [X] [Couldn't find an existing issue about this](https://github.com/NebulaSS13/Nebula/issues)

**Comment by MistakeNot4892** [comment]
What do you mean by repair? The only way to repair an emagged airlock on Baycode is removing the circuitboard (deconstructing the entire thing) and making a new one.

**Comment by SolatK** [comment]
> 
> 
> What do you mean by repair? The only way to repair an emagged airlock on Baycode is removing the circuitboard (deconstructing the entire thing) and making a new one.

You need to close airlock and get circuit out of them, but you cant close it with crowbar or bebug. If you drop bolts you cant raise it. And you cant attack airlock to completly break.

**Comment by afterthought2** [comment]
I believe you can depower it (from the APC) and then crowbar it closed.

Are there specific tool interactions you suggest adding or revising to handle emagged airlocks better?
