### ISSUE TITLE
Doors hacking is too easy now

### ISSUE THREAD

**Issue by comma** [NebulaSS13/Nebula#1274]
#### Description of issue
You don't actually have to hack them, you just unscrew panel, take out power components, and crowbar.

#### Difference between expected and actual behavior
Actual behavior:
Can bypass doors with simple construction steps
Expected behavior:
Bypassing door without proper access requires hacking or breaking it down

#### Steps to reproduce
1. Open hatch with screwdriver
2. Remove tesla part with wrench
3. Crowbar door open

#### Specific information for locating

Any airlock

#### Length of time in which bug has been known to occur

Probably since doors were fully machinery part'd

#### Issue bingo

- [x] Issue could be reproduced at least once
- [x] Issue could be reproduced by different players
- [x] Issue could be reproduced in multiple rounds
- [x] Issue happened in a recent (less than 7 days ago) round
- [x] [Couldn't find an existing issue about this](https://github.com/NebulaSS13/Nebula/issues)

**Comment by comma** [comment]
I think it could be fixed by
1.Adding lock component (maybe remove access setting from circuitboard since it'll be redundant)
2.Adding special states a-la APC to doors, where you can access wires for hacking without unlocking, but need to unlock before accessing the components.

**Comment by MistakeNot4892** [comment]
I'm partial to 2, it mirrors the old behavior the best.
