### ISSUE TITLE
eye surgery requires going through skull

### ISSUE THREAD

**Issue by ZirconiumWit** [NebulaSS13/Nebula#1276]
#### Description of issue
As title, surgical eye replacement requires skull cutting.  As eyes are a surface organ, seems like you should be able to extract eyes without breaking bone.  I seem to remember a time not too long ago that this was the case.  If this was deliberately changed, please disregard.

#### Difference between expected and actual behavior
Expected:  Eye removal should require incision and retraction of incision at most
Actual: eye removal requires digging in to the brain, below the skull

#### Steps to reproduce
perform eye replacement surgery

#### Specific information for locating

in patient's head

#### Length of time in which bug has been known to occur

Found out about it today

#### Client version, Server revision & Game ID

Client Version: 513
Server Revision: 470b4df42455b2c47c1f89089aa89cf906b0314a - scavhands - 2021-02-04
Game ID: cas-ae0A
Current map: Tradeship Ivenmoth

#### Issue bingo

- [x] Issue could be reproduced at least once
- [ ] Issue could be reproduced by different players
- [x] Issue could be reproduced in multiple rounds
- [x] Issue happened in a recent (less than 7 days ago) round
- [x] [Couldn't find an existing issue about this](https://github.com/NebulaSS13/Nebula/issues)

**Comment by MistakeNot4892** [comment]
Looks like surface_accessible is only checked for repairing internal organs, not for removing or replacing them. Unsure if this is functionality that was lost or if there was a misunderstanding at some point.

**Comment by MistakeNot4892** [comment]
Took a look at how easy this would be to fix and it's going to be painful. Will likely count as a feature addition rather than a fix. Will get to it someday.
