### ISSUE TITLE
Fuel from /obj/structure/fire_source can't be extracted correctly

### ISSUE THREAD

**Issue by AlexMorgan3817** [NebulaSS13/Nebula#1281]
#### Description of issue
If you put for example stack of wood in bonfire`/obj/structure/fire_source/hearth` and try to take it back, you will get it in hands visibly, but you can't attackby it or drop down or throw
![image](https://user-images.githubusercontent.com/46600554/107115684-ea4e7b00-68a0-11eb-9e85-6109c540c672.png)
![image](https://user-images.githubusercontent.com/46600554/107115696-06521c80-68a1-11eb-8063-7f9eff0a33de.png)
It will be just sprite in hand slot.

#### Issue bingo
- [x] Issue could be reproduced at least once
- [?] Issue could be reproduced by different players
- [?] Issue could be reproduced in multiple rounds
- [x] Issue happened in a recent (less than 7 days ago) round
- [x] [Couldn't find an existing issue about this](https://github.com/NebulaSS13/Nebula/issues)

**Comment by AlexMorgan3817** [comment]
Works only if fire_source is burning

**Comment by MistakeNot4892** [comment]
Can't reproduce this on current stable or dev. Please reopen if you can reliably reproduce it and detail the steps.
