### ISSUE TITLE
Blast and fire doors don't do automatic direction set

### ISSUE THREAD

**Issue by quardbreak** [NebulaSS13/Nebula#132]
Currently every mapped blast and fire door need to manually direction changed, without it, horizontally they're will look like here:
![image](https://user-images.githubusercontent.com/44920739/76682123-56c9e700-660a-11ea-967e-a9a5c3607ce1.png)
When they must look like here:
![image](https://user-images.githubusercontent.com/44920739/76682167-cb9d2100-660a-11ea-835e-fa33cdb234e4.png)

**Comment by afterthought2** [comment]
I don't believe any doors do this automatically; it may be reasonable, but it does make certain mapping assumptions. Are you suggesting that there is code for them to autoset like this in the repo, but it doesn't work, or are you proposing this as a feature?

**Comment by quardbreak** [comment]
More like it's doesn't work now. You can check for example the airlock code where it was able to automatically set direction based on list of objects or turfs around.

**Comment by quardbreak** [comment]
Also, I think recent blending refactor could have influenced this.
