### ISSUE TITLE
Cargo Shuttle and Escape Shuttle can't dock with the station

### ISSUE THREAD

**Issue by quardbreak** [NebulaSS13/Nebula#1340]
#### Description of issue

See the title. 
Cargo shuttle can't dock with exodus (as map example which still use this system) and probably shuttle type of evacuation controller is broken.

#### Difference between expected and actual behavior

Cargo and Escape shuttle should dock with the station.

#### Steps to reproduce

1. Run Loaf's or my copy of exodus.
2. Call evacuation shuttle or cargo shuttle. Wait for it.
3. See it doesn't dock.

#### Length of time in which bug has been known to occur

Probably a long time since bay stop using exodus and related cargo/evacuation shuttle code.

#### Client version, Server revision & Game ID

Byond 513.

#### Issue bingo

- [X] Issue could be reproduced at least once
- [X] Issue could be reproduced by different players
- [X] Issue could be reproduced in multiple rounds
- [X] Issue happened in a recent (less than 7 days ago) round
- [X] [Couldn't find an existing issue about this](https://github.com/NebulaSS13/Nebula/issues)

**Comment by afterthought2** [comment]
See #1374, though am unsure if this fixes the full issue.

**Comment by afterthought2** [comment]
It appears there are further issues with the evac shuttle.

**Comment by afterthought2** [comment]
Should now be fixed; open new issue if there are further legacy shuttle bugs.
