### ISSUE TITLE
Gas Heater/Cooler mouse opacity

### ISSUE THREAD

**Issue by ghost** [NebulaSS13/Nebula#1355]
#### Description of issue
Can't properly click on it, click passes on turf underneath instead (turf is also displayed on statusbar, maybe it's some overlay problem?)

#### Difference between expected and actual behavior
Able to use it without issues / Unable to click

#### Steps to reproduce
Create unary heater/cooler
Try to use it

#### Specific information for locating

/obj/machinery/atmospherics/unary/heater
or
/obj/machinery/atmospherics/unary/freezer
^^^ was not specified in report, freezer/heater. Problem probably may occur only with one since its code are copypasted from each other

#### Length of time in which bug has been known to occur

iirc was also occuring to me even on bay, year++

#### Client version, Server revision & Game ID

https://github.com/infinitystation/Nebula/tree/50439ae5d5d062a21cc4b61ac64d4c32e8839dc4

#### Issue bingo

- [x] Issue could be reproduced at least once
- [x] Issue could be reproduced by different players
- [x] Issue could be reproduced in multiple rounds
- [x] Issue happened in a recent (less than 7 days ago) round
- [x] [Couldn't find an existing issue about this](https://github.com/NebulaSS13/Nebula/issues)

**Comment by afterthought2** [comment]
Tried to reproduce but couldn't. Spawned one in -> was interactive; constructed one -> was interactive. Do you have specific steps to reproduce? It may help to know what the turf type on which you were spawning it is.

**Comment by ghost** [comment]
maybe a round-start problem.. i'll check it later

**Comment by ghost** [comment]
@afterthought2 
UPD:
![image](https://user-images.githubusercontent.com/30006750/109340387-029b2f80-787a-11eb-9853-e8ee9f7dbf20.png)

issue appeared on round-start premapped heater

**Comment by MistakeNot4892** [comment]
Had some reports of omni mixers/filters being weird with mouse opacity on staging earlier in the week, don't have any more useful info than that.

**Comment by ghost** [comment]
had this one too... i wonder why i didnt report it
(whats even more funny i had it like 2-3 yrs ago)

**Comment by MistakeNot4892** [comment]
Reproduced this on current staging, it's inconsistent - if you move the mouse quickly it happens, if you move it slowly it seems to be fine.
