### ISSUE TITLE
Ghost "point-to" are visible to players

### ISSUE THREAD

**Issue by ghost** [NebulaSS13/Nebula#1388]
#### Description of issue
N/A

#### Difference between expected and actual behavior
No ghostbusters

#### Steps to reproduce
Use point-to verb as a ghost, ask homie to tell you if he saw anything

#### Specific information for locating

N/A

#### Length of time in which bug has been known to occur

Recently

#### Client version, Server revision & Game ID

https://github.com/infinitystation/Nebula/tree/cb806d79c3930df3177110c8b96cbbc1ffc60c68

#### Issue bingo

- [x] Issue could be reproduced at least once
- [x] Issue could be reproduced by different players
- [x] Issue could be reproduced in multiple rounds
- [x] Issue happened in a recent (less than 7 days ago) round
- [x] [Couldn't find an existing issue about this](https://github.com/NebulaSS13/Nebula/issues)

**Comment by MistakeNot4892** [comment]
To be specific, the _message_ is visible to living players, not the arrow.
