### ISSUE TITLE
rig air supply didnt work after tanl replacement

### ISSUE THREAD

**Issue by SolatK** [NebulaSS13/Nebula#1410]
#### Difference between expected and actual behavior
It makes runtime every press on the toggle internal button
![изображение](https://user-images.githubusercontent.com/29740451/109435387-58fba000-7a2b-11eb-9ee7-9e0900dc0655.png)

#### Steps to reproduce
1)Remove tank from rig
2)install new tank, or the same
3)Try to breath using it

#### Issue bingo

- [x] Issue could be reproduced at least once
- [x] Issue could be reproduced by different players
- [x] Issue could be reproduced in multiple rounds
- [x] Issue happened in a recent (less than 7 days ago) round
- [x] [Couldn't find an existing issue about this](https://github.com/NebulaSS13/Nebula/issues)

**Comment by comma** [comment]
Actually has nothing to do with tank replacement - it runtimes if you have anything held in hands (probably wrench or old tank after replacement) because of internals auto-find code.
