### ISSUE TITLE
RnD and robotics

### ISSUE THREAD

**Issue by SolatK** [NebulaSS13/Nebula#1411]
#### Description of issue
Until scientists learn at least something and sync it, the product list of all robotisc printers will be empty

#### Difference between expected and actual behavior
I should be able to print robotic arms or other organs even without scientists

#### Steps to reproduce
1)Joins as robotist
2)Try to print something
3)There is no sientists and nothing in your printer list

#### Issue bingo

- [x] Issue could be reproduced at least once
- [x] Issue could be reproduced by different players
- [x] Issue could be reproduced in multiple rounds
- [x] Issue happened in a recent (less than 7 days ago) round
- [x] [Couldn't find an existing issue about this](https://github.com/NebulaSS13/Nebula/issues)

**Comment by MistakeNot4892** [comment]
Will have a commit up to fix this shortly, looks like the design databases were not syncing the network after init.
