### ISSUE TITLE
Runtime report regarding latex gloves and blood

### ISSUE THREAD

**Issue by ZirconiumWit** [NebulaSS13/Nebula#1434]
#### Description of issue
Surgery is bloody business, so why are these gloves so dang clean?

#### Difference between expected and actual behavior
Latex gloves don't bloody when performing surgery

#### Steps to reproduce
I was doing self-surgery and game runtime'd. 

#### Specific information for locating

Runtime message:
[08:19:04] Runtime in item.dm, line 676: bad index
proc name: add blood (/obj/item/add_blood)
src: the latex gloves (/obj/item/clothing/gloves/latex)
src.loc: Cadence Stroh (/mob/living/carbon/human)
call stack:
the latex gloves (/obj/item/clothing/gloves/latex): add blood(the heart (/obj/item/organ/internal/heart), 0, null)
Cadence Stroh (/mob/living/carbon/human): bloody hands(the heart (/obj/item/organ/internal/heart), 0)
the heart (/obj/item/organ/internal/heart): handle blood()
the heart (/obj/item/organ/internal/heart): Process()
Cadence Stroh (/mob/living/carbon/human): handle organs()
Cadence Stroh (/mob/living/carbon/human): Life(20, 572, Mobs (/datum/controller/subsystem/processing/mobs))
Mobs (/datum/controller/subsystem/processing/mobs): fire(0)
Mobs (/datum/controller/subsystem/processing/mobs): ignite(0)
Master (/datum/controller/master): RunQueue()
Master (/datum/controller/master): Loop()
Master (/datum/controller/master): StartProcessing(0)

#### Length of time in which bug has been known to occur

Today only

#### Client version, Server revision & Game ID

Client Version: 513
Server Revision: 57b4162b6d60ac230dc76caf62315f602f8cb342 - ministationmockup - 2021-03-02
Game ID: caU-a2kj
Current map: Ministation Zebra

#### Issue bingo

- [ ] Issue could be reproduced at least once
- [ ] Issue could be reproduced by different players
- [ ] Issue could be reproduced in multiple rounds
- [x] Issue happened in a recent (less than 7 days ago) round
- [x] [Couldn't find an existing issue about this](https://github.com/NebulaSS13/Nebula/issues)

**Comment by MistakeNot4892** [comment]
This appears to have been fixed at some point, can't reproduce on stable.
