### ISSUE TITLE
self-surgery for head broken

### ISSUE THREAD

**Issue by ZirconiumWit** [NebulaSS13/Nebula#147]
#### Description of issue
performing surgery on your own head doesn't seem to work at this point, can't even start an incision.  can't even fuck UP making your first incision for your own head.  All other self-surgery seems to work.

#### Difference between expected and actual behavior
Any doctor worth their salt would be ashamed of themselves if they had to ask for another surgery to do some measly brain surgery.

#### Steps to reproduce
Try cutting your own head open with a knife in help intent.  I'll bet you can't!

#### Specific information for locating

You can find it on a chair while preparing yourself for a surgery that won't be happening.

#### Length of time in which bug has been known to occur

Today only

#### Client version, Server revision & Game ID

Client Version: 512
Server Revision: 2b06cedc24e4debdbb7749f6c5728ea590abc826 - propheticprosthetics - 2020-03-15
Game ID: b6b-a9zI
Current map: Bearcat

#### Issue bingo

- [x] Issue could be reproduced at least once
- [ ] Issue could be reproduced by different players
- [x] Issue could be reproduced in multiple rounds
- [x] Issue happened in a recent (less than 7 days ago) round
- [x] [Couldn't find an existing issue about this](https://github.com/NebulaSS13/Nebula/issues)

**Comment by afterthought2** [comment]
This isn't a bug; it's an intentional restriction: you cannot operate on your own head. Can discuss on discord if you feel it should be lifted.
