### ISSUE TITLE
Entering cryo cause massive lag

### ISSUE THREAD

**Issue by SolatK** [NebulaSS13/Nebula#1530]
#### Description of issue
When the cryogenic capsule eats the body, the server lags.
VV open cause mini-lag too

#### Difference between expected and actual behavior
Shouldn't

#### Steps to reproduce
1) Enter the game
2) Place someone in the cryo
3) Wait until it eats the body
4) It lags!

#### Length of time in which bug has been known to occur

One month 

#### Issue bingo

- [x] Issue could be reproduced at least once
- [x] Issue could be reproduced by different players
- [x] Issue could be reproduced in multiple rounds
- [x] Issue happened in a recent (less than 7 days ago) round
- [x] [Couldn't find an existing issue about this](https://github.com/NebulaSS13/Nebula/issues)

**Comment by MistakeNot4892** [comment]
Need more information about what was being cryopodded and if there were runtimes, other circumstances, etc.

**Comment by MistakeNot4892** [comment]
Please reopen this if you can chase down more specific information on reproducing it.
