### ISSUE TITLE
Visual accessory problems

### ISSUE THREAD

**Issue by quardbreak** [NebulaSS13/Nebula#1591]
#### Description of issue

In inventory, accessories cover all clothing,

![изображение](https://user-images.githubusercontent.com/44920739/116786205-0b8cc500-aaa6-11eb-97bc-e3b06e18baa3.png)

#### Difference between expected and actual behavior

Should not render inventory icon in inventory while attached to something (except on examine). 

#### Steps to reproduce

1. Wear uniform
2. Attach accessory

#### Issue bingo

- [X] Issue could be reproduced at least once
- [X] Issue could be reproduced by different players
- [X] Issue could be reproduced in multiple rounds
- [X] Issue happened in a recent (less than 7 days ago) round
- [X] [Couldn't find an existing issue about this](https://github.com/NebulaSS13/Nebula/issues)

**Comment by MistakeNot4892** [comment]
This isn't a bug exactly, there are just no icons set for these accessories that line up properly. If someone wants to go through and define them then that would fix it.

**Comment by afterthought2** [comment]
Disagree that this is not a bug.

**Comment by MistakeNot4892** [comment]
Overlaps with  #1358
