### ISSUE TITLE
Removing all worn items on another player stops after first item is removed

### ISSUE THREAD

**Issue by WesKrug** [NebulaSS13/Nebula#1609]
#### Description of issue
You must have an empty hand to remove equipment from another character, and you can only remove one at a time.

When attempting to remove another character's equipment, you are able to select multiple entries like normal; however as soon as the first object is removed, it goes into your open hand and then all progress bars are immediately removed with the objects still equipped to the downed player.

#### Difference between expected and actual behavior
I would expect all items to be unequipped in the order which they were clicked

#### Steps to reproduce
1. Click and drag from another character to yourself
2. Ensure you have an empty hand selected
3. Quickly click all the equipment you can 
4. Watch as the first item is removed and see all of the progress bars fade out

#### Specific information for locating

Likely wherever the "remove equipment" screen is housed. That may not actually be the name of the screen.

#### Length of time in which bug has been known to occur

Dunno!

#### Client version, Server revision & Game ID

Client Version: 513
Server Revision: 6ce3da8783adf9318c59cbbddaaaafe0542efa9a - staging - 2021-05-06
Game ID: cbU-dqMu
Current map: Tradeship Ocelot Alpha

#### Issue bingo

- [x] Issue could be reproduced at least once
- [ ] Issue could be reproduced by different players
- [ ] Issue could be reproduced in multiple rounds
- [x] Issue happened in a recent (less than 7 days ago) round
- [x] [Couldn't find an existing issue about this](https://github.com/NebulaSS13/Nebula/issues)

**Comment by MistakeNot4892** [comment]
Going to throw this one at the Discord to get some feedback on how the ideal behavior should look. I don't think Bay-style 'click a list of stuff and everything will pop off' interaction is necessarily desirable.
