### ISSUE TITLE
Captains ID doesn't work inside PDA

### ISSUE THREAD

**Issue by WesKrug** [NebulaSS13/Nebula#1610]
#### Description of issue
Spare Captains ID doesn't seem to work when in your PDA

#### Difference between expected and actual behavior
When the Captain's Spare is inserted into your PDA, I expect access to the same doors I can access when the Captain's spare is in my hand

#### Steps to reproduce
1.) Obtain the Captain's Spare ID
2.) Insert it into your PDA
3.) Attempt to open door
4.) Fail
5.) Alt+Click your PDA to grab the ID in your open hand
6.) Attempt to open door
7.) Succeed

#### Specific information for locating

Access code? Godspeed.

#### Length of time in which bug has been known to occur

Dunno!

#### Client version, Server revision & Game ID

Client Version: 513
Server Revision: 6ce3da8 - staging - 2021-05-06
Game ID: cbU-dqMu
Current map: Tradeship Ocelot Alpha

#### Issue bingo

- [x] Issue could be reproduced at least once
- [ ] Issue could be reproduced by different players
- [ ] Issue could be reproduced in multiple rounds
- [x] Issue happened in a recent (less than 7 days ago) round
- [x] [Couldn't find an existing issue about this](https://github.com/NebulaSS13/Nebula/issues)

https://user-images.githubusercontent.com/44451125/117386496-09b36f00-aeb5-11eb-9718-4f848d366aa0.mp4

**Comment by WesKrug** [comment]
I realize I only captured the game screen so it's hard to prove that I had the captains ID but I can confirm that it was the spare

**Comment by ghost** [comment]
@WesKrug iirc this depends on whenever the PDA's RFID broadcaster powered and functioning. In your video PDA is off, so ???

**Comment by WesKrug** [comment]
@Coltrane97 It worked when my original ID was in my PDA... it's very possible I turned it off though! I don't recall.

**Comment by MistakeNot4892** [comment]
Can't reproduce on current staging branch.
