### ISSUE TITLE
Exosuit Camera Problem

### ISSUE THREAD

**Issue by ghost** [NebulaSS13/Nebula#1613]
#### Description of issue
While driving an exosuit, camera (player viewpoint) sometimes freezes.
Direct translation from player feedback:
kwuh: so when you drive vertically
kwuh: the camera follows you
kwuh: but as soon as you start to move horizontally
kwuh: camera freezes

Screenshots

![image](https://user-images.githubusercontent.com/30006750/117499328-bd833000-af83-11eb-8c39-efc922786a9c.png)
^ arrow points at actual player location
![image](https://user-images.githubusercontent.com/30006750/117499354-c83dc500-af83-11eb-96a7-ae1825c9d84c.png)
![image](https://user-images.githubusercontent.com/30006750/117499740-4ef2a200-af84-11eb-9132-b063080dbba0.png)

"occured to me on all mechas" - player feedback

#### Difference between expected and actual behavior
Have no camera problems / Have them

#### Steps to reproduce
1. Hop onto closest exosuit available
2. Drive to north
3. Turn, west for example
4. Experience camera problems

#### Specific information for locating

/mob/living/exosuit

#### Length of time in which bug has been known to occur

Today (07.05.2021)
could occure before, it's unknown

#### Client version, Server revision & Game ID

https://github.com/Starlight-SS13/Nebula/commit/882ffb5c92d4a8627eb4484c36ad988c9198f84c

#### Issue bingo

- [x] Issue could be reproduced at least once
- [ ] Issue could be reproduced by different players
- [ ] Issue could be reproduced in multiple rounds
- [x] Issue happened in a recent (less than 7 days ago) round
- [x] [Couldn't find an existing issue about this](https://github.com/NebulaSS13/Nebula/issues)

**Comment by MistakeNot4892** [comment]
Can't repro this on staging, even via stairs and pitfalls. Is there any further information on how to reproduce it?

**Comment by ghost** [comment]
sadly no

**Comment by MistakeNot4892** [comment]
Going to close it for now, can reopen if it reoccurs.
