### ISSUE TITLE
Putting non-reactant gasses into the R-UST breaks the rust core control console

### ISSUE THREAD

**Issue by pepperoniboy57** [NebulaSS13/Nebula#1627]
#### Description of issue
Putting gasses that the R-UST doesn't use for reactions (nitrogen, co2) bricks the core control console once the plasma temperature gets above 400
Can sometimes be fixed by going inside the core and intentionally destabilizing the field while the temperature is below 1000k

#### Difference between expected and actual behavior
Not having the R-UST in a vacuum shouldn't break the controls for it.

#### Steps to reproduce
-Turn on the supermacman in the power compartment, power 4/5
-Turn on the R-UST at 20 teslas
-Get the portable air pump from atmos and inject it's contents into the engines core (or unscrew and move one of the borosilicate windows to let some air in)
-Turn on the gyrotron at 2 delay 3 power
-Keep checking the core control console, it will stop working once the temperature reaches above 400
-it will act like there are no R-USTs untill the electromagnetic field goes down
-small chance for the "start up" button to stop working once the electromagnetic field goes down (cannot reliably recreate)

#### Specific information for locating

how the console looks once its broken: 
![image](https://user-images.githubusercontent.com/84046156/117889682-a498b880-b2bc-11eb-86f5-8f4357d8dd52.png)
/obj/machinery/computer/fusion/core_control
/obj/machinery/power/fusion_core/mapped
/obj/effect/fusion_em_field
once the field is deleted, somehow turned off or destabilized the console won't break again

#### Length of time in which bug has been known to occur

I've started playing nebula a few days ago so i'm not really sure

#### Client version, Server revision & Game ID

Client - Byond 513.5142
Revision - 6ce3da8783adf9318c59cbbddaaaafe0542efa9a

#### Issue bingo

- [x] Issue could be reproduced at least once
- [ ] Issue could be reproduced by different players
- [x] Issue could be reproduced in multiple rounds
- [x] Issue happened in a recent (less than 7 days ago) round
- [x] [Couldn't find an existing issue about this](https://github.com/NebulaSS13/Nebula/issues)

**Comment by MistakeNot4892** [comment]
Can reproduce this on current staging build.
Related runtime
````
[13:00:20] Runtime in core_control.dm,57: Cannot read null.gas_name
  proc name: build ui data (/obj/machinery/computer/fusion/core_control/build_ui_data)
  usr: The maintenance drone (740) (/mob/living/silicon/robot/drone) ([0x3000020]) (the floor) (41,26,3 - Tradeship Ocelot Alpha) (/turf/simulated/floor/tiled/techfloor) (mistakenot4892)
  usr.loc: The floor (/turf/simulated/floor/tiled/techfloor) ([0x10039f8]) (41,26,3 - Tradeship Ocelot Alpha) (/area/ship/trade/maintenance/engineering)
  src: the R-UST Mk. 8 core control (/obj/machinery/computer/fusion/core_control)
  src.loc: the floor (42,25,3) (/turf/simulated/floor/tiled/techfloor)
  call stack:
  the R-UST Mk. 8 core control (/obj/machinery/computer/fusion/core_control): build ui data()
  the R-UST Mk. 8 core control (/obj/machinery/computer/fusion/core_control): ui interact(the maintenance drone (740) (/mob/living/silicon/robot/drone), "main", null, 1)
  the R-UST Mk. 8 core control (/obj/machinery/computer/fusion/core_control): interface interact(the maintenance drone (740) (/mob/living/silicon/robot/drone))
  the R-UST Mk. 8 core control (/obj/machinery/computer/fusion/core_control): attack hand(the maintenance drone (740) (/mob/living/silicon/robot/drone))
  the R-UST Mk. 8 core control (/obj/machinery/computer/fusion/core_control): attack robot(the maintenance drone (740) (/mob/living/silicon/robot/drone))
  the maintenance drone (740) (/mob/living/silicon/robot/drone): ClickOn(the R-UST Mk. 8 core control (/obj/machinery/computer/fusion/core_control), "icon-x=22;icon-y=15;left=1;scr...")
  /datum/click_handler/default (/datum/click_handler/default): OnClick(the R-UST Mk. 8 core control (/obj/machinery/computer/fusion/core_control), "icon-x=22;icon-y=15;left=1;scr...")
  the R-UST Mk. 8 core control (/obj/machinery/computer/fusion/core_control): Click(the floor (42,25,3) (/turf/simulated/floor/tiled/techfloor), "mapwindow.map", "icon-x=22;icon-y=15;left=1;scr...")
  MistakeNot4892 (/client): Click(the R-UST Mk. 8 core control (/obj/machinery/computer/fusion/core_control), the floor (42,25,3) (/turf/simulated/floor/tiled/techfloor), "mapwindow.map", "icon-x=22;icon-y=15;left=1;scr...")
````

**Comment by MistakeNot4892** [comment]
![image](https://user-images.githubusercontent.com/2468979/123912243-22756800-d9c0-11eb-82f7-75c803d905e3.png)
