### ISSUE TITLE
R-UST Engine core vent is useless

### ISSUE THREAD

**Issue by pepperoniboy57** [NebulaSS13/Nebula#1629]
#### Description of issue
this vent 
![image](https://user-images.githubusercontent.com/84046156/117893362-e9275280-b2c2-11eb-8610-588fef0fed46.png)
is set to external 4000 and there is no way to change it's settings without var editing
if gasses were to get into the core, the vent can't get very effectively get them out, it will keep heating the co2 in the heat exhange pipes, eventually bursting them

#### Difference between expected and actual behavior
The vent should be set to external 0 to keep the core a vacuum, altough not necessary a button or some other way of toggling it on and off would be good for when you want gas in the core (heating up the propellant with the heat exchange pipes)

#### Steps to reproduce
-Mapping issue

#### Specific information for locating

/obj/machinery/atmospherics/unary/vent_pump/engine

#### Length of time in which bug has been known to occur

no clue

#### Client version, Server revision & Game ID

Client - Byond 513.5142
Revision - 6ce3da8783adf9318c59cbbddaaaafe0542efa9a

#### Issue bingo

- [x] Issue could be reproduced at least once
- [ ] Issue could be reproduced by different players
- [x] Issue could be reproduced in multiple rounds
- [x] Issue happened in a recent (less than 7 days ago) round
- [x] [Couldn't find an existing issue about this](https://github.com/NebulaSS13/Nebula/issues)

**Comment by MistakeNot4892** [comment]
The problem with making it siphon all gasses out of the core is that it makes it impossible to inject hydrogen as a gas.
I think it might be from the previous implementation as a burn chamber, not sure. Making it default to off with a pressure bound of zero and a button might be the best solution.

**Comment by pepperoniboy57** [comment]
> The problem with making it siphon all gasses out of the core is that it makes it impossible to inject hydrogen as a gas.
> I think it might be from the previous implementation as a burn chamber, not sure. Making it default to off with a pressure bound of zero and a button might be the best solution.

I thought the rusts field would absorb all the hydrogen in its core completely before the scrubbers can take any gas out


If a toggle cant be implemented you can add a filter to filter the hydrogen it takes back into the injector pipes. Hydrogen wont be wasted even if you need a bit higher pressure injection.
