### ISSUE TITLE
Through-wall doors seem REALLY loud  (Feature request, I suppose?)

### ISSUE THREAD

**Issue by ZirconiumWit** [NebulaSS13/Nebula#1637]
#### Description of issue
It's been a while since I played neb, but I seem to recall walls used to mitigate some of the noise level?  Might be misremembering.  However, during the test, every time someone opened a door anywhere NEAR medical, it sounded like they were certainly walking right in with how loud the airlock sounds were. 

#### Difference between expected and actual behavior
You'd expect walls and doors to mitigate sound to some extent, what with them being completely air tight.

#### Steps to reproduce
Listen to someone walking through a door that isn't in the same room.  You will hear.

#### Specific information for locating

Airlocks

#### Length of time in which bug has been known to occur

Today?

#### Client version, Server revision & Game ID

Client Version: 513
Server Revision: 7df74e2b7dfc296775db47df5ea89243452c5972 - staging - 2021-05-14
Game ID: cb4-aBu1
Current map: Tradeship Ocelot Alpha

#### Issue bingo

- [ ] Issue could be reproduced at least once
- [ ] Issue could be reproduced by different players
- [ ] Issue could be reproduced in multiple rounds
- [x] Issue happened in a recent (less than 7 days ago) round
- [x] [Couldn't find an existing issue about this](https://github.com/NebulaSS13/Nebula/issues)

**Comment by MistakeNot4892** [comment]
The sound engine doesn't actually care about turfs between the target and origin except in terms of distance (and low pressure at the point of hearing), so this is a feature request rather than a bug.
