### ISSUE TITLE
Fire alarm sounds seem to queue over the top of each other until they are unbearably loud and clashing.

### ISSUE THREAD

**Issue by MistakeNot4892** [NebulaSS13/Nebula#1640]
#### Description of issue
Moving in an area with a fire alarm going causes the sound to compound until it's extremely loud and grating.

#### Difference between expected and actual behavior
Fire alarm sound should play once and loop.

#### Steps to reproduce
Start a fire.
Walk into the area while the alarm is going.

#### Length of time in which bug has been known to occur
Unsure.

#### Client version, Server revision & Game ID
Client Version: 513
Server Revision: 38ce123cb4878492f2e6bf6e7e3d395d50eea402 - staging - 2021-05-15
Game ID: cb4-aLLW

#### Issue bingo

- [ ] Issue could be reproduced at least once
- [ ] Issue could be reproduced by different players
- [ ] Issue could be reproduced in multiple rounds
- [ ] Issue happened in a recent (less than 7 days ago) round
- [ ] [Couldn't find an existing issue about this](https://github.com/NebulaSS13/Nebula/issues)

**Comment by Mazianni** [comment]
line 930, alarm.dm
this line triggers the fire alarm's alarm() proc if there is a fire in the same loc and plays the sound.
it has no delay check on it, so it will play the sound until the fire is gone. repeatedly.
fire_alarm.ogg is eight seconds of ear-splitting fire alarm.

**Comment by afterthought2** [comment]
Closing; fixes merged. If further adjustment required can reopen.
