### ISSUE TITLE
Fire door inconsistency

### ISSUE THREAD

**Issue by ZirconiumWit** [NebulaSS13/Nebula#1643]
#### Description of issue
While testing on Exodus, a whole bunch of fire safety doors opened up all at once, allowing the cold vacuum into the station in ways it very much shouldn't have allowed. 

Someone mentioned opening one fire door in the area, leading to all other doors opening.  Unsure if that's related.   

#### Difference between expected and actual behavior
Those doors should have remained shuttered if no one was forcing them open

#### Steps to reproduce
Unsure.  There were fires and atmospheric breaches, and the fire doors decided that that none of these were important enough to remain shuttered

#### Specific information for locating

Emergency Shutters near the bridge, left of the doors leading to the dorms

#### Length of time in which bug has been known to occur

Today only

#### Client version, Server revision & Game ID

Client Version: 513
Server Revision: 38ce123cb4878492f2e6bf6e7e3d395d50eea402 - staging - 2021-05-15
Game ID: cb4-aYck
Current map: NSS Exodus

#### Issue bingo

- [ ] Issue could be reproduced at least once
- [ ] Issue could be reproduced by different players
- [ ] Issue could be reproduced in multiple rounds
- [x] Issue happened in a recent (less than 7 days ago) round
- [x] [Couldn't find an existing issue about this](https://github.com/NebulaSS13/Nebula/issues)

**Comment by MistakeNot4892** [comment]
This is likely related to the horrible runtime spam tied to zone deletion due to fires, which have been disabled. Going to close it for now and see if it crops up again in testing.

For reference, if you reset an atmos alarm, all the firedoors will go up regardless of danger.
