### ISSUE TITLE
syringe issue

### ISSUE THREAD

**Issue by ZirconiumWit** [NebulaSS13/Nebula#1644]
#### Description of issue
At one point while injecting a patient with styptic powder, I encountered an issue where the syringe was only injecting smaller and smaller fractions of medical dosages to the patient I was working on.  It reminded me of an issue where characters would FILL UP with atmospheric reagents while breathing until they didn't have room for injections, so the syringe would only inject approximately zero quantities of medication.  In this case, though, it cleared up after emptying the syringe and refilling it, so I'm convinced it was a syringe issue and not a bloated body full of air issue.

#### Difference between expected and actual behavior
Syringes should only administer a set amount, it should not behave like an eye dropper and administer smaller doses ad infinitum as the quantity remaining approaches zero.

#### Steps to reproduce
Wish I knew.  My character basically died while using that syringe-full of styptic and was adminbused back to full health for testing purposes, and I later encountered the issue - I don't think I had refilled the syringe in the meantime.  Could be related to my character dropping the syringe upon losing consciousness?

#### Specific information for locating

I had a patient with lots of trauma from void, a syringe, and an uncertain quantity of styptic powder in the syringe.  Unable to report with more specificity, unfortunately.

#### Length of time in which bug has been known to occur

Only saw it tonight.

#### Client version, Server revision & Game ID

Client Version: 513
Server Revision: 38ce123cb4878492f2e6bf6e7e3d395d50eea402 - staging - 2021-05-15
Game ID: cb4-aYck
Current map: NSS Exodus

#### Issue bingo

- [ ] Issue could be reproduced at least once
- [ ] Issue could be reproduced by different players
- [ ] Issue could be reproduced in multiple rounds
- [x] Issue happened in a recent (less than 7 days ago) round
- [x] [Couldn't find an existing issue about this](https://github.com/NebulaSS13/Nebula/issues)

**Comment by MistakeNot4892** [comment]
Going to close this for now, will reopen if it recurrs.
