### ISSUE TITLE
Shutters can sometimes be opened by throwing things at them.

### ISSUE THREAD

**Issue by SodiumShine** [NebulaSS13/Nebula#173]
Kinda wild that you can open secure shutters by throwing, say, a guitar at them.

Also, if a shutter has been forcibly opened, and it is part of a set, toggling the shutters as a group via a button causes the forcibly opened shutters to close, while all the others open, leaving them mismatched.

**Comment by afterthought2** [comment]
Just tried throwing guitars at shutters from various ranges with max skills. They did negligible damage. Can you give more specifics about what you were throwing, with what mob/skill/range, and whether the shutters were already damaged?

**Comment by quardbreak** [comment]
Tried to replicate and found what this is not just shutters, but entire `/obj/machinery/door` can have this issue
