### ISSUE TITLE
No mouse opacity when lying

### ISSUE THREAD

**Issue by ghost** [NebulaSS13/Nebula#1734]
#### Description of issue

![image](https://user-images.githubusercontent.com/30006750/120883158-4d98b180-c5e4-11eb-8416-cf73aa5f6728.png)
No additional data. No related runtimes. Call the ghostbusters.
The point: no mouse opacity for a mob (human) in lying condition. Both from observation and ingame as an another human. 
![image](https://user-images.githubusercontent.com/30006750/120883227-a49e8680-c5e4-11eb-9ccf-164fe169252a.png)
![image](https://user-images.githubusercontent.com/30006750/120883232-a8caa400-c5e4-11eb-9b76-6f35d12376c1.png)
Maybe it's a typing indicator issue. Or just typical "oh you" byond, who knows?
![image](https://user-images.githubusercontent.com/30006750/120883308-27274600-c5e5-11eb-85cd-6160062b20f3.png)
UPD: after i reconnected (closed DreamSeeker, opened it) the issue persisted.
Tho, that's so interesting: other player had nothing like this. 
![image](https://user-images.githubusercontent.com/30006750/120883412-b03e7d00-c5e5-11eb-9db3-a6dd8611edd1.png)
Permissions: me -  GameAdmin,
player - player. Maybe it somehow affects it

#### Difference between expected and actual behavior

Have a sane clicking ability / not have it

#### Steps to reproduce

1. Spawn a human
2. Wait for it to lay down
3. Try to click on it.

#### Specific information for locating

/mob/living/carbon/human (?) may be with other mobs as well

#### Length of time in which bug has been known to occur

Only today. This can be related with the new status effect indicators

#### Client version, Server revision & Game ID

Client Version: 514
Server Revision: 62fe0664b9f9918051101ad07fb1e5d854ce1897 - staging - 2021-06-05
Game ID: cco-aSUC
Current map: NSS Exodus

#### Issue bingo

- [x] Issue could be reproduced at least once
- [ ] Issue could be reproduced by different players
- [ ] Issue could be reproduced in multiple rounds
- [x] Issue happened in a recent (less than 7 days ago) round
- [x] [Couldn't find an existing issue about this](https://github.com/NebulaSS13/Nebula/issues)

**Comment by MistakeNot4892** [comment]
Can't reproduce this locally, wondering if it's related to #1355

**Comment by MarinaGryphon** [comment]
Would be good to know what mods are/were enabled when this happened.

**Comment by MistakeNot4892** [comment]
Will be curious to see if this still happens now that status markers have the correct flag and shouldn't interfere with mouse visibility.

**Comment by MistakeNot4892** [comment]
Haven't seen this since the AO and status markers got updated, please reopen if it shows up again.
