### ISSUE TITLE
Can't teleport via teleport hub

### ISSUE THREAD

**Issue by quardbreak** [NebulaSS13/Nebula#1760]
#### Description of issue

`Fart Bum bounces off the teleporter!`

#### Difference between expected and actual behavior

Not `Fart Bum bounces off the teleporter!`

#### Steps to reproduce

`Fart Bum bounces off the teleporter!`

#### Specific information for locating

`Fart Bum bounces off the teleporter!`

#### Length of time in which bug has been known to occur

Since teleportation rework.

#### Issue bingo

- [X] Issue could be reproduced at least once
- [ ] Issue could be reproduced by different players
- [X] Issue could be reproduced in multiple rounds
- [X] Issue happened in a recent (less than 7 days ago) round
- [X] [Couldn't find an existing issue about this](https://github.com/NebulaSS13/Nebula/issues)

**Comment by MistakeNot4892** [comment]
Are you throwing yourself at the teleporter or trying to move into it? Needs more info.

**Comment by quardbreak** [comment]
Move into. Seems throwing doesn't work too.
