### ISSUE TITLE
Blank textbook on Tradeship.

### ISSUE THREAD

**Issue by MistakeNot4892** [NebulaSS13/Nebula#1817]
#### Description of issue
Spotted the following book on the south side of the lowest level of the tradeship:
````
That's an alphabet book. It is a normal-sized item.
A blank textbook. (Notify admin)
````

#### Difference between expected and actual behavior
Probably shouldn't prompt to notify admin, or be blank.

#### Steps to reproduce
Unsure how it spawned.

#### Specific information for locating
None.

#### Length of time in which bug has been known to occur
No idea.

#### Client version, Server revision & Game ID
Current staging build.

#### Issue bingo
- [ ] Issue could be reproduced at least once
- [ ] Issue could be reproduced by different players
- [ ] Issue could be reproduced in multiple rounds
- [X] Issue happened in a recent (less than 7 days ago) round
- [X] [Couldn't find an existing issue about this](https://github.com/NebulaSS13/Nebula/issues)

**Comment by VNLoverMay** [comment]
Alphabet book is the name of the basic literacy skillbook. Did it function as such? If so, the issue might be specifically with changing the description on initialize.
