### ISSUE TITLE
Grab and drag does not work well with multiz movement.

### ISSUE THREAD

**Issue by ghostsheet** [NebulaSS13/Nebula#183]
~~First issue: ctrl-click grabbing an object then clicking on openspace turf with the grab, doesn't drag that object to the openspace turf (unlike other turfs). 
Clicking with the grab on a turf, normally move the object to the turf.~~

Second issue: ctrl-click grabbing objects doesn't like Multi Z movement, it doesn't allow you to pull objects up or down through space or through ladders.
Pulling objects should come up with you for space at the very least. 

~~Third issue: ctrl-click grabbing objects doesn't count atheletics or item size for movespeed delay. It should have some way to count and apply the encumbrance properly~~

**Comment by MistakeNot4892** [comment]
Encumberance is factored into move delay these days.
Will put a PR up with the first issue.
