### ISSUE TITLE
[QoL] Fabricator UI renders them nearly unusable at times

### ISSUE THREAD

**Issue by Kurgis** [NebulaSS13/Nebula#1842]
#### Description of issue

Autolathe, protolathe, circuit imprinter: Despite the categories, the Find function does not work with their menus due to an unknown issue (multiple people experienced this). This makes items near impossible to find because not only are objects not in alphabetical order, but there is no search function.

#### Difference between expected and actual behavior

I can find what I'm looking for; I cannot.

#### Steps to reproduce

Look for Seed Extractor in a menu where both Seed Storage and Honey Extractor exist, while you have 30+ items in a black + green thin-type font.

#### Length of time in which bug has been known to occur

Forever.

#### Client version, Server revision & Game ID

Downstream: Outreach
513 - cae48ed581a783fad60ce376bac09a1c521ff06f - ccT-cSuk

#### Issue bingo

- [x] Issue could be reproduced at least once
- [x] Issue could be reproduced by different players
- [ ] Issue could be reproduced in multiple rounds
- [x] Issue happened in a recent (less than 7 days ago) round
- [x] [Couldn't find an existing issue about this](https://github.com/NebulaSS13/Nebula/issues)

**Comment by MistakeNot4892** [comment]
I plan to add a search bar and alphabetized design lists this weekend.

**Comment by MistakeNot4892** [comment]
Barring display issues in #1951 this has been implemented.
