### ISSUE TITLE
Cannot throw things on partially obstructed tiles 

### ISSUE THREAD

**Issue by PsyCommando** [NebulaSS13/Nebula#1867]
#### Description of issue
Basically, if you got a tile with a window pane parrallel to the direction you're throwing an item, its going to collide as if it was in the way, but its clearly not.

#### Difference between expected and actual behavior
Throwing an item through a tile with a window pane on parallel to the direction of the throw should not stop the item from travelling.

#### Steps to reproduce
* Place window pane on tile in front.
* Rotate the pane so its not facing you or obstructing the tile in the direction of the throw.
* Throw the item on the tile past the window pane.
* Notice the item colliding with the pane even if it visibly wouldn't hit it.

#### Length of time in which bug has been known to occur

At least more than a month.

#### Issue bingo

- [x] Issue could be reproduced at least once
- [ ] Issue could be reproduced by different players
- [x] Issue could be reproduced in multiple rounds
- [x] Issue happened in a recent (less than 7 days ago) round
- [x] [Couldn't find an existing issue about this](https://github.com/NebulaSS13/Nebula/issues)

**Comment by MistakeNot4892** [comment]
Guessing this has something to do with the Bump() behavior changes, will need to maybe add some border flag checking to throw iteration/projectiles.
