### ISSUE TITLE
Graphical human artifact animation

### ISSUE THREAD

**Issue by quardbreak** [NebulaSS13/Nebula#1893]
#### Description of issue

![2021-07-13_23-51-04](https://user-images.githubusercontent.com/44920739/125622002-6b38af70-d6f1-4976-be78-590eb4995757.gif)

#### Difference between expected and actual behavior

I... suppose this shouldn't be like this.

#### Steps to reproduce

Unknown.

#### Length of time in which bug has been known to occur

Discovered today.

#### Client version, Server revision & Game ID

https://github.com/infinitystation/Nebula/commit/79fa623f247071753b5759dcf116078908873126

#### Issue bingo

- [X] Issue could be reproduced at least once
- [X] Issue could be reproduced by different players
- [X] Issue could be reproduced in multiple rounds
- [X] Issue happened in a recent (less than 7 days ago) round
- [X] [Couldn't find an existing issue about this](https://github.com/NebulaSS13/Nebula/issues)

**Comment by MistakeNot4892** [comment]
Can this be reproduced on Nebula?

**Comment by quardbreak** [comment]
Yes, I suppose this is part of scaling modpack.

**Comment by MistakeNot4892** [comment]
How was it reproduced?

**Comment by quardbreak** [comment]
It's purely random, but happens after joining in a round.

**Comment by MistakeNot4892** [comment]
- Can this be reproduced on Nebula specifically, not Infinity?
- What are any commonalities shared by characters that experience the bug?
- What are any commonalities in the environment when the bug is observed?
