### ISSUE TITLE
Breaking closets and/or crates don't drop object materials

### ISSUE THREAD

**Issue by quardbreak** [NebulaSS13/Nebula#1894]
#### Description of issue

Breaking closets and/or crates don't drop object materials.

#### Difference between expected and actual behavior

Should drop object's material.

#### Steps to reproduce

1. Grab toolbox
2. Try to destroy closet
3. It will drop contents, but not object's matter.

#### Length of time in which bug has been known to occur

Discovered today.

#### Client version, Server revision & Game ID

https://github.com/infinitystation/Nebula/commit/79fa623f247071753b5759dcf116078908873126

#### Issue bingo

- [X] Issue could be reproduced at least once
- [X] Issue could be reproduced by different players
- [X] Issue could be reproduced in multiple rounds
- [X] Issue happened in a recent (less than 7 days ago) round
- [X] [Couldn't find an existing issue about this](https://github.com/NebulaSS13/Nebula/issues)

**Comment by MistakeNot4892** [comment]
This is fixed for crafted closets in #1852 but I noticed mapped closets don't _have_ matter/material.

**Comment by MistakeNot4892** [comment]
Remind me to split the closet material changes out of #1852 to fix this.
