### ISSUE TITLE
Mapped decals, sometimes, don't apply

### ISSUE THREAD

**Issue by quardbreak** [NebulaSS13/Nebula#1904]
#### Description of issue

Expected:
![изображение](https://user-images.githubusercontent.com/44920739/125761028-5c34d2f9-9573-4fe9-af46-64fc579bf096.png)

Received:
![изображение](https://user-images.githubusercontent.com/44920739/125760904-334c5104-8dd0-48ec-abbb-5c10a223de45.png)

#### Difference between expected and actual behavior

Should apply.

#### Steps to reproduce

1. Place decals on glass floor, or on wood.
2. See the result.

#### Length of time in which bug has been known to occur

It's not discovered today, but still persists.

#### Client version, Server revision & Game ID

https://github.com/infinitystation/Nebula/commit/64687ebf0fcfec8e928f2482c6e20cf2783461a2

#### Issue bingo

- [X] Issue could be reproduced at least once
- [ ] Issue could be reproduced by different players
- [X] Issue could be reproduced in multiple rounds
- [X] Issue happened in a recent (less than 7 days ago) round
- [X] [Couldn't find an existing issue about this](https://github.com/NebulaSS13/Nebula/issues)

**Comment by out-of-phaze** [comment]
Has anyone been able to reproduce this recently?
