### ISSUE TITLE
TEG Won't make power

### ISSUE THREAD

**Issue by factory-station-13** [NebulaSS13/Nebula#1917]
#### Description of issue

I hooked up some nitro to a cooler, and some H2 to a heater

#### Difference between expected and actual behavior

Circulators got input and output, but the generator didn't make any power, and the circulators wouldn't spin

#### Steps to reproduce
hook up some nitro to a cooler, and some H2 to a heater, pump em into 2 circulators with a generator wired to an APC

#### Specific information for locating

generator circulator nitro h2 canisters and a heater and a cooler

#### Length of time in which bug has been known to occur

everytime I try

#### Client version, Server revision & Game ID

latest, I think

#### Issue bingo

- [ ] Issue could be reproduced at least once
- [ ] Issue could be reproduced by different players
- [ ] Issue could be reproduced in multiple rounds
- [ ] Issue happened in a recent (less than 7 days ago) round
- [ ] [Couldn't find an existing issue about this](https://github.com/NebulaSS13/Nebula/issues)

**Comment by MistakeNot4892** [comment]
![image](https://user-images.githubusercontent.com/2468979/127148959-89389c87-7566-4668-bffd-c0956267e761.png)
Can't reproduce on Exodus (dev branch). Standard SM engine setup works fine.
