### ISSUE TITLE
Medicine/armor/gun feedback review from another station player

### ISSUE THREAD

**Issue by quardbreak** [NebulaSS13/Nebula#1925]
#### Description of issue

Apparently, nebula have several issues with current balance of existing armor and guns.

All combat system parameters, armor, medicine and guns probably need take a good look to ensure what game balance work fine.

Quoting a person who give me info about current problems:

> %!the gun, which I can't to translate from RU to EN!% is a nerfed shit
you shoot at point-blank range into the your chest in the deadest armor
and you knock self for 2 seconds
you smear yourself with a bandage you go further
it's like cancer from new-bay, but it's even worse

![изображение](https://user-images.githubusercontent.com/44920739/126402988-cbc05c20-0da9-4cf5-bcf5-184b0af4d3cb.png)

#### Difference between expected and actual behavior

It should not affect on 

#### Steps to reproduce

Simulate the combat process.

#### Specific information for locating

Medicine, Armour, Guns

#### Length of time in which bug has been known to occur

It's a big balance issue since bay.

#### Client version, Server revision & Game ID

dev, stable and staging

**Comment by afterthought2** [comment]
Please explain more clearly. `it's like cancer from new-bay, but it's even worse` is unhelpful.

**Comment by quardbreak** [comment]
This means, what current nebula combat is wrong, and haven't changed since branched off from bay. People on bay haven't complain about combat at all, because they does not balanced combat as one of the main mechanics of interaction and conflict development.

For this reason, all russian forks had to make much changes into balance with long tests and numbers of unsuccessful re-balances for armor, bullet/laser bodypart impact, bodypart health, gun miss and shoot modifiers.

Someone might say, what Nebula is flexible enough for overriding gun/armor stats on downstream, but in my honest opinion, it should be balanced on upstream firstly, before people will notice what combat system doesn't provide enough balanced realism (in SS13 terms) on their forks. In short, people expect what they opponent won't beat them with toolbox, when you did like 4-5 shots in head, or, shoot on yourself with a currenty-avaliable-op-armor and have full resist with minimal negative effect which would cause person to change their tactics in combat to save their life.

**Comment by quardbreak** [comment]
Closing because this is technically not a bug and moving it into idea pit channel for future discussion.
