### ISSUE TITLE
You can select any lanugage in character preferences

### ISSUE THREAD

**Issue by quardbreak** [NebulaSS13/Nebula#1926]
#### Description of issue

![изображение](https://user-images.githubusercontent.com/44920739/126404764-2e6e144a-e212-426f-b563-c6e0c65281ac.png)

#### Difference between expected and actual behavior

You should unable to select robots, drones, changelings and any other languages in character preferences.

#### Steps to reproduce

1. Open character setup
2. Try select language
3. Find out what you can select changeling language (and perhaps, other ones)

#### Length of time in which bug has been known to occur

Discovered today by a reviewer.

#### Client version, Server revision & Game ID

latest dev

#### Issue bingo

- [ ] Issue could be reproduced at least once
- [X] Issue could be reproduced by different players
- [ ] Issue could be reproduced in multiple rounds
- [X] Issue happened in a recent (less than 7 days ago) round
- [X] [Couldn't find an existing issue about this](https://github.com/NebulaSS13/Nebula/issues)

**Comment by quardbreak** [comment]
Update: this works only if you have admin rights. IMO this shouldn't be like this, because it can confuse admins or make them abuse it.
Might be better to remove it because VV already have the special selections for adding/removing languages.

**Comment by afterthought2** [comment]
It's an intentional admin feature, been this way forever. Can discuss changing, but it's not a bug.
