### ISSUE TITLE
Turf translation deletes terminals

### ISSUE THREAD

**Issue by PsyCommando** [NebulaSS13/Nebula#1965]
#### Description of issue
When a turf with a terminal connected to a machine like an APC is translated, the code for when the machine is loose and is moved around triggers and the terminal is deleted. 

Pretty sure it happens around here according to some runtime we got when the terminal was deleted during translation:
```dm
/obj/item/stock_parts/power/terminal/proc/machine_moved(var/obj/machinery/machine, var/turf/old_loc, var/turf/new_loc)
    if(!terminal)
        events_repository.unregister(/decl/observ/moved, machine, src, .proc/machine_moved)
        return
    if(istype(new_loc) && (terminal.loc == get_step(new_loc, terminal_dir)))
        return     // This location is fine
    machine.visible_message(SPAN_WARNING("The terminal is ripped out of \the [machine]!"))
    qdel(terminal) // will handle everything via the destroyed event
```

We'd get an exception saying we attempted to forceMove a qdeleted terminal. And the callstack matches my hypothesis.

#### Difference between expected and actual behavior
Terminals should not be deleted during translation, only when the machine is pushed around or step() around. So the observer might need to be tweaked.

#### Steps to reproduce
Get a shuttle, land/dock it somewhere.
Notice the terminals are missing on all machines on the shuttle.

#### Issue bingo

- [x] Issue could be reproduced at least once
- [x] Issue could be reproduced by different players
- [x] Issue could be reproduced in multiple rounds
- [x] Issue happened in a recent (less than 7 days ago) round
- [x] [Couldn't find an existing issue about this](https://github.com/NebulaSS13/Nebula/issues)

**Comment by MistakeNot4892** [comment]
Could change that block to use a timer/callback to check if the terminal is still in the same relative position or not, asynchronously?

**Comment by afterthought2** [comment]
There's a system for this that I guess isn't being used here; would be nice if there was a better system, though (current one is awful).

**Comment by afterthought2** [comment]
Closing as this appears a downstream issue. The system mentioned in the previous comment is in fact used here and has been since summer '19.
