### ISSUE TITLE
Its really hard to align gas thrusters when building them

### ISSUE THREAD

**Issue by PsyCommando** [NebulaSS13/Nebula#1966]
#### Description of issue
The gas thruster is a pain in the ass to get to align properly because they ignore whatever direction the machine assembly code pass to their their New proc for some reasons.
If you create a gas thruster it will always face south. Which is the default direction for atmospheric/unary. And you can't unwrench them once assembled.
It should be an easy fix, but I wonder if just grabbing the direction in Initialize() won't break something?

#### Difference between expected and actual behavior
If the machine frame faces east the thruster should face east.

#### Steps to reproduce
Build a gas thruster from a machine frame you moved to face a particular direction that's not south.

#### Issue bingo

- [x] Issue could be reproduced at least once
- [x] Issue could be reproduced by different players
- [x] Issue could be reproduced in multiple rounds
- [x] Issue happened in a recent (less than 7 days ago) round
- [x] [Couldn't find an existing issue about this](https://github.com/NebulaSS13/Nebula/issues)

**Comment by PsyCommando** [comment]
Update seems like it can only have 2 possible directions, like regular pipes? It might just be missing something to allow it to face all 4 ways?

**Comment by afterthought2** [comment]
I tested this and successfully constructed `/obj/machinery/atmospherics/unary/engine` facing every direction. That said, it can be difficult to tell which way the assembly is facing, as it does not have directional sprites. If you have problems building these machines (or are referring to a different machine) reopen with reproduction steps and the machine's path. If it's the assembly not having directional sprites which is confusing, reopen under a separate issue.
