### ISSUE TITLE
Reinforcing glass with steel to make rglass doesn't stack the result

### ISSUE THREAD

**Issue by PsyCommando** [NebulaSS13/Nebula#1972]
#### Description of issue
If you reinforce glass panes with steel the resulting stack is dumped on the ground, but subsequent rglass sheets will just spawn new stacks of rglass instead of merging with the existing stack.

#### Difference between expected and actual behavior
The newly created reinforced stacks should merge with the existing stacks in the same tile or in the user's hands.

I noticed that the stacks when reinforcing don't call ``add_to_stacks`` so I tested calling it. Though it seems that doesn't cause the stacks to merge at all. I think it used to be called automatically on dropInto at one point, but it apparently isn't the case anymore?

#### Steps to reproduce
Pick a stack of glass and steel. Click with the steel on the glass. Notice as a new stack is created for all subsequent sheets of rglass you create.

#### Client version, Server revision & Game ID

On dev.

#### Issue bingo

- [x] Issue could be reproduced at least once
- [x] Issue could be reproduced by different players
- [x] Issue could be reproduced in multiple rounds
- [x] Issue happened in a recent (less than 7 days ago) round
- [x] [Couldn't find an existing issue about this](https://github.com/NebulaSS13/Nebula/issues)

**Comment by MistakeNot4892** [comment]
We talked about adding it to dropInto but it hasn't ever been in there as far as I could tell.

**Comment by PsyCommando** [comment]
It might have been a ps13 thing then.
