### ISSUE TITLE
Items don't burn

### ISSUE THREAD

**Issue by PsyCommando** [NebulaSS13/Nebula#1974]
#### Description of issue
For some reasons items like clothing, portable electronics, bags, blueprints, loose cables and components do not burn to ashes in a raging white hot hydrogen fire.
I also noticed that all the machinery barring computers, was completely unscathed from the fire. Regular pipes, pumps, connectors, canisters, apcs, smes, pacman generator, all perfectly fine after the fire. Only a canister with hydrogen in it bursted open, the oxygen containing one is completely unharmed.
It did destroy a steel wall though, and broke all the lightbulbs in the place.

#### Difference between expected and actual behavior
Normally, most items would have turned into ash piles. Most machines would have fried their components at the very least, or just completely broken down/turned to ashes.

#### Steps to reproduce
Start a big hydrogen fire in a room with misc items on the ground and machinery. Notice as barely anything is destroyed.

#### Issue bingo

- [x] Issue could be reproduced at least once
- [ ] Issue could be reproduced by different players
- [x] Issue could be reproduced in multiple rounds
- [x] Issue happened in a recent (less than 7 days ago) round
- [x] [Couldn't find an existing issue about this](https://github.com/NebulaSS13/Nebula/issues)

**Comment by MistakeNot4892** [comment]
Machine damage is probably valid but as far as I know items have never burned to ash in fires.

**Comment by MistakeNot4892** [comment]
Calling this a feature request, please open a thread on the Discord for it - CrimsonShrike and I will likely have thoughts as it ties back into the general fire rework that has been discussed occasionally.
