### ISSUE TITLE
Getting an infection causes 60c+ fevers

### ISSUE THREAD

**Issue by PsyCommando** [NebulaSS13/Nebula#1975]
#### Description of issue
For some reasons getting a mild infection sends your body temp all the way into the high 60c (~141 F). It reached 70c after a while.
Apparently fevers rarely go above 42c, and the highest fever ever recorded was 46c.. So I'm assuming something is going very wrong with this?

#### Difference between expected and actual behavior
I'd expect a fever to bring the char's body temp to something below 50c..

#### Steps to reproduce
Get an infected wound. Use a medical scanner on yourself. Check body temperature.

#### Issue bingo

- [x] Issue could be reproduced at least once
- [ ] Issue could be reproduced by different players
- [ ] Issue could be reproduced in multiple rounds
- [x] Issue happened in a recent (less than 7 days ago) round
- [x] [Couldn't find an existing issue about this](https://github.com/NebulaSS13/Nebula/issues)

**Comment by MistakeNot4892** [comment]
Generally speaking, bodytemp is a mess. Humans have no heat capacity and bodytemp is increased instantly based on environmental/fever factors. Entire thing needs rewriting to have sane bounds/meaning associated.

**Comment by MistakeNot4892** [comment]
Closing this for now as it's not a bug, it's just our terrible infection system. This should be reviewed/addressed down the track when heat capacity is modelled for atoms, and mobs can separate internal and external temperature so fevers can be less absurd.
