### ISSUE TITLE
Infinite loop in preference code

### ISSUE THREAD

**Issue by PsyCommando** [NebulaSS13/Nebula#1999]
#### Description of issue
There's an infinite proc call loop in the preference code.

Here's a breakdown of the procs in question:
```
 /client/proc/get_preference_value(var/preference)
 	if(prefs)
 		var/datum/client_preference/cp = get_client_preference(preference)
 		if(cp)
 			return prefs.preference_values[cp.key]
 		else
 			return null
 	else
 		log_error("Client is lacking preferences: [log_info_line(src)]") // <------------ Causes infinite loop

 /proc/log_error(text)
	 error(text)
	 to_debug_listeners(text, "ERROR")

 /proc/to_debug_listeners(text, prefix = "DEBUG")
 	for(var/client/C in global.admins)
 		if(C.get_preference_value(/datum/client_preference/staff/show_debug_logs) == PREF_SHOW)
 			to_chat(C, "[prefix]: [text]")

```

Basically, get_preference_value can call log_error, which calls get_preference_value, which can call log_error, and so on..
Also, if you try to log_debug, log_error, or whatever before prefs are loaded it runtimes and crash just for logging stuff, which isn't very cool. Would probably be nice to add some sort of check for whether the prefs are loaded first in to_debug_listener.

#### Issue bingo

- [x] Issue could be reproduced at least once
- [ ] Issue could be reproduced by different players
- [x] Issue could be reproduced in multiple rounds
- [x] Issue happened in a recent (less than 7 days ago) round
- [x] [Couldn't find an existing issue about this](https://github.com/NebulaSS13/Nebula/issues)

**Comment by MistakeNot4892** [comment]
I'm not even clear on why that should be reporting an error - surely it just means prefs aren't loaded for whatever reason.

**Comment by PsyCommando** [comment]
> 
> 
> I'm not even clear on why that should be reporting an error - surely it just means prefs aren't loaded for whatever reason.

Prefs are loaded later on during init. If you log_debug/log_error anything before prefs are loaded this happens. 

In another case the prefs were partially loaded so the list of prefs was null and it would runtime.

**Comment by MistakeNot4892** [comment]
Yeah what I mean is I'm not sure why we need to report pref failures to that particular proc - prefs being null is expected in some circumstances so reporting it at all is a bit wonky.

**Comment by PsyCommando** [comment]
Anyways, I put up a fix for this:
#2012
