### ISSUE TITLE
Some devices do not reconnect to their network after a power outage unless reconnected manually.

### ISSUE THREAD

**Issue by MistakeNot4892** [NebulaSS13/Nebula#2004]
#### Description of issue
Reporting this secondhand so will be a bit vague.
Some devices (specifically the software server in this case) will lose connection to the network if the network suffers a power outage, and will not reconnect unless you go into their network settings and forcibly refresh them.
This was also observed when testing the network comms branch (#733).

#### Difference between expected and actual behavior
Things should drop their network properly on a power outage and reconnect next time they need their network as happens with a newly spawned device.

#### Steps to reproduce
Cycle the APC on the network mainframe.
Try to use the software vendor.

#### Specific information for locating
Nothing springs to mind.

#### Length of time in which bug has been known to occur
Unclear, probably since the network rewrites.

#### Client version, Server revision & Game ID
Current dev branch.

#### Issue bingo

- [X] Issue could be reproduced at least once
- [X] Issue could be reproduced by different players
- [X] Issue could be reproduced in multiple rounds
- [X] Issue happened in a recent (less than 7 days ago) round
- [X] [Couldn't find an existing issue about this](https://github.com/NebulaSS13/Nebula/issues)

**Comment by comma** [comment]
It seems that issue is mostly relays - other devices try to reconnect when they need network, but if relay is down, they're fucked.
Going to see if I can make relays less lazy.

**Comment by MistakeNot4892** [comment]
Still occurring on my tcomms dev branch.
