### ISSUE TITLE
glass doors only want to be broken by someone who has access

### ISSUE THREAD

**Issue by ZirconiumWit** [NebulaSS13/Nebula#2021]
#### Description of issue
![image](https://user-images.githubusercontent.com/59771903/130373891-26b4f70a-58df-4a12-ab7a-a1d52d12f2a5.png)
When breaking a glass door, a character using a standard tool such as a crowbar respectfully defers to the computer to see if they have the necessary credentials to access whatever is behind the interior door, even on harm intent.  Characters using more general items, like fire extinguishers, are slightly less careful about ensuring that they're allowed to be wherever they are.
![image](https://user-images.githubusercontent.com/59771903/130374022-1a2a8564-d7e1-46f7-a5b3-3af2553e841f.png)
Not a huge deal, but there it is.

#### Difference between expected and actual behavior
characters on harm intent are supposed to throw caution to the wind, even going so far as to walk right past caution tape!  

#### Steps to reproduce
Use crowbar on interior glass doors

#### Specific information for locating

The access lock flashes red! You lack the access to unlock this.

#### Length of time in which bug has been known to occur

Just noticed during last test round, which was very short.

#### Client version, Server revision & Game ID

Client Version: 513
Server Revision: 72ee2adb5b76c6af6716da55e5342522548219e5 - staging - 2021-08-21
Game ID: cdD-b8tj
Current map: Tradeship Ocelot Alpha

#### Issue bingo

- [x] Issue could be reproduced at least once
- [ ] Issue could be reproduced by different players
- [ ] Issue could be reproduced in multiple rounds
- [x] Issue happened in a recent (less than 7 days ago) round
- [x] [Couldn't find an existing issue about this](https://github.com/NebulaSS13/Nebula/issues)

**Comment by afterthought2** [comment]
Probably worth discussing in greater generality: machinery prioritizes all "tool" interactions regardless of intent, partly in order to make it easier to interact with, partly out of inertia. Could be modified at machinery level if deemed desirable.
