### ISSUE TITLE
dragging items between z-levels is odd

### ISSUE THREAD

**Issue by ZirconiumWit** [NebulaSS13/Nebula#2022]
#### Difference between expected and actual behavior
You can drag items up stairs but not down stairs.  I tried this on multiple floors and it remained constant between every floor I tried it on.  I tried this with a cotton office chair and with the roller bed, as well as a crate.  The nice thing about a solid object like a crate is, you can push it down the stairs and pull it up the stairs, so there's a workaround, but objects you can pass through like an office chair or an empty rollerbed is more difficult to find workarounds for.

#### Steps to reproduce
pull items toward a staircase.  You'll probably succeed at dragging the item upstairs, but you'll have trouble dragging it down.

#### Specific information for locating

n/a, probably.

#### Length of time in which bug has been known to occur

Just discovered it today.

#### Client version, Server revision & Game ID

Client Version: 513
Server Revision: 72ee2adb5b76c6af6716da55e5342522548219e5 - staging - 2021-08-21
Game ID: cdF-aboo
Current map: Tradeship Ocelot Alpha

#### Issue bingo

- [x] Issue could be reproduced at least once
- [ ] Issue could be reproduced by different players
- [ ] Issue could be reproduced in multiple rounds
- [x] Issue happened in a recent (less than 7 days ago) round
- [x] [Couldn't find an existing issue about this](https://github.com/NebulaSS13/Nebula/issues)

**Comment by MistakeNot4892** [comment]
Overlaps with #183
