### ISSUE TITLE
Drone Lights are Very Weak

### ISSUE THREAD

**Issue by Mazianni** [NebulaSS13/Nebula#2069]
#### Description of issue

Mirror of https://github.com/HearthOfHestia/Nebula/issues/46

#### Difference between expected and actual behavior

Drone flashlights could not be super weak.

#### Steps to reproduce
1. Be maint drone.
2. Turn light on.
3. Still dark.

#### Specific information for locating

Maint drones.

#### Length of time in which bug has been known to occur

Whenever the lighting power changes happened.

#### Issue bingo

- [x] Issue could be reproduced at least once
- [x] Issue could be reproduced by different players
- [x] Issue could be reproduced in multiple rounds
- [x] Issue happened in a recent (less than 7 days ago) round
- [x] [Couldn't find an existing issue about this](https://github.com/NebulaSS13/Nebula/issues)

**Comment by MistakeNot4892** [comment]
I am pretty sure I fixed this a month ago, are you definitely up to date? Can you send a screenshot?

**Comment by Mazianni** [comment]
might just be out of date on this one

**Comment by MistakeNot4892** [comment]
Can't reproduce on dev - they're dim, but nowhere near as dim as the bug report on Hearth:
![image](https://user-images.githubusercontent.com/2468979/135781754-cd0d5c18-42dc-4bd2-869e-4ca33ab54ce0.png)

**Comment by MistakeNot4892** [comment]
Please reopen if you can repro on Neb.
