### ISSUE TITLE
The holster breaks when using a hotkey

### ISSUE THREAD

**Issue by SolatK** [NebulaSS13/Nebula#2073]
#### Description of issue
The holster breaks when using H button 

#### Steps to reproduce
1) Take a gun
2) press H several times when holster is attached to your uniform
3) Now by pressing H the gun always appears in your hand, wherever you put it

#### Length of time in which bug has been known to occur

today

#### Client version, Server revision & Game ID

last dev

#### Issue bingo

- [x] Issue could be reproduced at least once
- [x] Issue could be reproduced by different players
- [x] Issue could be reproduced in multiple rounds
- [x] Issue happened in a recent (less than 7 days ago) round
- [x] [Couldn't find an existing issue about this](https://github.com/NebulaSS13/Nebula/issues)

**Comment by comma** [comment]
Holster extension doesn't clear reference to the holster, only happens if doing this via hotkey
