### ISSUE TITLE
icon blend problems when change bodytype 

### ISSUE THREAD

**Issue by SolatK** [NebulaSS13/Nebula#2075]
#### Description of issue
If you change the bodytype then icon_blend is not always updated

#### Difference between expected and actual behavior
it shouldn't

#### Steps to reproduce
1) change bodytype with different blend types
2)it doesn't work as you expect

#### Client version, Server revision & Game ID

![изображение](https://user-images.githubusercontent.com/29740451/132891372-0a482662-6274-4ba4-b460-2380660d1a3a.png)

#### Issue bingo

- [x] Issue could be reproduced at least once
- [x] Issue could be reproduced by different players
- [x] Issue could be reproduced in multiple rounds
- [x] Issue happened in a recent (less than 7 days ago) round
- [x] [Couldn't find an existing issue about this](https://github.com/NebulaSS13/Nebula/issues)

**Comment by MistakeNot4892** [comment]
This is very odd. If you close and reopen the char setup panel it applies properly, and it looks fine if you join with that slot.

**Comment by MistakeNot4892** [comment]
Tail overlays are also not cleared properly on changing bodytype so this seems to be a broader issue than specifically the blend mode.

**Comment by SolatK** [comment]
works fine

**Comment by MistakeNot4892** [comment]
Observed this myself on staging tests the other night when I was respriting birds. :(

Specifically changing blend mode caused the tail blending to bug out.

**Comment by MistakeNot4892** [comment]
Noticing that the preview doesn't properly update or apply bodytype-specific icons either - during testing of the vox bodytype branch it was putting the wrong beak/eyes overlays on.

**Comment by MistakeNot4892** [comment]
https://github.com/ScavStation/ScavStation/issues/622
