### ISSUE TITLE
runtime at char loading and setup breaking

### ISSUE THREAD

**Issue by SolatK** [NebulaSS13/Nebula#2077]
#### Description of issue
If you load an empty slot, then you have a runtime error.
But if you enter new round with empty slot you character setup broke
![изображение](https://user-images.githubusercontent.com/29740451/132898596-3a7bc589-78d7-4be2-920d-61fd6ea92f9d.png)

[06:00:00] Runtime in skill_selection.dm, line 113: Cannot execute null.skills from age().
proc name: sanitize skills (/datum/preferences/proc/sanitize_skills)
src: /datum/preferences (/datum/preferences)
call stack:
/datum/preferences (/datum/preferences): sanitize skills(/list (/list))
Occupation (/datum/category_item/player_setup_item/occupation): sanitize character()
Occupation (/datum/category_group/player_setup_category/occupation_preferences): load character(/datum/pref_record_reader/null... (/datum/pref_record_reader/null_reader))
/datum/category_collection/pla... (/datum/category_collection/player_setup_collection): load character(/datum/pref_record_reader/null... (/datum/pref_record_reader/null_reader))
/datum/preferences (/datum/preferences): load character(4)
/datum/preferences (/datum/preferences): load data()
/datum/preferences (/datum/preferences): setup()
/datum/preferences (/datum/preferences): setup preferences(1)
Character Setup (/datum/controller/subsystem/character_setup): Initialize(652823)
Character Setup (/datum/controller/subsystem/character_setup): DoInitialize(652823)
Master (/datum/controller/master): Initialize(10, 0)

#### Steps to reproduce
1) Load empty slot
2) close and restart the server
3) join the server again
4) char setup is boken

#### Client version, Server revision & Game ID

Server Revision: 1f703d4f8dacfecea7f5f7922ba25ea695177159 - a7f5f7922ba25ea695177159 - 2021-09-10

#### Issue bingo

- [x] Issue could be reproduced at least once
- [x] Issue could be reproduced by different players
- [x] Issue could be reproduced in multiple rounds
- [x] Issue happened in a recent (less than 7 days ago) round
- [x] [Couldn't find an existing issue about this](https://github.com/NebulaSS13/Nebula/issues)

**Comment by MistakeNot4892** [comment]
I wonder if it's loading skills before loading species?

**Comment by afterthought2** [comment]
As far as I can tell, the null prefs reader loads species to be null. This is invalid, but species is not sanitized (??). Were it to be sanitized, you may at that point run into ordering issues. As you can see in the runtime, it is skill sanitize, not skill load, that checks species.
