### ISSUE TITLE
roundstart character loading is not correct

### ISSUE THREAD

**Issue by SolatK** [NebulaSS13/Nebula#2078]
#### Description of issue
Sometimes equipment, body type or markings are not loaded at the roundstart. Cliking at reload slot fixes that.

#### Difference between expected and actual behavior
The character must be fully loaded

#### Steps to reproduce
1) Make character with some clothing and different bodytype
2) Save it
3) Restart the server
4) Open charsetup. The character is half loaded.

#### Specific information for locating

Perhaps the problem with the loadout is that it is in the modpack

#### Client version, Server revision & Game ID

Server Revision: 1f703d4f8dacfecea7f5f7922ba25ea695177159 - a7f5f7922ba25ea695177159 - 2021-09-10

#### Issue bingo

- [x] Issue could be reproduced at least once
- [x] Issue could be reproduced by different players
- [x] Issue could be reproduced in multiple rounds
- [ ] Issue happened in a recent (less than 7 days ago) round
- [x] [Couldn't find an existing issue about this](https://github.com/NebulaSS13/Nebula/issues)

**Comment by MistakeNot4892** [comment]
Will need retesting after #2109, can't reproduce on that branch with a neo-avian.

**Comment by MistakeNot4892** [comment]
Can no longer reproduce on dev.

**Comment by MistakeNot4892** [comment]
Please reopen if this reocurrs.

**Comment by SolatK** [comment]
reocurrs

**Comment by SolatK** [comment]
Not occure if join to server before master controller starts processing

**Comment by SolatK** [comment]
Steps to reproduce
1. create character and give him some stuff from avian loaduot
2. save and restart server
3. join after master controller start
4. it appears
