### ISSUE TITLE
Trader and drugs

### ISSUE THREAD

**Issue by SolatK** [NebulaSS13/Nebula#2084]
#### Description of issue
You do not know what exactly the merchant is selling you, even if an experienced medic
![изображение](https://user-images.githubusercontent.com/29740451/132967074-05a5fd14-0e5c-4bd5-9f9e-1fad37240d84.png)

#### Difference between expected and actual behavior
You should know what you are buying

#### Steps to reproduce
1) try to buy medicine from a merchant

#### Issue bingo

- [x] Issue could be reproduced at least once
- [x] Issue could be reproduced by different players
- [x] Issue could be reproduced in multiple rounds
- [x] Issue happened in a recent (less than 7 days ago) round
- [x] [Couldn't find an existing issue about this](https://github.com/NebulaSS13/Nebula/issues)

**Comment by MistakeNot4892** [comment]
Ask Your Pharmacist About Xycopilophen™️ Today!

**Comment by MistakeNot4892** [comment]
Thoughts on this: a 'More Info' button that shows up for specific atoms if the viewer has a skill rank or other condition (alien knowledge, aspect, etc).
