### ISSUE TITLE
Things get stuck in your hands

### ISSUE THREAD

**Issue by SolatK** [NebulaSS13/Nebula#2085]
#### Description of issue
Things get stuck in your hands and there is no way to drop it

#### Steps to reproduce
1) take something in your hand
2) use rejuvenate
3) the item is stuck!

#### Issue bingo

- [x] Issue could be reproduced at least once
- [x] Issue could be reproduced by different players
- [x] Issue could be reproduced in multiple rounds
- [x] Issue happened in a recent (less than 7 days ago) round
- [x] [Couldn't find an existing issue about this](https://github.com/NebulaSS13/Nebula/issues)

**Comment by MistakeNot4892** [comment]
As a workaround you can click the item with your empty hand to swap hands and it puts it back in your hand properly. The issue is due to rejuvenate deleting and recreating your limbs I think.

**Comment by SolatK** [comment]
> 
> 
> As a workaround you can click the item with your empty hand to swap hands and it puts it back in your hand properly. The issue is due to rejuvenate deleting and recreating your limbs I think.

I was able to pick up two objects in one hand after that. And the stuck object cannot be removed in any way, only delete.

**Comment by SolatK** [comment]
> swap hands and it puts it back in your hand properly

Checked again and it worked. Last time I had a box in my hands and it didn't work.
