### ISSUE TITLE
Doors can not be set to require one access.

### ISSUE THREAD

**Issue by Mazianni** [NebulaSS13/Nebula#2105]
#### Description of issue

Doors can no longer be set to only require one access.

#### Difference between expected and actual behavior

Be able to set doors to require only one access.

#### Steps to reproduce

Create a door with multiple accesses.
Door now requires all accesses instead of one and can not be set to require just one.

#### Specific information for locating

Airlocks.

#### Length of time in which bug has been known to occur
Since the access refactor.

#### Client version, Server revision & Game ID

Latest.

#### Issue bingo

- [x] Issue could be reproduced at least once
- [x] Issue could be reproduced by different players
- [x] Issue could be reproduced in multiple rounds
- [x] Issue happened in a recent (less than 7 days ago) round
- [x] [Couldn't find an existing issue about this](https://github.com/NebulaSS13/Nebula/issues)

**Comment by afterthought2** [comment]
Please read [this guide](https://github.com/NebulaSS13/Nebula/wiki/Access) for how to add what used to be called `req_one_access`. If there are specific issues found with the new implementation, open a new issue.

**Comment by afterthought2** [comment]
Re-opening because it's not clear with the new hardware lock implementation that doors and locks properly respect the access format. Certainly the UI aspects are inadequate.

**Comment by comma** [comment]
Works On My Machine

I took the access lock out of some door and set it to require either Medical, Captain or Sec access. Note that you need to change le mode of operation for that on the top 

![image](https://user-images.githubusercontent.com/1300258/134357319-0c85cb9d-005c-4b84-865c-d9d5b09827bf.png)

It set lock's access to a proper format for OR access: list(list(med,cap,sec))

![IEfp1UT](https://user-images.githubusercontent.com/1300258/134357575-aac9a146-5f69-4168-aa6b-9121dc4ebe5c.png)

Then I made myself an ID that only had medical access, and was able to open the door

![image](https://user-images.githubusercontent.com/1300258/134357640-e535006c-f706-466b-9ec4-1dd9c5d6b56e.png)

**Comment by comma** [comment]
For auto-setting from area it uses exact same procs as before the changes, so mapped doors should work with OR accesses too provided areas are set up for that.

**Comment by MistakeNot4892** [comment]
Closing as discussed on Discord.
