### ISSUE TITLE
Robots don't take fall damage

### ISSUE THREAD

**Issue by ghost** [NebulaSS13/Nebula#2110]
#### Description of issue

As usual, `/silicon/robot` is wonky and doesn't take any noticeable damage after falling down the tradeship elevator shaft.

#### Difference between expected and actual behavior

They should probably be damaged when they fall 4 levels, however instead they don't even get a dent.

#### Steps to reproduce

1. Spawn as Robot.
2. Go to open space.
3. Fall down open space.
4. Check health.

#### Specific information for locating

`/mob/living/silicon/robot`

#### Length of time in which bug has been known to occur

Since 9-19-2021.

#### Client version, Server revision & Game ID

Client Version: 513
Server Revision: b98855421444ed800c0f915ea18b32a41215b7be - staging - 2021-08-25
Game ID: cd6-aZaQ
Current map: Tradeship Ocelot Alpha

#### Issue bingo

- [x] Issue could be reproduced at least once
- [ ] Issue could be reproduced by different players
- [ ] Issue could be reproduced in multiple rounds
- [x] Issue happened in a recent (less than 7 days ago) round
- [x] [Couldn't find an existing issue about this](https://github.com/NebulaSS13/Nebula/issues)

**Comment by MistakeNot4892** [comment]
This isn't a thing on Bay either.
