### ISSUE TITLE
rocket nozzles use to much power

### ISSUE THREAD

**Issue by SolatK** [NebulaSS13/Nebula#2112]
#### Description of issue
Turning on the engines on the ship causes the APC to discharge very quickly.

#### Difference between expected and actual behavior
The engine already consumes gas, I don't think it should consume kilowatts of energy

#### Steps to reproduce
1) turn on bearcat engines 
2) fly sometime
3) ENGINES POWER CRITICAL!

#### Issue bingo

- [x] Issue could be reproduced at least once
- [x] Issue could be reproduced by different players
- [x] Issue could be reproduced in multiple rounds
- [x] Issue happened in a recent (less than 7 days ago) round
- [x] [Couldn't find an existing issue about this](https://github.com/NebulaSS13/Nebula/issues)

**Comment by comma** [comment]
https://github.com/NebulaSS13/Nebula/pull/2368
