### ISSUE TITLE
cant take off clothes from buckled human

### ISSUE THREAD

**Issue by SolatK** [NebulaSS13/Nebula#2113]
#### Description of issue
cant take off clothes from buckled human

#### Difference between expected and actual behavior
?

#### Steps to reproduce
1) buckle someone to something like a chair or rollerbed 
2)try to take off it clothes

#### Issue bingo

- [x] Issue could be reproduced at least once
- [ ] Issue could be reproduced by different players
- [x] Issue could be reproduced in multiple rounds
- [x] Issue happened in a recent (less than 7 days ago) round
- [x] [Couldn't find an existing issue about this](https://github.com/NebulaSS13/Nebula/issues)

**Comment by MistakeNot4892** [comment]
Needs more information. What happens instead? Do you get the strip menu or just no response?

**Comment by SolatK** [comment]
> 
> 
> Needs more information. What happens instead? Do you get the strip menu or just no response?

No responce, no runtimes

**Comment by MistakeNot4892** [comment]
Reproduced on stable.
