### ISSUE TITLE
low total_health makes you in constant shock

### ISSUE THREAD

**Issue by SolatK** [NebulaSS13/Nebula#2115]
#### Description of issue
neocorvids as an example have total_health = 80, And 120 brute damage puts them in constant shock. They cant get up and use some meds, but they don't die

It is necessary to set limbs hp to (health *= total_health / defalut_total_health) or something like this. So that death comes instead of permanent shock.
#### Difference between expected and actual behavior
The character must either die or have enough time out of shock to escape.

#### Steps to reproduce
1) create some species whith total_health lower than 100
2) deal 120 damage

#### Issue bingo

- [x] Issue could be reproduced at least once
- [x] Issue could be reproduced by different players
- [x] Issue could be reproduced in multiple rounds
- [x] Issue happened in a recent (less than 7 days ago) round
- [x] [Couldn't find an existing issue about this](https://github.com/NebulaSS13/Nebula/issues)

**Comment by MistakeNot4892** [comment]
Tested on dev with suggested change, seems to work ok. Death does take awhile to reach but shock slowly ticks up until it stops your heart.
