### ISSUE TITLE
F4 opens 2 me window

### ISSUE THREAD

**Issue by SolatK** [NebulaSS13/Nebula#2116]
#### Description of issue
![изображение](https://user-images.githubusercontent.com/29740451/134774160-917ccc95-c6a3-4dba-babb-4afb07582cd7.png)

#### Difference between expected and actual behavior
there must be one

#### Steps to reproduce
press f4

#### Issue bingo

- [x] Issue could be reproduced at least once
- [x] Issue could be reproduced by different players
- [x] Issue could be reproduced in multiple rounds
- [x] Issue happened in a recent (less than 7 days ago) round
- [x] [Couldn't find an existing issue about this](https://github.com/NebulaSS13/Nebula/issues)

**Comment by MistakeNot4892** [comment]
Should be fixed by #2134.
