### ISSUE TITLE
ship control button didnt work

### ISSUE THREAD

**Issue by SolatK** [NebulaSS13/Nebula#2117]
#### Description of issue
![изображение](https://user-images.githubusercontent.com/29740451/134783818-375cf4f1-8ce4-4dd0-851b-d7cf929b47b3.png)

#### Difference between expected and actual behavior
This button should stop the ship, but it does not stop

#### Steps to reproduce
1) fly
2) press the button

#### Length of time in which bug has been known to occur

long time

#### Client version, Server revision & Game ID

82d4c5cfb172f50d810406d4dff165f0da1e76a0 - dev - 2021-09-25

#### Issue bingo

- [x] Issue could be reproduced at least once
- [x] Issue could be reproduced by different players
- [x] Issue could be reproduced in multiple rounds
- [x] Issue happened in a recent (less than 7 days ago) round
- [x] [Couldn't find an existing issue about this](https://github.com/NebulaSS13/Nebula/issues)

**Comment by MistakeNot4892** [comment]
This button only works if your speed is below a certain point, otherwise you need to negate your momentum with thrust in the opposite direction. How fast were you going when you tried to use it?

**Comment by comma** [comment]
It's supposed to always try to burn in direction opposite to current speed, must be some bug with the maths then.

**Comment by MistakeNot4892** [comment]
@ZirconiumWit couldn't repro this on staging, please open if it is still an issue.

**Comment by SolatK** [comment]
![изображение](https://user-images.githubusercontent.com/29740451/169424068-10ad636e-0ad5-4fa1-aca4-1fd815b49b1f.png)
works only if ship moves on this directions
