### ISSUE TITLE
Dropping an item in your offhand while holding a any riot shield nulls its item_state

### ISSUE THREAD

**Issue by chaoko99** [NebulaSS13/Nebula#2126]
#### Description of issue
See title

#### Difference between expected and actual behavior
I expect it to continue having an item state.

#### Steps to reproduce
Pick up /obj/item/shield/riot, drop item in your offhand, icon_state is set to null.

VERY BAD

#### Specific information for locating

/obj/item/shield/riot

#### Length of time in which bug has been known to occur

https://github.com/NebulaSS13/Nebula/commit/1cce4b018f8f15bc8d998656493ff32bf7a609f8 probably this PR

#### Client version, Server revision & Game ID

Client Version: 514
Server Revision: 92631286f7bb11f9824df588d3b0b81e6510f45b - shieldsprite - 2021-09-29
Game ID: ceh-aAQN
Current map: The Example

#### Issue bingo

- [x] Issue could be reproduced at least once
- [ ] Issue could be reproduced by different players
- [ ] Issue could be reproduced in multiple rounds
- [ ] Issue happened in a recent (less than 7 days ago) round
- [x] [Couldn't find an existing issue about this](https://github.com/NebulaSS13/Nebula/issues)

**Comment by MistakeNot4892** [comment]
The linked commit doesn't mess with wielded stuff, it was more likely the general collapse of wielded items into /obj/item. Will see if I can spot where it does the null.

**Comment by MistakeNot4892** [comment]
Can't reproduce this on current Nebula dev. Shields don't change icon state at all.

**Comment by MistakeNot4892** [comment]
Please reopen with specific steps for reproducing on dev or stable.
