### ISSUE TITLE
Can't build wall girders in any way

### ISSUE THREAD

**Issue by anconfuzedrock** [NebulaSS13/Nebula#2135]
#### Description of issue
Doesn't seem to be anything in the crafting menu for steel struts or sheets about building a wall girder or wall frame or low wall frame. nothing about supports or girders or nothing.

#### Difference between expected and actual behavior
-should be able to craft wall supports in some way

#### Steps to reproduce
-press z with steel or struts

#### Specific information for locating

Client Version: 514
Server Revision: bb9abc4e2293b525ba2dff819cfdce4519cf2d8c - dev - 2021-09-28
Game ID: cej-dMEV
Current map: Tradeship Ocelot Alpha

aalso seen on hearth of hestia
#### Length of time in which bug has been known to occur

Saw it a few days ago 

#### Issue bingo

- [x] Issue could be reproduced at least once
- [x] Issue could be reproduced by different players
- [x] Issue could be reproduced in multiple rounds
- [x] Issue happened in a recent (less than 7 days ago) round
- [x] [Couldn't find an existing issue about this](https://github.com/NebulaSS13/Nebula/issues)

**Comment by MistakeNot4892** [comment]
Leaving a note for myself when I get to this one - borgs/drones need a cyborg strut subtype.
