### ISSUE TITLE
Away Sites fail to Space Transition

### ISSUE THREAD

**Issue by Mazianni** [NebulaSS13/Nebula#2136]
#### Description of issue

If you hit the space edge of an away site, you do not transit.

#### Difference between expected and actual behavior

I should float off into an empty Z.

#### Steps to reproduce

Find Space-based away site. 
Jump towards edge.
Get stuck on edge forever.

#### Specific information for locating

Space.

#### Length of time in which bug has been known to occur

Unknown.

#### Issue bingo

- [x] Issue could be reproduced at least once
- [x] Issue could be reproduced by different players
- [x] Issue could be reproduced in multiple rounds
- [x] Issue happened in a recent (less than 7 days ago) round
- [x] [Couldn't find an existing issue about this](https://github.com/NebulaSS13/Nebula/issues)

**Comment by MistakeNot4892** [comment]
Any associated runtimes?

**Comment by Mazianni** [comment]
Not that I am aware of.

**Comment by MistakeNot4892** [comment]
Reproduced this on Neb dev in a sense, you don't transition off the main map level either.
