### ISSUE TITLE
Cyborgs & Drones cannot grab things.

### ISSUE THREAD

**Issue by chaoko99** [NebulaSS13/Nebula#2139]
#### Description of issue
Engineering borgs cannot pull canisters, thus blocking them from setting the engine.

#### Difference between expected and actual behavior
To be able to set up the engine on lowpop without making a dedicated character for the task.

#### Steps to reproduce
ctrl click a canister. Nothing happens.

#### Specific information for locating

engineering shard

#### Length of time in which bug has been known to occur

Probably since grab refactor.

#### Client version, Server revision & Game ID

Client Version: 514
Server Revision: Revision Unknown
Game ID: cek-dBO9
Current map: ISEO Endeavour

#### Issue bingo

- [x] Issue could be reproduced at least once
- [ ] Issue could be reproduced by different players
- [x] Issue could be reproduced in multiple rounds
- [x] Issue happened in a recent (less than 7 days ago) round
- [x] [Couldn't find an existing issue about this](https://github.com/NebulaSS13/Nebula/issues)

**Comment by MistakeNot4892** [comment]
![image](https://user-images.githubusercontent.com/2468979/135779768-6c250fe3-e2a6-4251-ab6a-c98ed61ef1d2.png)
Can't reproduce this on current dev.

**Comment by MistakeNot4892** [comment]
More to the point:
![image](https://user-images.githubusercontent.com/2468979/135779793-2ce7f7bb-eb9b-4e78-a05c-ed6afb795b8e.png)

**Comment by MistakeNot4892** [comment]
Please reopen if you can repro this on Neb.
