### ISSUE TITLE
loadout general category is missing

### ISSUE THREAD

**Issue by SolatK** [NebulaSS13/Nebula#2153]
#### Description of issue
You can't choose it, but it opens by default.

#### Difference between expected and actual behavior
It should be shown

#### Steps to reproduce
1) open loadout
2) there is no "general"

#### Length of time in which bug has been known to occur

Maybe a week

#### Issue bingo

- [x] Issue could be reproduced at least once
- [x] Issue could be reproduced by different players
- [x] Issue could be reproduced in multiple rounds
- [x] Issue happened in a recent (less than 7 days ago) round
- [x] [Couldn't find an existing issue about this](https://github.com/NebulaSS13/Nebula/issues)

**Comment by SolatK** [comment]
it was renamed to "Miscellaneous"

**Comment by MarinaGryphon** [comment]
actually, it *was* missing except when initially opened, I made a fix to readd it to the selection
