### ISSUE TITLE
Able to fall onto a planet when floating around in space

### ISSUE THREAD

**Issue by anconfuzedrock** [NebulaSS13/Nebula#2168]
#### Description of issue
Floating around in space having jumped off a shuttle, I landed on what seemed to be the barren planet I was looking at before at the  border. Notably I wasn't able to walk through the borders to get to the other side, maybe it wasn't a real planet? 
Hearth of hestia test.

#### Difference between expected and actual behavior
-wouldn't be able to just come onto a land map border after going past a space  map border 
-if it were possible it'd probably hurt

#### Steps to reproduce
-be above a planet? 
-jump off your ship?

#### Length of time in which bug has been known to occur

Today 

#### Client version, Server revision & Game ID

Client Version: 514
Server Revision: Revision Unknown
Game ID: cey-ddg4
Current map: ISEO Endeavour

#### Issue bingo

- [ ] Issue could be reproduced at least once
- [ ] Issue could be reproduced by different players
- [ ] Issue could be reproduced in multiple rounds
- [x] Issue happened in a recent (less than 7 days ago) round
- [x] [Couldn't find an existing issue about this](https://github.com/NebulaSS13/Nebula/issues)

**Comment by MistakeNot4892** [comment]
This sounds like the overmap transition stuff punted you onto the edge of the exoplanet, which... shouldn't happen? I think? Not sure if this is a new bug or if fixing the overmap transition runtimes has exposed a preexisting weird bug.

**Comment by anconfuzedrock** [comment]
Thaat's what I think happened. but considering the fuckiness of the borders, maybe it was just some other weird kind of z level that looked like a barren exo?

**Comment by Kaksisilma** [comment]
I was able to reproduce this in Hearth, where I opened an issue: https://github.com/HearthOfHestia/Nebula/issues/139.

I was unable to reproduce it here.

**Comment by Qumefox** [comment]
We can reproduce this on scavstation as well. Last reported incident happened on June 11, 2022

**Comment by MistakeNot4892** [comment]
Looking into this one:
- Seems to be related to the overmap travel() proc.
- Exoplanets don't have the space sector flag and are in the sealed levels list, so should not be available for travel.
- Still not sure of the actual cause.
