### ISSUE TITLE
Bioprinters and robotics fabricator don't print organs.

### ISSUE THREAD

**Issue by anconfuzedrock** [NebulaSS13/Nebula#2177]
#### Description of issue
Can't get organs from the robotics fasbricator or bioprinter. injected a blood sample into the bioprinter and it has no designs in any category. robotics fabricator has designs but not organs. happened on hestia but I booted up a localhost test of slightly outdated neb code (and now up to date nebcode that I had to delete like 1 observer var to get it to  work so it might be scuffed) and got the same thing.
#### Difference between expected and actual behavior

Organs would be printable as implied by #870

#### Steps to reproduce
1. need organs
2. use robotics fabricator or bioprinter
3. cry

#### Length of time in which bug has been known to occur

today

#### Client version, Server revision & Game ID

Client Version: 514
Server Revision: Revision Unknown
Game ID: ceE-cAPI
Current map: ISEO Endeavour

#### Issue bingo

- [x] Issue could be reproduced at least once
- [ ] Issue could be reproduced by different players
- [ ] Issue could be reproduced in multiple rounds
- [x] Issue happened in a recent (less than 7 days ago) round
- [x] [Couldn't find an existing issue about this](https://github.com/NebulaSS13/Nebula/issues)

**Comment by SolatK** [comment]
Add a drug that makes the body accept someone else's organ. Then, from the beginning of the shift, doctors will print bodies and store they organs in the refrigerator, and not print them out of necessity. And it will be possible to trade organs!

**Comment by MistakeNot4892** [comment]
That's not really related to the bug or in scope as a fix @SolatK.

**Comment by MistakeNot4892** [comment]
![image](https://user-images.githubusercontent.com/2468979/139561801-39e183d6-1f96-4977-8bcb-0cd552c1c2b9.png)
This is due to the fabricators not starting with the required data levels.
