### ISSUE TITLE
You can teleport through windows w/out grilles via low wall

### ISSUE THREAD

**Issue by anconfuzedrock** [NebulaSS13/Nebula#2211]
#### Description of issue

you can grab yourself and push yourself onto low wall to go into it, even if there's a window. Tested on hearth but I doubt it's a hearth thing.

#### Difference between expected and actual behavior
window should stop me.

#### Steps to reproduce
1. grab self
2. click low wall
3. go through it

#### Length of time in which bug has been known to occur

Today

#### Client version, Server revision & Game ID

Game ID: ceU-aL7b>
Client BYOND Version: 514.1568
Server BYOND Version: 514.1569
Current map: ISEO Endeavour
TGS version: 4.15.7
DMAPI version: 5.3.0

#### Issue bingo

- [x] Issue could be reproduced at least once
- [ ] Issue could be reproduced by different players
- [ ] Issue could be reproduced in multiple rounds
- [x] Issue happened in a recent (less than 7 days ago) round
- [x] [Couldn't find an existing issue about this](https://github.com/NebulaSS13/Nebula/issues)

**Comment by MistakeNot4892** [comment]
Could you clarify if there was a message, a do after, etc, or if it was like clicking on a turf to move something being grabbed?

Can you reproduce it with someone else grabbed?

Was the window anchored down?

**Comment by anconfuzedrock** [comment]
> Could you clarify if there was a message, a do after, etc, or if it was like clicking on a turf to move something being grabbed?
> it was a "x places x on the low wall"
> Can you reproduce it with someone else grabbed?
> I can get back to you on this one. I'd assume so
> Was the window anchored down?
yes
