### ISSUE TITLE
handle_post_spawn didnt calls

### ISSUE THREAD

**Issue by SolatK** [NebulaSS13/Nebula#2214]
#### Description of issue
handle_post_spawn didnt calls after joining the game. Thats the same issue on the bay. I do this for test, and it didnt work:
![изображение](https://user-images.githubusercontent.com/29740451/141938906-b5d1248f-2c41-4ab6-ac0b-f4fbd7e9fa83.png)
But when i manually call it, all works fine.

#### Difference between expected and actual behavior
handle_post_spawn should be called after spawn

#### Steps to reproduce
1) make some handle_post_spawn code
2) enter the game
3) nothing happiens

#### Client version, Server revision & Game ID

Client Version: 514
Server Revision: 6ea7fc168610135f4cdb5713e97ec8e1e2045f65 - dev - 2021-11-16
Game ID: ce3-bfGb

#### Issue bingo

- [x] Issue could be reproduced at least once
- [x] Issue could be reproduced by different players
- [x] Issue could be reproduced in multiple rounds
- [x] Issue happened in a recent (less than 7 days ago) round
- [x] [Couldn't find an existing issue about this](https://github.com/NebulaSS13/Nebula/issues)

**Comment by SolatK** [comment]
I think something in /mob/living/carbon/human/proc/set_species is wrong

**Comment by MistakeNot4892** [comment]
Your path is /decl/species/human not /decl/species/golem.

**Comment by MistakeNot4892** [comment]
Can't reproduce this on Neb, humans call the proc and so do monkeys. Confident this is an issue with your code.

**Comment by MistakeNot4892** [comment]
Confirmed to not be an issue.
