### ISSUE TITLE
Shuttle chairs lack overlay when there is no occupant

### ISSUE THREAD

**Issue by ghost** [NebulaSS13/Nebula#2216]
#### Description of issue

Shuttle chairs do not show the buckle/bar/whatever up in the air when there is no occupant.

![image](https://user-images.githubusercontent.com/57928673/142728155-bc39ee34-427d-453f-bb29-b0f54af9352f.png)

#### Difference between expected and actual behavior

As far as I remember they had the little bar go up in the air if unbuckled, and I know that's a thing on Bay.

#### Steps to reproduce

1. Summon shuttle chair.
2. Notice no bar?

#### Specific information for locating
https://github.com/NebulaSS13/Nebula/blob/e9fa1ab7a1b75fa554da5e14ec28e53049899867/code/game/objects/structures/stool_bed_chair_nest/chairs.dm#L226

#### Length of time in which bug has been known to occur

N/A

#### Client version, Server revision & Game ID

Client Version: 514
Server Revision: 0ddd3cfaa975cc2c502821d1c33cba25133428fa - staging - 2021-11-15
Game ID: ce2-dKhp
Current map: NSS Exodus

#### Issue bingo

- [x] Issue could be reproduced at least once
- [ ] Issue could be reproduced by different players
- [x] Issue could be reproduced in multiple rounds
- [x] Issue happened in a recent (less than 7 days ago) round
- [x] [Couldn't find an existing issue about this](https://github.com/NebulaSS13/Nebula/issues)

**Comment by MistakeNot4892** [comment]
How sure are you that this is a thing on Bay? I've never seen it and I don't think the code supports it.

**Comment by ghost** [comment]
Here is the Spirit's crew area from Hearth of Hestia, what's weird is not only that it has this bug, but it also seems to have a shuttle chair (the one next to the bed) that didn't generate its sprite or is not displaying it properly.

![image](https://user-images.githubusercontent.com/57928673/142866856-084c5620-3997-43f2-b2c4-10fb8b4d79f1.png)

Here is the same area on Bay's Charon.

![image](https://user-images.githubusercontent.com/57928673/142867016-348c2b2e-f508-43d8-af2d-d2eab6a6baba.png)
