### ISSUE TITLE
t-ray scanner do not show wires 

### ISSUE THREAD

**Issue by SolatK** [NebulaSS13/Nebula#2217]
#### Description of issue
![изображение](https://user-images.githubusercontent.com/29740451/142734327-119a5f8e-eba0-40de-94f9-4b0b738cda71.png)
![изображение](https://user-images.githubusercontent.com/29740451/142734420-e8eb73db-01e9-4987-b720-36fb0cfbba3e.png)

#### Difference between expected and actual behavior
It should 

#### Steps to reproduce
1) lay the cable under the tiles
2) it is not visible by the scanner

#### Client version, Server revision & Game ID

Client Version: 514
Server Revision: e9fa1ab7a1b75fa554da5e14ec28e53049899867 - dev - 2021-11-20
Game ID: ce7-czHr
Current map: NSS Exodus

#### Issue bingo

- [x] Issue could be reproduced at least once
- [x] Issue could be reproduced by different players
- [x] Issue could be reproduced in multiple rounds
- [x] Issue happened in a recent (less than 7 days ago) round
- [x] [Couldn't find an existing issue about this](https://github.com/NebulaSS13/Nebula/issues)

**Comment by MistakeNot4892** [comment]
Cables have a `level` value of 2 so t-ray scanners skip over them.
