### ISSUE TITLE
Bolted airlock stacks up light sources 

### ISSUE THREAD

**Issue by SolatK** [NebulaSS13/Nebula#2219]
#### Description of issue
![изображение](https://user-images.githubusercontent.com/29740451/142735989-f0c00884-6948-4a57-bd36-050f6eed25aa.png)
![изображение](https://user-images.githubusercontent.com/29740451/142736102-a61a2f6d-9121-4a63-b5e3-d2dc25532f8c.png)

#### Steps to reproduce
1) Lock airlock
2) Click on it many times
3) affecting_lights on it turf is stacking

#### Client version, Server revision & Game ID

Client Version: 514
Server Revision: 69f1f1ff5f7f4e6fd0f485cda28e7c9c8bb2aab9 - dev - 2021-11-20
Game ID: ce7-cLSB
Current map: NSS Exodus

#### Issue bingo

- [x] Issue could be reproduced at least once
- [ ] Issue could be reproduced by different players
- [x] Issue could be reproduced in multiple rounds
- [x] Issue happened in a recent (less than 7 days ago) round
- [x] [Couldn't find an existing issue about this](https://github.com/NebulaSS13/Nebula/issues)

**Comment by MistakeNot4892** [comment]
Can't reproduce this on current dev.
