### ISSUE TITLE
Autolathes print unusable structure-tape instead of tape recorder item tape.

### ISSUE THREAD

**Issue by anconfuzedrock** [NebulaSS13/Nebula#2226]
#### Description of issue
There's an item in autolathes called "tape", it costs nothing to queue up and print, and it prints a placed piece of security tape on the tile, which you can't pick up (only break).

#### Difference between expected and actual behavior
I think this was supposed to print tapes for the universal recorder, not pieces of unusable tape

#### Steps to reproduce
1. print tape

#### Length of time in which bug has been known to occur

today

#### Client version, Server revision & Game ID

Client Version: 514
Server Revision: aa9b40b1d4a378e461826677a074744da8dfe5cc - dev - 2021-11-27
Game ID: cfd-apmZ

#### Issue bingo

- [x] Issue could be reproduced at least once
- [ ] Issue could be reproduced by different players
- [x] Issue could be reproduced in multiple rounds
- [x] Issue happened in a recent (less than 7 days ago) round
- [x] [Couldn't find an existing issue about this](https://github.com/NebulaSS13/Nebula/issues)

**Comment by Mazianni** [comment]
oh this bug again
