### ISSUE TITLE
/obj/level_data doesn't have map icon

### ISSUE THREAD

**Issue by quardbreak** [NebulaSS13/Nebula#2243]
#### Description of issue

Title.

#### Difference between expected and actual behavior

Map viewers like StrongDMM, FastDMM2 and render tools like MapDiff should render it.

#### Steps to reproduce

1. Open tradeship-0.dmm in FastDMM2.
2. Hide-and-seek begin.

#### Specific information for locating

/obj/level_data doesn't have set icon for mapping.

#### Length of time in which bug has been known to occur

Perhaps after https://github.com/NebulaSS13/Nebula/commit/1451790f2f5b95d2397f0e48266ef0e665ffca10.

#### Issue bingo

- [X] Issue could be reproduced at least once
- [ ] Issue could be reproduced by different players
- [ ] Issue could be reproduced in multiple rounds
- [X] Issue happened in a recent (less than 7 days ago) round
- [x] [Couldn't find an existing issue about this](https://github.com/NebulaSS13/Nebula/issues)

**Comment by MistakeNot4892** [comment]
Fixed by #2242.
