### ISSUE TITLE
Some emotes, which theoretically, can be hearable and visible both, shown only if you can hear or see

### ISSUE THREAD

**Issue by quardbreak** [NebulaSS13/Nebula#2254]
#### Description of issue

Don't want to write a big explanation so here's example:

> A deaf guy see a person. A person screams, but deaf guy don't know about it, because all audible emote messages can be seen only by people who aren't deaf.

Not sure if same with blind people.

#### Difference between expected and actual behavior
Some emotes like screaming both can be understood in both ways other than the simultaneous loss of hearing and vision.

#### Steps to reproduce

1. Be deaf.
2. `Say "*scream`

#### Specific information for locating

Emote code.

#### Length of time in which bug has been known to occur

I think a years.

#### Client version, Server revision & Game ID

514.

#### Issue bingo

- [X] Issue could be reproduced at least once
- [ ] Issue could be reproduced by different players
- [X] Issue could be reproduced in multiple rounds
- [X] Issue happened in a recent (less than 7 days ago) round
- [X] [Couldn't find an existing issue about this](https://github.com/NebulaSS13/Nebula/issues)

**Comment by comma** [comment]
This is more of feature request, there's just no handling for deafness like that. Blindness is handled by visible message having argument for blind alt text.

**Comment by MistakeNot4892** [comment]
Closing this as a feature request, emote system doesn't support this currently.
