### ISSUE TITLE
Ability buttons are gone

### ISSUE THREAD

**Issue by XElectricX** [NebulaSS13/Nebula#2255]
#### Description of issue
The ability buttons on your HUD do not appear anywhere. Only the button to show/hide them is visible. Item-specific buttons seem to work though. Bay's version works.

#### Difference between expected and actual behavior
Buttons for things like spells do not appear on your HUD when given.

#### Steps to reproduce
Load game.
Spawn a contract, spellbook, or use give spell command.
Try to find where the corresponding button to use it is.

#### Specific information for locating
N/A

#### Length of time in which bug has been known to occur
Found out the day before while testing spells.

#### Client version, Server revision & Game ID
Client Version: 514
Server Revision: 6145049cb4eb27878ecdf216aacb9080b2cea1f8 - dev - 2021-12-14
Game ID: cfu-cSf3

#### Issue bingo

- [X] Issue could be reproduced at least once
- [x] Issue could be reproduced by different players
- [X] Issue could be reproduced in multiple rounds
- [X] Issue happened in a recent (less than 7 days ago) round
- [X] [Couldn't find an existing issue about this](https://github.com/NebulaSS13/Nebula/issues)

**Comment by quardbreak** [comment]
Caused by https://github.com/NebulaSS13/Nebula/commit/98a06f07a3b602a8a8566c4ade177267102dee6b.

**Comment by MistakeNot4892** [comment]
Didn't test this with spells at the time, rip.
