### ISSUE TITLE
Bad URL in /nano/templates/TemplatesGuide.txt

### ISSUE THREAD

**Issue by PsyCommando** [NebulaSS13/Nebula#2274]
#### Description of issue
The URL in /nano/templates/TemplatesGuide.txt points to the baystation wiki that disappeared. And I don't know what we should do about it? Just stumbled on that when looking for doc.

**Comment by afterthought2** [comment]
Should probably just point [here](https://olado.github.io/doT/); we don't maintain the Bay docs and this is the real dependency.

**Comment by PsyCommando** [comment]
Gonna be fixed in my pr #2289
