### ISSUE TITLE
Items in the grid inventory UI are misaligned with their cell

### ISSUE THREAD

**Issue by PsyCommando** [NebulaSS13/Nebula#2302]
#### Description of issue
Items in the grid inventory UI are misaligned with their cell.
![2022-03-22 19_47_50-Window](https://user-images.githubusercontent.com/8772299/159595048-e832e1f9-af86-49d0-ae52-5e51f0d3829d.png)

#### Difference between expected and actual behavior
Items in the inventory are normally within their cells.

#### Steps to reproduce
Open any grid inventory.

#### Specific information for locating

Possibly a side effect of #2293.

#### Client version, Server revision & Game ID

1c37bd70ce760caae31697ed400b8011a30c9ebc - dev - 2022-03-22

#### Issue bingo

- [X] Issue could be reproduced at least once
- [x] Issue could be reproduced by different players
- [X] Issue could be reproduced in multiple rounds
- [X] Issue happened in a recent (less than 7 days ago) round
- [X] [Couldn't find an existing issue about this](https://github.com/NebulaSS13/Nebula/issues)

**Comment by MarinaGryphon** [comment]
Can reproduce on a fork.

**Comment by MistakeNot4892** [comment]
Fixed by #2332
