### ISSUE TITLE
Weapons made with some materials don't use the right damage type

### ISSUE THREAD

**Issue by PsyCommando** [NebulaSS13/Nebula#2304]
#### Description of issue
Depending on the materials, some swords for instance, cause blunt damage instead of edge damage. Its because of some of the materials change that disable the sharp flag on swords based on hardness of the material its made of. The same issue also applies to the energy swords..

#### Steps to reproduce
Try to cut a human's head off with a katana or esword. (Both are considered to be made of steel and get their flags modified)
Notice it gibs the head like a blunt weapon would do.
Try the vibrokatana instead.
Notice how its made of titanium and properly chop the head off?

#### Length of time in which bug has been known to occur

At least a month.

#### Issue bingo

- [X] Issue could be reproduced at least once
- [X] Issue could be reproduced by different players
- [X] Issue could be reproduced in multiple rounds
- [X] Issue happened in a recent (less than 7 days ago) round
- [X] [Couldn't find an existing issue about this](https://github.com/NebulaSS13/Nebula/issues)

**Comment by MistakeNot4892** [comment]
For reference this is specifically handled by `/obj/item/sword/update_force()` and the basic material system has handling for edge/blunt damage as-is - might be worth merging the functions.

**Comment by comma** [comment]
It shouldn't affect e-swords because they're not under `/sword/` path, they're their own item `/obj/item/energy_blade/sword`
Katanas are blunt because steel is not hard enough, going to bump that so it's above cast iron

**Comment by out-of-phaze** [comment]
the esword has sharp and edge both set to false, which implies this is intended? it's a blunt weapon that's just very hot. i think #2953 fixed the actual issues with katanas though, so i'll close this. feel free to open a new one if it's still an issue
