### ISSUE TITLE
Limbs thrown when dismembering a mob with a melee weapon can hit you and throw you away

### ISSUE THREAD

**Issue by PsyCommando** [NebulaSS13/Nebula#2306]
#### Description of issue
When dismembering a mob, if you stand in the path of the limb (~~stand on top for example~~ standing one tile next) you get kicked around with a lot of force. You get knocked down and if you hit a wall, you can actually cause some brain damage and "YOU DON'T KNOW WHICH WAY IS FORWARD" to happen.

#### Difference between expected and actual behavior
Chopping off a limb and getting hit with it definitely shouldn't send you flying with that amount of force.

#### Steps to reproduce
* Take a weapon that does edge damage
* Spawn a human, preferably in a tight corridor
* Stand on the tile next to the mob as its laying down
* Attack the limb zone on the human until the limb flies off and it hits you
* Notice how it hits you, and sends you flying

#### Issue bingo

- [X] Issue could be reproduced at least once
- [ ] Issue could be reproduced by different players
- [X] Issue could be reproduced in multiple rounds
- [X] Issue happened in a recent (less than 7 days ago) round
- [X] [Couldn't find an existing issue about this](https://github.com/NebulaSS13/Nebula/issues)

**Comment by MistakeNot4892** [comment]
Could possibly resolve this by adding a force or direction argument to `/obj/item/organ/external/proc/dismember`.
