### ISSUE TITLE
Chemistry on Bearcat has no phoron

### ISSUE THREAD

**Issue by T-rexsuper1** [NebulaSS13/Nebula#2310]
#### Description of issue

Chemistry on Bearcat has no phoron

#### Difference between expected and actual behavior

It's supposed to have 2-3 sheets

#### Steps to reproduce

Walk into chemistry on Bearcat

#### Specific information for locating

Pretty much self explanatory 

#### Length of time in which bug has been known to occur

Roundstart

#### Client version, Server revision & Game ID

Client Version: 514
Server Revision: Revision Unknown
Game ID: chz-cBHy
Current map: Enamelled Tradeship One

#### Issue bingo

- [x] Issue could be reproduced at least once
- [x] Issue could be reproduced by different players
- [x] Issue could be reproduced in multiple rounds
- [x] Issue happened in a recent (less than 7 days ago) round
- [x] [Couldn't find an existing issue about this](https://github.com/NebulaSS13/Nebula/issues)

**Comment by quardbreak** [comment]
Not a bug, because phoron was removed from the codebase intentionally.

**Comment by MistakeNot4892** [comment]
Means it's missing uranium and enzyme instead afaicr.

**Comment by T-rexsuper1** [comment]
> Means it's missing uranium and enzyme instead afaicr.

so chemicals that use phoron as a component now use uranium?

**Comment by quardbreak** [comment]
> so chemicals that use phoron as a component now use uranium?

Anything else but phoron. You can check all reactions and which one component required for it in Codex.

**Comment by MistakeNot4892** [comment]
It might be a good idea to add some uranium/enzyme to the tradeship chemistry bay, but as it stands Tradeship is _meant_ be undersupplied, so marking this down as deliberate.
