### ISSUE TITLE
Cloth, synthetic leather and normal leather crafting recipes issues.

### ISSUE THREAD

**Issue by T-rexsuper1** [NebulaSS13/Nebula#2318]
#### Description of issue

Cloth and other clothlike items (synthetic leather and normal leather) have absurd recipes and are missing the stuff that is supposed to be there (list bellow)

#### Difference between expected and actual behavior

Expected items that are supposed to be craftable:
Cloth - gauze, white jumpsuit, white cap, evening gloves, white shoes, white drop pouches, backpack, duffelbag, sterile mask, white hoodie, white webbing, medical belt. 

Leather - work gloves (brown), waist holster, armpit holster, hip holster, knife sheath (leather, brown), toolbelt, cowboy hat, brown leather jacket, brown drop pouches, satchel. 

Synthetic leather - work gloves (black), thigh holster, knife sheath (synthetic, black), security holster belt, security belt (no holster), forestcis belt, jackboots, rucksack, drop pouches (black), black synthetic leather jacket, utility uniform, cowboy hat (black). 

Stuff that is there but is not supposed to be there: 
ashtray, ring, clipboard, cross, baseball bat, urn, spoon, antique coins. 

#### Steps to reproduce

Try to craft stuff with leather, synthetic leather or cloth. 

#### Specific information for locating

Any cloth, synthetic leather or leather. 

#### Length of time in which bug has been known to occur

I guess the entire time modular crafting was there. 

#### Client version, Server revision & Game ID

Client Version: 514
Server Revision: Revision Unknown
Game ID: chI-cZbh
Current map: Tradeship Ocelot Alpha

#### Issue bingo

- [x] Issue could be reproduced at least once
- [x] Issue could be reproduced by different players
- [x] Issue could be reproduced in multiple rounds
- [x] Issue happened in a recent (less than 7 days ago) round
- [x] [Couldn't find an existing issue about this](https://github.com/NebulaSS13/Nebula/issues)

**Comment by MistakeNot4892** [comment]
The recipes are nonsense and need better conditions/hardness checks, but with regards to the expected crafting lists - almost all of have never been craftable by hand as far as I know. You need to use the textiles fabricator to print anything complex.

**Comment by MistakeNot4892** [comment]
Closing this for the time being as leather and cloth have no nonsense recipes now - the other stuff can be added to recipes or the textiles fab in a PR if desired.
