### ISSUE TITLE
Wheelchairs allow passing through machinery, unhindered.

### ISSUE THREAD

**Issue by SodiumShine** [NebulaSS13/Nebula#235]
![power](https://cdn.discordapp.com/attachments/663522358362898442/694318415682207786/wheelchair.gif)

Doors seem to work fine though

**Comment by deathride58** [comment]
All-terrain wheelchair

**Comment by SodiumShine** [comment]
![wheelchair2](https://user-images.githubusercontent.com/4461697/77970947-35226c80-7339-11ea-8734-70d1b41b51d0.gif)

Also works on mobs regardless of their intent. However, those mobs can't pass through the wheelchair and it's occupant by their own will.
