### ISSUE TITLE
Moving yourself with grab.

### ISSUE THREAD

**Issue by Gaxeer** [NebulaSS13/Nebula#2412]
#### Description of issue

It's possible to move yourself by grabbing and then clicking to neighboring turf.

#### Difference between expected and actual behavior

It shouldn't be possible to move yourself with grab.

#### Steps to reproduce

1) Grab yourself
2) Click on neighboring turf with left mouse button

#### Length of time in which bug has been known to occur

4 month at least

#### Client version, Server revision & Game ID

Client Version: 514
Server Revision: 90b889aef804d7847341155a73bec8eac346f60a - 7341155a73bec8eac346f60a - 
Game ID: ch0-c5GC

#### Issue bingo

- [x] Issue could be reproduced at least once
- [x] Issue could be reproduced by different players
- [x] Issue could be reproduced in multiple rounds
- [x] Issue happened in a recent (less than 7 days ago) round
- [x] [Couldn't find an existing issue about this](https://github.com/NebulaSS13/Nebula/issues)

**Comment by noelle-lavenza** [comment]
This isn't a bug, I don't think. I tend to use it for crawling.

**Comment by Gaxeer** [comment]
> This isn't a bug, I don't think. I tend to use it for crawling.

But... Crawling is handled by just moving while lying:D
