### ISSUE TITLE
Bug with directional light

### ISSUE THREAD

**Issue by Gaxeer** [NebulaSS13/Nebula#2422]
#### Description of issue

Light moves with speed different from the speed of light source

#### Difference between expected and actual behavior

Light should have the same speed as the light source, I suppose

#### Steps to reproduce

1) Take flashlight or other light source with directional light
2) Turn on
3) Move

#### Length of time in which bug has been known to occur

Couple of month

#### Client version, Server revision & Game ID

Client Version: 514
Server Revision: cd30584062f7885b653f23b691b613c4ee5fb082 - dev - 2022-05-21
Game ID: ch2-cLZE

#### Issue bingo

- [x] Issue could be reproduced at least once
- [x] Issue could be reproduced by different players
- [x] Issue could be reproduced in multiple rounds
- [ ] Issue happened in a recent (less than 7 days ago) round
- [x] [Couldn't find an existing issue about this](https://github.com/NebulaSS13/Nebula/issues)

**Comment by afterthought2** [comment]
I don't think this is fixable, but can check with @Lohikar. Mobs move instantly but have an animation that gives a visual delay. Lights cannot be animated like that.

**Comment by MistakeNot4892** [comment]
Yeah fixing this would require a total rewrite of the lighting engine to use overlays and objects a la Europalights, this isn't a bug or something we can feasibly fix.
