### ISSUE TITLE
Persistence didnt track noticeboards correctly

### ISSUE THREAD

**Issue by SolatK** [NebulaSS13/Nebula#2438]
#### Description of issue
Persistence didnt track noticeboards correctly
it resets direction after 1 restart
![изображение](https://user-images.githubusercontent.com/29740451/170619252-2b4417af-7869-4dc3-8869-a71422b68c7b.png)
and noticeboard dissapears after 2 restarts
![изображение](https://user-images.githubusercontent.com/29740451/170619293-9e8c8ed1-302d-4476-b6bd-fb56c5d7f96e.png)

sometimes it vanished afred 1 restart with all papers, sometimes leave "persistent" paper that exists until it is destroyed
#### Difference between expected and actual behavior
I think it should track it until someone or something destroy it

#### Steps to reproduce
1) craft noticeboard
2) pin some papers
3) dont touch noticeboard and restart server 2 times
#### Client version, Server revision & Game ID

Client Version: 514
Server Revision: c2377f69454640262b020b26407fc27de8786968 - dev - 2022-05-27
Game ID: ch8-aBbe

#### Issue bingo

- [x] Issue could be reproduced at least once
- [x] Issue could be reproduced by different players
- [x] Issue could be reproduced in multiple rounds
- [x] Issue happened in a recent (less than 7 days ago) round
- [x] [Couldn't find an existing issue about this](https://github.com/NebulaSS13/Nebula/issues)

**Comment by MistakeNot4892** [comment]
The noticeboard itself isn't persistent, the papers on it are. If a noticeboard has no persistent papers, it will not be kept for the next round. Debugging now so will update if I can repro this.
