### ISSUE TITLE
APC charge mode

### ISSUE THREAD

**Issue by SolatK** [NebulaSS13/Nebula#2440]
#### Description of issue
Disable APC charge prevents it from charge it cell, but it used energy from wire, not from battery. 
![изображение](https://user-images.githubusercontent.com/29740451/170622718-60a8043a-123b-4ef6-ac91-c029cfc00e05.png)

#### Difference between expected and actual behavior
It should use cell stored energy when charge mode is off

#### Steps to reproduce
1) set apc charge mode to off
2) it dont use battery power

#### Client version, Server revision & Game ID

Client Version: 514
Server Revision: c2377f69454640262b020b26407fc27de8786968 - dev - 2022-05-27
Game ID: ch8-aBbe

#### Issue bingo

- [x] Issue could be reproduced at least once
- [x] Issue could be reproduced by different players
- [x] Issue could be reproduced in multiple rounds
- [x] Issue happened in a recent (less than 7 days ago) round
- [x] [Couldn't find an existing issue about this](https://github.com/NebulaSS13/Nebula/issues)

**Comment by afterthought2** [comment]
I think that's just not a correct interpretation of how the interaction should work; charge off disables the battery from charging, but not the APC drawing power from the net. I guess it could be changed, though I don't relish the prospect of doing it.

**Comment by SolatK** [comment]
> I think that's just not a correct interpretation of how the interaction should work; charge off disables the battery from charging, but not the APC drawing power from the net. I guess it could be changed, though I don't relish the prospect of doing it.

I'm not sure. On the one hand, everything is logically correct, on the other hand, on any other build, this switch just disconnects the APC from the network.

**Comment by MistakeNot4892** [comment]
I would argue the purpose of the charge mode option is to stop APCs draining the powernet/SMES to charge themselves, which is still a valid use of it currently. Wouldn't call this a bug necessarily.

**Comment by afterthought2** [comment]
I feel that since the APC is so extremely complicated as far as the possible interactions go, and there are ways of obtaining both of these effects with basic, completely universal _hardware_ interactions (cut terminal for the "legacy" one, remove battery for the "current" one; alternatively, remove the corresponding stock part), I'm not too concerned with this. If anything I'd consider just removing this software toggle, or renaming it, or explaining it better somehow.

**Comment by MistakeNot4892** [comment]
Calling this fixed for now unless someone wants to articulate the issue and a better fix.
