### ISSUE TITLE
multitool problem

### ISSUE THREAD

**Issue by SolatK** [NebulaSS13/Nebula#2443]
#### Description of issue
There is no way to choose what side of item you want to use
![изображение](https://user-images.githubusercontent.com/29740451/170625689-c21d5158-a04e-4d1c-99d1-e2ca8f17e010.png)
and sometimes you cants use the weapon to attack if it can be used as tool
![изображение](https://user-images.githubusercontent.com/29740451/170625765-4a454767-b7eb-42fd-b3e6-40daa1da5a25.png)

#### Difference between expected and actual behavior
There is should be way to choose what aspect of item you want to use, or just use it like weapon

#### Steps to reproduce
1) take combat knife
2) try to attack APC

#### Issue bingo

- [x] Issue could be reproduced at least once
- [x] Issue could be reproduced by different players
- [x] Issue could be reproduced in multiple rounds
- [x] Issue happened in a recent (less than 7 days ago) round
- [x] [Couldn't find an existing issue about this](https://github.com/NebulaSS13/Nebula/issues)

**Comment by MistakeNot4892** [comment]
Workaround in #2447
