### ISSUE TITLE
you cant move body on straight line

### ISSUE THREAD

**Issue by SolatK** [NebulaSS13/Nebula#2444]
#### Description of issue
inject someone with drugs and you cant move it on straight line. Im not shure what effect cause this, confusion or dizzines, but it affect forced move.

#### Difference between expected and actual behavior
No matter how many drugs there are in the body, you should be able to drag it in a straight line

#### Steps to reproduce
1) Inject drugs in someone body
2) Try to drag it

#### Client version, Server revision & Game ID

Client Version: 514
Server Revision: c2377f69454640262b020b26407fc27de8786968 - dev - 2022-05-27
Game ID: ch8-aI2Y

#### Issue bingo

- [x] Issue could be reproduced at least once
- [x] Issue could be reproduced by different players
- [x] Issue could be reproduced in multiple rounds
- [x] Issue happened in a recent (less than 7 days ago) round
- [x] [Couldn't find an existing issue about this](https://github.com/NebulaSS13/Nebula/issues)

**Comment by Gaxeer** [comment]
Fixed with https://github.com/NebulaSS13/Nebula/pull/2424
