### ISSUE TITLE
network access lock and APC

### ISSUE THREAD

**Issue by SolatK** [NebulaSS13/Nebula#2452]
#### Description of issue
![изображение](https://user-images.githubusercontent.com/29740451/170813822-2dd923e9-655d-460e-98e9-eeb5a68103f7.png)
unlocked APC cover still needs access to open it

#### Difference between expected and actual behavior
it shouldn require access if it unlocked 

#### Steps to reproduce
1) install network access lock in APC
2) unlock it cover
3) try to open it without id card
#### Client version, Server revision & Game ID

Client Version: 514
Server Revision: 0fe1ea0034ebc5b79e08699ca99e83bacb5600dc - dev - 2022-05-27
Game ID: ch9-aSJf

#### Issue bingo

- [x] Issue could be reproduced at least once
- [x] Issue could be reproduced by different players
- [x] Issue could be reproduced in multiple rounds
- [x] Issue happened in a recent (less than 7 days ago) round
- [x] [Couldn't find an existing issue about this](https://github.com/NebulaSS13/Nebula/issues)

**Comment by afterthought2** [comment]
We should take a close look at this whole interaction tree. APCs have very complicated access management with separate "hardware" and "software" access and various ways to bypass each, which are not really compatible with the component stuff.

**Comment by SolatK** [comment]
> We should take a close look at this whole interaction tree. APCs have very complicated access management with separate "hardware" and "software" access and various ways to bypass each, which are not really compatible with the component stuff.

[11:00:56] Runtime in code/datums/progress_bar.dm, line 42: datum/progress_bar: Invalid param given - param_target
usr: Shara (/mob/living/carbon/human) ([0x3000026]) (the floor) (32,24,2 - Tradeship Ocelot Alpha) (/turf/simulated/floor/tiled/techfloor) (solark)
usr.loc: The floor (/turf/simulated/floor/tiled/techfloor) ([0x100ae57]) (32,24,2 - Tradeship Ocelot Alpha) (/area/ship/trade/maintenance/techstorage)


[11:00:56] Runtime in progress_bar.dm, line 93: Cannot read null.progress_bars
proc name: shift down all (/datum/progress_bar/proc/shift_down_all)
usr: Shara (/mob/living/carbon/human) ([0x3000026]) (the floor) (32,24,2 - Tradeship Ocelot Alpha) (/turf/simulated/floor/tiled/techfloor) (solark)
usr.loc: The floor (/turf/simulated/floor/tiled/techfloor) ([0x100ae57]) (32,24,2 - Tradeship Ocelot Alpha) (/area/ship/trade/maintenance/techstorage)
src: default (/datum/progress_bar/default)
call stack:
default (/datum/progress_bar/default): shift down all()
default (/datum/progress_bar/default): stop()
do after(Shara (/mob/living/carbon/human), 6.5, null, 1, 1, 61, 0, 0, /datum/progress_bar/default (/datum/progress_bar/default))
Shara (/mob/living/carbon/human): do skilled(5, /decl/hierarchy/skill/engineer... (/decl/hierarchy/skill/engineering/construction), null, 0.3)
the steel sheets (/obj/item/stack/material/sheet/mapped/steel/fifty): produce recipe(/datum/stack_recipe/rod (/datum/stack_recipe/rod), 5, Shara (/mob/living/carbon/human))
the steel sheets (/obj/item/stack/material/sheet/mapped/steel/fifty): Topic("src=\[0x20099ab];make=23;multi...", /list (/list))
SolarK (/client): Topic("src=\[0x20099ab];make=23;multi...", /list (/list), the steel sheets (/obj/item/stack/material/sheet/mapped/steel/fifty))



[11:00:56] Runtime in progress_bar.dm, line 81: invalid object type 0:0
proc name: stop (/datum/progress_bar/proc/stop)
usr: Shara (/mob/living/carbon/human) ([0x3000026]) (the floor) (32,24,2 - Tradeship Ocelot Alpha) (/turf/simulated/floor/tiled/techfloor) (solark)
usr.loc: The floor (/turf/simulated/floor/tiled/techfloor) ([0x100ae57]) (32,24,2 - Tradeship Ocelot Alpha) (/area/ship/trade/maintenance/techstorage)
src: default (/datum/progress_bar/default)
call stack:
default (/datum/progress_bar/default): stop()
do after(Shara (/mob/living/carbon/human), 6.5, null, 1, 1, 61, 0, 0, /datum/progress_bar/default (/datum/progress_bar/default))
Shara (/mob/living/carbon/human): do skilled(5, /decl/hierarchy/skill/engineer... (/decl/hierarchy/skill/engineering/construction), null, 0.3)
the steel sheets (/obj/item/stack/material/sheet/mapped/steel/fifty): produce recipe(/datum/stack_recipe/rod (/datum/stack_recipe/rod), 5, Shara (/mob/living/carbon/human))
the steel sheets (/obj/item/stack/material/sheet/mapped/steel/fifty): Topic("src=\[0x20099ab];make=23;multi...", /list (/list))
SolarK (/client): Topic("src=\[0x20099ab];make=23;multi...", /list (/list), the steel sheets (/obj/item/stack/material/sheet/mapped/steel/fifty))

**Comment by MistakeNot4892** [comment]
Found the same issue from the opposite direction, cover lock is completely ignored in favour of your equipped access.
