### ISSUE TITLE
Spawn Atom window too narrow

### ISSUE THREAD

**Issue by Qumefox** [NebulaSS13/Nebula#2462]
#### Description of issue
The selection window when spawning atoms is too narrow and can't be resized. This prevents actually being able to see which atom it is that you're actually trying to spawn when it's path length is longer than the window width.

#### Difference between expected and actual behavior

Should be self explanatory. The default width of the selection window just needs to be wider.

#### Steps to reproduce

Try to spawn an atom that has a path longer than the width of the selection window. For example, portable air pump

#### Length of time in which bug has been known to occur

At least since 5-27-2022

#### Client version, Server revision & Game ID

Client Version: 514
Server Revision: ea3cdbe93b0a70bb9e3d1d6f1bf108c9283c6717 - dev - 2022-05-27
Game ID: cia-avgO
Current map: Tradeship Ivenmoth

#### Issue bingo

- [x] Issue could be reproduced at least once
- [ ] Issue could be reproduced by different players
- [x] Issue could be reproduced in multiple rounds
- [x] Issue happened in a recent (less than 7 days ago) round
- [x] [Couldn't find an existing issue about this](https://github.com/NebulaSS13/Nebula/issues)

**Comment by MistakeNot4892** [comment]
Game Panel has a spawn button that gives a more flexible browser based approach as discussed.
