### ISSUE TITLE
Cryopods draw extreme amounts of power after they're ghosted/logged out in.

### ISSUE THREAD

**Issue by Qumefox** [NebulaSS13/Nebula#2463]
#### Description of issue

When someone ghosts/logs out in a cryopod, it causes the power draw for that pod to increase by 50KW per ghost/logout.

#### Difference between expected and actual behavior

Cryopods should not start drawing insane amounts of power when used.

#### Steps to reproduce

View power monitoring on the terminal in engineering. Ghost or logout in a cryopod, then recheck the power draw for that APC. It will increase by 50KW each time you ghost/logout in a pod connected to that APC

#### Length of time in which bug has been known to occur

First noticed 5-20-2022 but has probably been going on for longer.

#### Client version, Server revision & Game ID

Client Version: 514
Server Revision: ea3cdbe93b0a70bb9e3d1d6f1bf108c9283c6717 - dev - 2022-05-27
Game ID: cia-avgO
Current map: Tradeship Ivenmoth

#### Issue bingo

- [x] Issue could be reproduced at least once
- [x] Issue could be reproduced by different players
- [x] Issue could be reproduced in multiple rounds
- [x] Issue happened in a recent (less than 7 days ago) round
- [x] [Couldn't find an existing issue about this](https://github.com/NebulaSS13/Nebula/issues)

**Comment by noelle-lavenza** [comment]
The only thing I can think of is that items like PDAs somehow get stuck in the cryopod and start to consume power on behalf of the cryopod??
