### ISSUE TITLE
The character ÿ has begun appearing before compartment names in event notices.

### ISSUE THREAD

**Issue by Qumefox** [NebulaSS13/Nebula#2464]
#### Description of issue
Extremely minor but I figured I'd report it anyway. A strange character has started sneaking in before compartment names in notices. For example:

Bioscans indicate that lizards have been breeding in the ÿChemistry Bay. Further infestation is likely if left unchecked.

Pressure readings indicate an imminent explosion in the ÿMaintenance Corridors disposal systems. Piping sections may be damaged

#### Difference between expected and actual behavior

The character ÿ should not be preceding compartment names.

#### Steps to reproduce

None. Just have to wait for an event to happen.

#### Length of time in which bug has been known to occur

I just noticed this today, 5-28-2022 when testing other issues.

#### Client version, Server revision & Game ID

Client Version: 514
Server Revision: ea3cdbe93b0a70bb9e3d1d6f1bf108c9283c6717 - dev - 2022-05-27
Game ID: cia-avgO
Current map: Tradeship Ivenmoth

#### Issue bingo

- [x] Issue could be reproduced at least once
- [ ] Issue could be reproduced by different players
- [ ] Issue could be reproduced in multiple rounds
- [x] Issue happened in a recent (less than 7 days ago) round
- [x] [Couldn't find an existing issue about this](https://github.com/NebulaSS13/Nebula/issues)

**Comment by MistakeNot4892** [comment]
This is due to the way BYOND renders `\improper`.
