### ISSUE TITLE
text in bitflag field 

### ISSUE THREAD

**Issue by SolatK** [NebulaSS13/Nebula#2468]
#### Description of issue
![изображение](https://user-images.githubusercontent.com/29740451/170916852-e0911d3a-770c-4266-a152-8879d9bb2aae.png)
after refitting space suit get bodytype name in bodytype_equip_flags field instead of its bitflag

and half of associated code using bodytype_flag while the outher half using name of bodytype. Thats create runrimes if you equip refitted space suit and works incorrectly.

#### Difference between expected and actual behavior
It all should use only one type

#### Steps to reproduce
1) refit spacesuit to any species and equip it
2) get runtime in _clothing.dm, line 135: type mismatch

#### Issue bingo

- [x] Issue could be reproduced at least once
- [x] Issue could be reproduced by different players
- [x] Issue could be reproduced in multiple rounds
- [x] Issue happened in a recent (less than 7 days ago) round
- [x] [Couldn't find an existing issue about this](https://github.com/NebulaSS13/Nebula/issues)

**Comment by MistakeNot4892** [comment]
#2470
