### ISSUE TITLE
Timer runtimes

### ISSUE THREAD

**Issue by Qumefox** [NebulaSS13/Nebula#2517]
#### Description of issue

Frequently timer runtimes during rounds. 
The runtime is always the same other than the timer number.

#### Difference between expected and actual behavior

Timers shouldn't be runtiming.

#### Steps to reproduce

Watch the console output during rounds

#### Specific information for locating
````
<!-- e.g. an object name, paste specific message outputs... -->
[11:14:47] Runtime in timer.dm,494: Cannot read null.object
  proc name: bucketJoin (/datum/timedevent/proc/bucketJoin)
  src: Timer: 123 (\[0x21006695]), TT... (/datum/timedevent)
  call stack:
  Timer: 123 (\[0x21006695]), TT... (/datum/timedevent): bucketJoin()
  Timer (/datum/controller/subsystem/timer): fire(0)
  Timer (/datum/controller/subsystem/timer): ignite(0)
  Master (/datum/controller/master): RunQueue()
  Master (/datum/controller/master): Loop()
  Master (/datum/controller/master): StartProcessing(0)
````
#### Length of time in which bug has been known to occur

At least since i've started hosting scavstation, so at minimum ~6 weeks, but likely far longer

#### Client version, Server revision & Game ID

Client Version: 514
Server Revision: 013e91177a69345c0a692db0b6f73915933075ce - dev - 2022-06-09
Game ID: cip-aakB
Current map: Tradeship Ivenmoth

#### Issue bingo

- [x] Issue could be reproduced at least once
- [ ] Issue could be reproduced by different players
- [x] Issue could be reproduced in multiple rounds
- [x] Issue happened in a recent (less than 7 days ago) round
- [x] [Couldn't find an existing issue about this](https://github.com/NebulaSS13/Nebula/issues)

**Comment by MistakeNot4892** [comment]
Let's close this for now and reopen if the runtime happens again on testing.
