### ISSUE TITLE
Mouse interactions

### ISSUE THREAD

**Issue by Qumefox** [NebulaSS13/Nebula#2518]
#### Description of issue

Mice can interact with far more items in game than they should be able to.

#### Difference between expected and actual behavior

Mice shouldn't be unscrewing lightbulbs and setting off fire alarms.

#### Steps to reproduce

Be a mouse. Try to do things.

#### Specific information for locating

Items i've (so far) found that mice can meaningfully manipulate and interact with:

Elevator call buttons
Fire alarms
Portable air pumps
Portable scrubbers
Light bulbs

#### Length of time in which bug has been known to occur

Since I started hosting scavstation, but probably longer. At least ~6 weeks.

#### Client version, Server revision & Game ID

Client Version: 514
Server Revision: 013e91177a69345c0a692db0b6f73915933075ce - dev - 2022-06-09
Game ID: cip-aakB
Current map: Tradeship Ivenmoth

#### Issue bingo

- [x] Issue could be reproduced at least once
- [x] Issue could be reproduced by different players
- [x] Issue could be reproduced in multiple rounds
- [x] Issue happened in a recent (less than 7 days ago) round
- [x] [Couldn't find an existing issue about this](https://github.com/NebulaSS13/Nebula/issues)

**Comment by MistakeNot4892** [comment]
Appears to be related to Chinsky's natural weapon PR giving animals a way to call `attack_hand()`.

**Comment by MistakeNot4892** [comment]
Closing for now, please reopen with specific interactions you think are inappropriate if they pop up again. Mice should be very restricted in what they can interact with following the dexterity changes.
