### ISSUE TITLE
After an item has been equipped to the back slot, it refuses to properly leave your inventory.

### ISSUE THREAD

**Issue by kelgaras** [NebulaSS13/Nebula#2535]
#### Description of issue

when you try to put the backpack on the floor, it is placed, but at the same time it breaks the slot of the back and the arm with which you put it

#### Difference between expected and actual behavior

I put my backpack on floor properly, its all

#### Steps to reproduce

try to put backpack on floor

#### Issue bingo

- [x] Issue could be reproduced at least once
- [x] Issue could be reproduced by different players
- [x] Issue could be reproduced in multiple rounds
- [x] Issue happened in a recent (less than 7 days ago) round
- [x] [Couldn't find an existing issue about this](https://github.com/NebulaSS13/Nebula/issues)

**Comment by MistakeNot4892** [comment]
Reproduced on dev - the backpack leaves the slot visibly but is still set to `holding` on the hand inventory slot.

**Comment by MistakeNot4892** [comment]
Does not occur if you use a mob you spawned to pick up the backpack and put it down, until you equip it to the back slot, after which the issue starts happening again.

**Comment by MistakeNot4892** [comment]
Appears to be anything equipped to the back slot - head, suit, etc. did not cause the issue, but /obj/item/scythe equipped to the back slot did.

**Comment by MistakeNot4892** [comment]
Can't reproduce on staging. I would hazard a guess this is due to something in #2494
