### ISSUE TITLE
you cant fully deploy hardsuit without shoes on your fits

### ISSUE THREAD

**Issue by kelgaras** [NebulaSS13/Nebula#2546]
#### Description of issue

you cant fully deploy hardsuit without shoes on your fits

#### Difference between expected and actual behavior

yuo can do this

#### Steps to reproduce

tru to deploy hardsuit without shoes on your fits

#### Specific information for locating
![dreamseeker_JvG9VadwgK](https://user-images.githubusercontent.com/87154286/174768171-c563c2eb-b56b-4de6-a436-2cf9f28e762a.png)

![dreamseeker_Zg8FQGEGRs](https://user-images.githubusercontent.com/87154286/174768385-187d8234-c220-4333-afee-4b994b18bb2b.gif)

#### Issue bingo

- [x] Issue could be reproduced at least once
- [ ] Issue could be reproduced by different players
- [x] Issue could be reproduced in multiple rounds
- [x] Issue happened in a recent (less than 7 days ago) round
- [x] [Couldn't find an existing issue about this](https://github.com/NebulaSS13/Nebula/issues)

**Comment by MistakeNot4892** [comment]
Dev or staging?

**Comment by kelgaras** [comment]
> Dev or staging?

dev
