### ISSUE TITLE
Organs cant be removed 

### ISSUE THREAD

**Issue by SolatK** [NebulaSS13/Nebula#2548]
#### Description of issue
Internal organs cant be removed from body
![изображение](https://user-images.githubusercontent.com/29740451/175440230-8ca61310-eebf-445d-a021-6f952a5ec834.png)
![изображение](https://user-images.githubusercontent.com/29740451/175440240-1c386698-b4b0-4547-aca4-e27510b61738.png)

#### Steps to reproduce
1) spawn a human
2) do organ detach surgery 
3) remove detached organ with hemostat
4) It still inside, you can reattach it or remove again.

#### Client version, Server revision & Game ID

Server Revision: 9f6e9ce9a30144f89f6346908d1c6a8c2562819a - dev - 2022-06-23

#### Issue bingo

- [x] Issue could be reproduced at least once
- [x] Issue could be reproduced by different players
- [x] Issue could be reproduced in multiple rounds
- [x] Issue happened in a recent (less than 7 days ago) round
- [x] [Couldn't find an existing issue about this](https://github.com/NebulaSS13/Nebula/issues)

**Comment by MistakeNot4892** [comment]
Should be fixed by #2549
