### ISSUE TITLE
People's heads appears over their hoods

### ISSUE THREAD

**Issue by PsyCommando** [NebulaSS13/Nebula#2583]
#### Description of issue
Hooded clothing that have a single sprite for both the suit and the hood don't layer properly with the human mob's head. The head is drawn over the hood, because the hood is part of the suit.

![2022-07-28 21_06_41-Window](https://user-images.githubusercontent.com/8772299/181839678-a47204b2-110b-4e01-ab3c-db4af0e23c77.png)
![2022-07-28 20_57_34-Window](https://user-images.githubusercontent.com/8772299/181839693-079ca445-0a1c-4423-a2bd-ea53ea583372.png)

#### Difference between expected and actual behavior
Normally the character's head would appear covered by the hood, but instead it layers over it.

Here's how the wintercoat would look on bay:
![2022-07-28 22_07_25-Window](https://user-images.githubusercontent.com/8772299/181839767-00283e6e-3114-43a4-95f0-9423f512b2d8.png)

#### Steps to reproduce
Put on a wintercoat, toggle the hood. Notice how the head is above the hood

#### Length of time in which bug has been known to occur

At least a few months.

#### Client version, Server revision & Game ID

51faf71b4ef11ee4c69423382297804dbf144bd5

#### Issue bingo

- [x] Issue could be reproduced at least once
- [x] Issue could be reproduced by different players
- [x] Issue could be reproduced in multiple rounds
- [x] Issue happened in a recent (less than 7 days ago) round
- [x] [Couldn't find an existing issue about this](https://github.com/NebulaSS13/Nebula/issues)

**Comment by MistakeNot4892** [comment]
![image](https://user-images.githubusercontent.com/2468979/182327322-c0d31941-412d-44f7-8ae6-cf5cd48059b5.png)
Can't reproduce on staging, trying to repro on dev now.

**Comment by MistakeNot4892** [comment]
![image](https://user-images.githubusercontent.com/2468979/182328323-407d37e6-c9f7-4d2f-9b2d-f7be1e0b6140.png)
Can't reproduce on dev.

This is expected behavior if you change the hidehair flags as you did your PR, I am guessing you were not on plain dev when you saw this.

**Comment by PsyCommando** [comment]
Yeah, seems like that might have been it. I just re tested on a fresh branch and it worked fine. 
I guess I'll make a bug report for facial hair not showing up when you have a hood.
