### ISSUE TITLE
Human wearing a hood have no facial hair

### ISSUE THREAD

**Issue by PsyCommando** [NebulaSS13/Nebula#2595]
#### Description of issue
When wearing a hood, people's facial hair disapear.

#### Difference between expected and actual behavior
Hoods shouldn't hide facial hair.

#### Steps to reproduce
Have facial hair, wear a hood, notice the lack of facial hair.

#### Issue bingo

- [x] Issue could be reproduced at least once
- [ ] Issue could be reproduced by different players
- [x] Issue could be reproduced in multiple rounds
- [x] Issue happened in a recent (less than 7 days ago) round
- [x] [Couldn't find an existing issue about this](https://github.com/NebulaSS13/Nebula/issues)

**Comment by MistakeNot4892** [comment]
Closing this as it's fixed on dev.
