### ISSUE TITLE
MMI holders use the BP_BRAIN tag and lead to a constant 200 brain damage

### ISSUE THREAD

**Issue by noelle-lavenza** [NebulaSS13/Nebula#2600]
#### Description of issue
Species with non-`/obj/item/organ/internal/brain` organs in the `BP_BRAIN` slot will fail the newly-added istype checks, meaning no brain is able to be gotten. However, since they have *something* in the slot, the game thinks they're supposed to have a fleshy brain and lack one. They default to 200 brain damage when this happens. This is particularly an issue with MMI holders (and subtypes) in FBPs (and synthetics), because those have `organ_tag = BP_BRAIN`.

#### Difference between expected and actual behavior
`GET_ORGAN` wouldn't fail with non-brains in the brain slot.

#### Steps to reproduce
1. Spawn in as a species with a non-`/obj/item/organ/internal/brain` organ in the `BP_BRAIN` slot.
2. Be really slow.
3. Check VV to see that you have 200 brain damage that can't be healed.

#### Length of time in which bug has been known to occur
Since the istype checks were added to `GET_ORGAN()`.

#### Client version, Server revision & Game ID
Latest dev.

#### Issue bingo

- [x] Issue could be reproduced at least once
- [ ] Issue could be reproduced by different players
- [x] Issue could be reproduced in multiple rounds
- [x] Issue happened in a recent (less than 7 days ago) round
- [x] [Couldn't find an existing issue about this](https://github.com/NebulaSS13/Nebula/issues)

**Comment by MistakeNot4892** [comment]
Tags are a bit of a formality, will open a PR to revert the typechecking on brainloss procs shortly. This is a downstream problem though, nothing on main Neb uses BP_BRAIN for a non-brain-subtyped item, intentionally - brain status/damage threshold procs are defined at the brain level, so some code needs to cast to brain.
