### ISSUE TITLE
Shield generator sometimes randomly refuses interactions

### ISSUE THREAD

**Issue by PsyCommando** [NebulaSS13/Nebula#2601]
#### Description of issue
Its a pretty hard to track issue because its been somewhat random, and its been hard to tell if its a bug or not.
But, after running/charging for some time, the shield generator won't let you open its ui, even though its powered and undamaged. It usually becomes possible to interact with it again a while later, and it will then again become impossible to interact with it. 

I suspect it might have something to do with some of the power checks in the shield gen code, or maybe the power net can't output enough, and isn't giving enough feedback. But in my tests it was pretty hard to say. Especially since the generator would let you interact again after some time even if the power input hadn't significantly changed.

#### Difference between expected and actual behavior
It should always display its UI when powered and intact.

#### Steps to reproduce
* Build shield generator, and connect it to a cable linked to a smes' output, with some power generation mean.
* Start it with any shield settings, preferably at least 2 of them. 
* Notice how some time later it becomes impossible to open its UI for a random amount of time.

#### Length of time in which bug has been known to occur

Probably a month.

#### Issue bingo

- [X] Issue could be reproduced at least once
- [X] Issue could be reproduced by different players
- [X] Issue could be reproduced in multiple rounds
- [ ] Issue happened in a recent (less than 7 days ago) round
- [X] [Couldn't find an existing issue about this](https://github.com/NebulaSS13/Nebula/issues)

**Comment by MistakeNot4892** [comment]
Going to close this for now pending any reliable reproduction steps.
