### ISSUE TITLE
Oxyloss behave oddly

### ISSUE THREAD

**Issue by PsyCommando** [NebulaSS13/Nebula#2617]
#### Description of issue
Oxyloss doesn't seem to ever go down when you got into a low pressure area and back into a normal pressure area. And beyond a certain point it'll just keep increasing until you die. All that happens way too quickly compared to usual. 

Also, rejuvenating doesn't seem to clear oxy damage at all. You have to manually apply -100 oxy damage a few times for it to clear off completely. 

#### Difference between expected and actual behavior
Short duration exposures to low oxygen areas don't usually kill you this fast. And rejuvenating should clear all oxy loss.

#### Steps to reproduce
* Partially vent a room below safe levels.
* Go into the room.
* Wait until it says something about not being able to breath.
* Leave the room.
* Notice its not going away.
* Try to rejuvenate.
* Notice it doesn't do anything about the oxy loss.
* Look at the vars and confirm looking at the oxy loss in VV.

#### Issue bingo

- [x] Issue could be reproduced at least once
- [x] Issue could be reproduced by different players
- [x] Issue could be reproduced in multiple rounds
- [x] Issue happened in a recent (less than 7 days ago) round
- [x] [Couldn't find an existing issue about this](https://github.com/NebulaSS13/Nebula/issues)

**Comment by MistakeNot4892** [comment]
Was this on dev or staging?

**Comment by MistakeNot4892** [comment]
Noting that rejuvenate() does by default clear oxyloss, I would assume something the human mob is doing is reapplying it afterward.

**Comment by MistakeNot4892** [comment]
This seems to be down to getOxyLoss returning a percentage, but adjustOxyLoss and setOxyLoss dealing with absolute values. Behavior all seems normal with this fixed on staging. Oxyloss does down you fairly quickly, but it's in the vicinity of twenty or thirty seconds, not immediately.

**Comment by MistakeNot4892** [comment]
Staging fixes have resolved the main issues I could see with oxyloss, we can reopen with more specific bugs if issues persist.
