### ISSUE TITLE
Premade manuals in-game don't work properly

### ISSUE THREAD

**Issue by PsyCommando** [NebulaSS13/Nebula#2630]
#### Description of issue
A few manuals in the game show an error page, or contain error messages and have incomplete contents.
![image](https://user-images.githubusercontent.com/8772299/185807541-10f4b1c8-6cc3-40ff-bffe-e46d95e70f53.png)
Usually it shows a message string: ``Cannot find file \tmp154608\List_of_Medical_Chemicals&printable=yes&remove_links=1``

#### Difference between expected and actual behavior
Books should actually display their associated wepbage.

#### Steps to reproduce
Open a premade book.

#### Issue bingo

- [x] Issue could be reproduced at least once
- [ ] Issue could be reproduced by different players
- [x] Issue could be reproduced in multiple rounds
- [x] Issue happened in a recent (less than 7 days ago) round
- [x] [Couldn't find an existing issue about this](https://github.com/NebulaSS13/Nebula/issues)

**Comment by MistakeNot4892** [comment]
This is a bit of a wontfix, these manuals expect a provided wikiurl which is sort of against the intent of Neb. Ideally the entire set of manuals would be converted to pull a guide page out of the codex to display instead. Ex:
````
/obj/item/book/manual/chef_recipes
	name = "Chef Recipes"
	icon_state = "cooked_book"
	author = "Victoria Ponsonby"
	title = "Chef Recipes"

/obj/item/book/manual/chef_recipes/Initialize()
	. = ..()
	dat = {"<html>
				<head>
				<style>
				h1 {font-size: 18px; margin: 15px 0px 5px;}
				h2 {font-size: 15px; margin: 15px 0px 5px;}
				h3 {font-size: 13px; margin: 15px 0px 5px;}
				li {margin: 2px 0px 2px 15px;}
				ul {margin: 5px; padding: 0px;}
				ol {margin: 5px; padding: 0px 15px;}
				body {font-size: 13px; font-family: Verdana;}
				</style>
				</head>
				<body>
				[SScodex.get_guide(/decl/codex_category/recipes)]
				</body>
			</html>
			"}
````

**Comment by MistakeNot4892** [comment]
Somewhat fixed in terms of removing the URL behavior in favour of codex links - still need several manuals written.
