### ISSUE TITLE
Resource duplication bug

### ISSUE THREAD

**Issue by Qumefox** [NebulaSS13/Nebula#2632]
#### Description of issue
Feeding stacks of steel floor tiles with more than ~15 tiles into the autolathe increases the steel count of the autolath, but does not remove tiles form the stack. This only seems to affect stacks with greater than 15 tiles or so. The stacks I noticed it on had 17, and 22 tiles respectively.  Using smaller stacks seems to work as expected.

#### Difference between expected and actual behavior
Tiles should be decreasing from the stack when fed to the autolathe.

#### Steps to reproduce

Pry up or build 16 or more floor tiles and put them in a single stack, then feed this to the autolathe. The autolathe will fill, but tiles won't vanish from the stack.

#### Length of time in which bug has been known to occur
I just stumbled on this tonight testing maintenance/construction drones.  (8/21/2022)

#### Client version, Server revision & Game ID
I forgot to note this but I can get it if it's reaaaaly needed.

#### Issue bingo

- [x] Issue could be reproduced at least once
- [ ] Issue could be reproduced by different players
- [ ] Issue could be reproduced in multiple rounds
- [x] Issue happened in a recent (less than 7 days ago) round
- [x] [Couldn't find an existing issue about this](https://github.com/NebulaSS13/Nebula/issues)

**Comment by MistakeNot4892** [comment]
Seems to be more broadly an issue with matter calculation for stacks, splitting 10 tiles off a stack of 85 ended up with `/decl/material/solid/metal/steel -> 4303125` which is completely insane.
