### ISSUE TITLE
Hydro tray bubbling loop and buggy fertilizer bottles

### ISSUE THREAD

**Issue by Qumefox** [NebulaSS13/Nebula#2633]
#### Description of issue
Constant bubbling of hydroponics trays and both fertilizer and trays reading as -nan units left.
Reported as an issue on the Scavstation repo by sharah-za-fluffy.  Moving to Nebula since it's not a scav specific issue - Qumefox

#### Difference between expected and actual behavior
Said buggy remaining units readout and constant annoying bubbling spam that can be heard from all decks

#### Steps to reproduce
Not sure but I believe it's this:
1: let trays be drained fully of water and nutrients by weeds
2:remove dead weeds but do not use hoe to weed out the tray further
3: using bucket set to 180 units fill with sink and then pour it into tray
4: take bottle of fertilizer and dump most if not all of it in tray
5: if bug happens it should read as -nan units in bottle and tray and the bubblepocalyce is upon you

#### Specific information for locating
When examining the tray, it shows
"It contains -nan amounts of liquid"

#### Length of time in which bug has been known to occur
Happened first around noon of august 20th 2022

#### Client version, Server revision & Game ID
Client Version: 514
Server Revision: https://github.com/ScavStation/ScavStation/commit/cfe491f97b99736add5bf046c7a3970b3fc8fc50 - dev - 2022-08-19
Game ID: cjv-buNB
Current map: Tradeship Ivenmoth

#### Issue bingo

- [x] Issue could be reproduced at least once
- [ ] Issue could be reproduced by different players
- [ ] Issue could be reproduced in multiple rounds
- [x] Issue happened in a recent (less than 7 days ago) round
- [x] [Couldn't find an existing issue about this](https://github.com/NebulaSS13/Nebula/issues)

**Comment by MistakeNot4892** [comment]
Suspect this is temperature or solvent based (the bubbling) and that the NAN issue is down to rounding being screwy.
