### ISSUE TITLE
One last y character straggler found

### ISSUE THREAD

**Issue by Qumefox** [NebulaSS13/Nebula#2635]
#### Description of issue
One last 'y' character preceding text has been spotted in the R-UST control panel.

#### Difference between expected and actual behavior
Y U NO GO AWAY

#### Steps to reproduce
Open the R-UST terminal in engineering

#### Length of time in which bug has been known to occur
For a while now. Most of these have been fixed but I spotted one more.

#### Issue bingo

- [x] Issue could be reproduced at least once
- [ ] Issue could be reproduced by different players
- [x] Issue could be reproduced in multiple rounds
- [x] Issue happened in a recent (less than 7 days ago) round
- [x] [Couldn't find an existing issue about this](https://github.com/NebulaSS13/Nebula/issues)

![Screenshot 2022-08-22 103339](https://user-images.githubusercontent.com/38769166/185974218-edf34e78-4f10-47f6-84a1-6fbd62660a27.png)

**Comment by MistakeNot4892** [comment]
This is sort of expected for anything passing `\improper` to a browser window.

**Comment by Qumefox** [comment]
Yes i'm aware. However these characters used to be everywhere, Those got fixed. This is the only instance of it I find remaining now. None of the other browser windows in engineering have this character anymore. Gyrotron control etc. It's just the R-UST window now.

**Comment by MistakeNot4892** [comment]
`strip_improper()` appears to fail to strip out `\improper` and `\proper` after the string has been embedded - have not managed to work out how to strip the little accented y out yet.

**Comment by MistakeNot4892** [comment]
Per discussion on Discord, we should be able to at least strip out leading `\improper` via the broken ASCII that DM emits.

**Comment by out-of-phaze** [comment]
Should have been fixed in #2918, if it occurs again please create a new issue for it.
