### ISSUE TITLE
Code issues: Uses of initial on lists

### ISSUE THREAD

**Issue by PsyCommando** [NebulaSS13/Nebula#2747]
#### Description of issue
Here are a bunch of initial() call on lists which return garbage non-null values because lists are apparently unsupported by initial.

code\controllers\subsystems\initialization\codex.dm:30
```
if(initial(centry.name) || initial(centry.associated_paths) || initial(centry.associated_strings))
```

code\modules\clothing\spacesuits\rig\rig_wiring.dm:32
```dm
rig.req_access = initial(rig.req_access)
```

code\modules\shuttles\shuttle_emergency.dm:118
```dm
authorized = initial(authorized)
```

code\modules\admin\verbs\massmodvar.dm:116
```dm
O.vars[variable] = initial(O.vars[variable])
```
It doesn't check if the initial variable value is a list, object instance, or anything that can't be used with initial.

code\modules\admin\verbs\modifyvariables.dm:228
```dm
new_var = initial(variable)
```
Same as above.

code\modules\admin\view_variables\helpers.dm:107
```dm
/datum/proc/get_initial_variable_value(varname)
	return initial(vars[varname])
```
Same as above.

**Comment by MistakeNot4892** [comment]
VV ones are a bit w/e, no clean way to identify and warn against those.

**Comment by Kapu1178** [comment]
The technical explanation of why lists aren't supported by initial, is you need to remember lists are an object type in byond.

`initial()` returns `null` for all variables whose defined value is an object instance. This is because it's compile time value is actually `null`, and the hidden internal proc called `init()` creates the instances.

**Comment by PsyCommando** [comment]
> The technical explanation of why lists aren't supported by initial, is you need to remember lists are an object type in byond.
> 
> `initial()` returns `null` for all variables whose defined value is an object instance. This is because it's compile time value is actually `null`, and the hidden internal proc called `init()` creates the instances.

It  doesn't return null actually. It returns a garbage value that doesn't cast to null.

**Comment by MistakeNot4892** [comment]
From what I can tell the fixable entries in this issue have been fixed. The VV handlers are not something easily updated to handle list values without a broader feature PR.

Specific individual initial() on lists should probably be given their own issues. I'm going to close this one for now as I don't think it serves much of a purpose being open indefinitely with the main body of it resolved.
