### ISSUE TITLE
lathes destroy materials

### ISSUE THREAD

**Issue by SolatK** [NebulaSS13/Nebula#2752]
#### Description of issue
lathes destroy materials

#### Difference between expected and actual behavior
It should give out sheets

#### Steps to reproduce
1) insert materials
2) press this button
![Скриншот 20-10-2022 234139](https://user-images.githubusercontent.com/29740451/197054281-49dd60c1-971b-4a27-b284-f9df21d778f4.png)
3) no runtimes, no materials, no sheets

#### Client version, Server revision & Game ID

Client Version: 514
Server Revision: 6c201bca35775118172e821ab4b2d270450d6111 - dev - 2022-10-20
Game ID: cku-dgmc
Current map: Tradeship Ocelot Alpha

#### Issue bingo

- [x] Issue could be reproduced at least once
- [x] Issue could be reproduced by different players
- [x] Issue could be reproduced in multiple rounds
- [x] Issue happened in a recent (less than 7 days ago) round
- [x] [Couldn't find an existing issue about this](https://github.com/NebulaSS13/Nebula/issues)

**Comment by MistakeNot4892** [comment]
Can't repro on stable.
