### ISSUE TITLE
materials stack digits

### ISSUE THREAD

**Issue by SolatK** [NebulaSS13/Nebula#2753]
#### Description of issue
roundstart materials have a digits on it sprite
![изображение](https://user-images.githubusercontent.com/29740451/197055669-2f8e1851-68f1-443d-85a5-ab0a14a4c2c4.png)

#### Difference between expected and actual behavior
![изображение](https://user-images.githubusercontent.com/29740451/197055775-508fede8-f92d-4f82-8f7e-615a30e7d48f.png)

#### Client version, Server revision & Game ID

Client Version: 514
Server Revision: 6c201bca35775118172e821ab4b2d270450d6111 - dev - 2022-10-20
Game ID: cku-dgmc
Current map: Tradeship Ocelot Alpha

#### Issue bingo

- [x] Issue could be reproduced at least once
- [x] Issue could be reproduced by different players
- [x] Issue could be reproduced in multiple rounds
- [x] Issue happened in a recent (less than 7 days ago) round
- [x] [Couldn't find an existing issue about this](https://github.com/NebulaSS13/Nebula/issues)

**Comment by MistakeNot4892** [comment]
Specifically seems to be stuff that initializes in a locker/crate.
