### ISSUE TITLE
Changing screen size to 64x64 twice extends view range

### ISSUE THREAD

**Issue by quardbreak** [NebulaSS13/Nebula#29]
If you press Size -> 64x64 twice, your square will be broken and you will have widescreen. The effect may stack after pressing 64x64 or other button in Size selection.

**Comment by MistakeNot4892** [comment]
Please supply further info, or screenshots.

**Comment by quardbreak** [comment]
This can happen even if you reload the game. You can extend your view size more than 15x15

![2020-02-24_23-06-40](https://user-images.githubusercontent.com/44920739/75187075-60260900-575a-11ea-882d-d3fc0a1ec167.gif)

**Comment by MistakeNot4892** [comment]
That is how the scaling is meant to function. Sliding the central bar just doesn't raise an event so can't do it automatically.

**Comment by MistakeNot4892** [comment]
Discussion on Discord - quard believes this is a balance concern, which is something for discussion, but isn't a bug. This is intended behavior so I'm going to close the ticket - we can keep discussing the potential problems.
