### ISSUE TITLE
CI fail due to bot teleporting?

### ISSUE THREAD

**Issue by PsyCommando** [NebulaSS13/Nebula#2927]
#### Description of issue
Very rarely the CI may fails with this runtime happening before the unit tests started, when testing the exodus map.

```
MC: Runlevel changed from NULL to 1
Master starting processing
MC: Runlevel changed from 1 to 2
## UNIT_TEST ##: Game start has been requested.
[15:00:00] Runtime in areas.dm,330: Cannot read null.has_gravity
  proc name: Entered (/area/Entered)
  src: the Space (/area/space)
  call stack:
  the Space (/area/space): Entered(Officer Beepsky (/mob/living/bot/secbot/beepsky), the floor (113,160,2) (/turf/simulated/floor/tiled/steel_grid))
  Officer Beepsky (/mob/living/bot/secbot/beepsky): forceMove(space (113,249,2) (/turf/space))
  Officer Beepsky (/mob/living/bot/secbot/beepsky): forceMove(space (113,249,2) (/turf/space))
  Officer Beepsky (/mob/living/bot/secbot/beepsky): forceMove(space (113,249,2) (/turf/space))
  Officer Beepsky (/mob/living/bot/secbot/beepsky): forceMove(space (113,249,2) (/turf/space))
  teleport (/datum/artifact_effect/teleport): teleport away(Officer Beepsky (/mob/living/bot/secbot/beepsky))
  teleport (/datum/artifact_effect/teleport): DoEffectAura()
  teleport (/datum/artifact_effect/teleport): process()
  the alien artifact (/obj/structure/artifact): Process(10, 0, Objs (/datum/controller/subsystem/processing/obj))
  Objs (/datum/controller/subsystem/processing/obj): fire(1)
  Objs (/datum/controller/subsystem/processing/obj): ignite(1)
  Master (/datum/controller/master): RunQueue()
  Master (/datum/controller/master): Loop()
  Master (/datum/controller/master): StartProcessing(0)
MC: Runlevel changed from 2 to 3
## UNIT_TEST ##: The game is now in progress.
## UNIT_TEST ##: Testing Started.
```

#### Difference between expected and actual behavior
Shouldn't runtime.

#### Steps to reproduce
It's completely random. But, if I have to guess, it's probably a missing validity check somewhere.

#### Specific information for locating

See above for log.

Happened on a completely unrelated 2 line PR swapping icon for something.
https://github.com/PersistentSS13/Nebula/actions/runs/4001248500/jobs/6867287089

#### Length of time in which bug has been known to occur

No ideas.

#### Client version, Server revision & Game ID

Downstream revision. 

#### Issue bingo

- [ ] Issue could be reproduced at least once
- [ ] Issue could be reproduced by different players
- [ ] Issue could be reproduced in multiple rounds
- [x] Issue happened in a recent (less than 7 days ago) round
- [x] [Couldn't find an existing issue about this](https://github.com/NebulaSS13/Nebula/issues)

**Comment by MistakeNot4892** [comment]
This was fixed 9 months ago apparently, never closed the issue oops.
