### ISSUE TITLE
Some machinery clears mapped values during init

### ISSUE THREAD

**Issue by PsyCommando** [NebulaSS13/Nebula#2928]
#### Description of issue
Some machines, like ``/obj/machinery/atmospherics/unary/heater`` will lose the values set via the map editor when the map is loaded.
For example with heaters/coolers the vars ``power_setting`` and ``set_temperature`` get reset to default.

It happens because refresh part is called at least once before the components needed to calculate the efficiency of the machine are spawned, and so the equation results in nulled out values:

```
/obj/machinery/atmospherics/unary/heater/RefreshParts()
	..()
	var/cap_rating = clamp(total_component_rating_of_type(/obj/item/stock_parts/capacitor), 1, 20)
	var/bin_rating = clamp(total_component_rating_of_type(/obj/item/stock_parts/matter_bin), 0, 10)

	max_power_rating = initial(max_power_rating) * cap_rating / 2
	max_temperature = max(initial(max_temperature) - T20C, 0) * ((bin_rating * 4 + cap_rating) / 5) + T20C
	air_contents.volume = max(initial(internal_volume) - 200, 0) + 200 * bin_rating
	set_power_level(power_setting)

/obj/machinery/atmospherics/unary/heater/proc/set_power_level(var/new_power_setting)
	power_setting = new_power_setting
	power_rating = max_power_rating * (power_setting/100)
``` 

#### Difference between expected and actual behavior
Normally, the mapped values should be retained intact until part init is complete, and only them clamped and sanitized. So we don't lose the value along the way during setup.

#### Steps to reproduce
* Change the power setting and set_temperature of a mapped heater to anything non-default. 
* Load the game. 
* Notice the heater will have reset its values.

#### Length of time in which bug has been known to occur
Maybe 6 months, give or take.

#### Issue bingo

- [x] Issue could be reproduced at least once
- [ ] Issue could be reproduced by different players
- [x] Issue could be reproduced in multiple rounds
- [ ] Issue happened in a recent (less than 7 days ago) round
- [x] [Couldn't find an existing issue about this](https://github.com/NebulaSS13/Nebula/issues)

**Comment by afterthought2** [comment]
I don't follow; the code you linked does not modify either of the variables you mention. 

It does override `max_` variants if you set them in map files on a dmm-suite loaded map, due to the use of initial; best practice in that case is to use subtypes instead.
