### ISSUE TITLE
Diona nymph and kharmaani nymph held items do not show up on the HUD.

### ISSUE THREAD

**Issue by MistakeNot4892** [NebulaSS13/Nebula#2974]
#### Description of issue
Items picked up by a nymph do not show on the HUD. `holding_item` is also inconsistently set.

#### Difference between expected and actual behavior
Inventory should work.

#### Steps to reproduce
Pick up a thing as a nymph of either kind.

#### Specific information for locating
Nothing springs to mind.

#### Length of time in which bug has been known to occur
Unclear.

#### Client version, Server revision & Game ID
Current dev.

#### Issue bingo
- [X] Issue could be reproduced at least once
- [ ] Issue could be reproduced by different players
- [X] Issue could be reproduced in multiple rounds
- [X] Issue happened in a recent (less than 7 days ago) round
- [X] [Couldn't find an existing issue about this](https://github.com/NebulaSS13/Nebula/issues)

**Comment by out-of-phaze** [comment]
Fixed on stable in #2994.
