### ISSUE TITLE
Exoplanet water textures are odd

### ISSUE THREAD

**Issue by ZirconiumWit** [NebulaSS13/Nebula#3207]
#### Description of issue
![image](https://github.com/NebulaSS13/Nebula/assets/59771903/45abfc05-dbd8-432e-a2b0-d9d321196799)
Just look at it.  Just look!

#### Difference between expected and actual behavior
Did you even look at it.

#### Steps to reproduce
Go to exoplanet and LOOK at it.

#### Specific information for locating

you would know if you looked at the water

#### Length of time in which bug has been known to occur

Long-lived issue.

#### Client version, Server revision & Game ID

Client Version: 514
Server Revision: 4612e6429c32f0ac6c24ff5225111545ba7a0fea - staging - 2023-07-10
Game ID: coO-dGaB
Current map: Tradeship Ocelot Alpha

#### Issue bingo

- [x] Issue could be reproduced at least once
- [x] Issue could be reproduced by different players
- [x] Issue could be reproduced in multiple rounds
- [x] Issue happened in a recent (less than 7 days ago) round
- [x] [Couldn't find an existing issue about this](https://github.com/NebulaSS13/Nebula/issues)

**Comment by MistakeNot4892** [comment]
Fixed on dev following water turf changes.
