### ISSUE TITLE
Sealed mech chassis air supply doesn't work

### ISSUE THREAD

**Issue by Morguemeat** [NebulaSS13/Nebula#3247]
#### Description of issue

The internal air supply of the sealed mech chassis does not support life. 

#### Difference between expected and actual behavior

When you use the sealed mech chassis on a mech with the canopy closed, it should provide breathable atmosphere. It does not.

#### Steps to reproduce

Build a mech with a Sealed Chassis, close the canopy, turn the air on, and walk out into space. You will suffocate and die.

#### Length of time in which bug has been known to occur

A few months at least.

#### Client version, Server revision & Game ID

Server Revision: dacf10adc96190b6cc5a8c8b0c79b1d99cab8199 - main - 2023-07-22
Game ID: coV-awZU 

#### Issue bingo

- [x] Issue could be reproduced at least once
- [x] Issue could be reproduced by different players
- [x] Issue could be reproduced in multiple rounds
- [x] Issue happened in a recent (less than 7 days ago) round
- [x] [Couldn't find an existing issue about this](https://github.com/NebulaSS13/Nebula/issues)

**Comment by out-of-phaze** [comment]
This is because you exhale into the environment, so you consume O2 and the concentration of nitrogen slowly rises. Solution pending, since we can't just make it use an oxygen tank. I think we'll probably just make it exhale the air into the turf the mech is on.
