### ISSUE TITLE
Prosthetic limbs caught a rash

### ISSUE THREAD

**Issue by sirleatherflute** [NebulaSS13/Nebula#3294]
#### Description of issue
Ailment random event shouldn't be applying to prosthetics.

#### Difference between expected and actual behavior
It does

#### Steps to reproduce
Unknown
(May be a coincidence, but the limbs were hit by EMP both times)

#### Specific information for locating

"A bright red rash on your robotic left hand itches distractingly"

#### Length of time in which bug has been known to occur

Happened twice in last 12 hours, last time around 8:45 UTC

#### Client version, Server revision & Game ID

Client Version: 514
Server Revision: 598864414cbfb0489f730a54dacc3fdcfcd60fae - main - 2023-08-29
cpw-dvaF
cpx-apzw

#### Issue bingo

- [ ] Issue could be reproduced at least once
- [ ] Issue could be reproduced by different players
- [x] Issue could be reproduced in multiple rounds
- [x] Issue happened in a recent (less than 7 days ago) round
- [x] [Couldn't find an existing issue about this](https://github.com/NebulaSS13/Nebula/issues)

**Comment by out-of-phaze** [comment]
Resolved in #3300.
