### ISSUE TITLE
Decals and possibly layers are broken.

### ISSUE THREAD

**Issue by SodiumShine** [NebulaSS13/Nebula#33]
Floor decals are not appearing correctly on tiled floors at round start. They still work fine on plating. Seems to happen for most kinds of floor_decals.

Painting the decals on in-game works fine.

Mining consoles also vanish when placed directly on walls as they are supposed to be, also vanish. (May not be related)

![image](https://user-images.githubusercontent.com/4461697/75215600-66ad9280-57e5-11ea-8d27-7ef7b555fe08.png)
![image](https://user-images.githubusercontent.com/4461697/75215607-70cf9100-57e5-11ea-91ee-aee5d2c03766.png)

**Comment by MistakeNot4892** [comment]
Did some testing of this - decals are fine if you apply them after world init, which would imply something is fucky with the ordering of decals being created and turfs updating their layer.
