### ISSUE TITLE
Tradeship Shuttle (Bee) has tiles that vanish on takeoff

### ISSUE THREAD

**Issue by Frenjo** [NebulaSS13/Nebula#3377]
#### Description of issue
When the Tradeship shuttle (I believe it's called the Bee) takes off, several tiles aren't taken with it and seem to be left behind at the Tradeship docking port.

#### Difference between expected and actual behavior
The shuttle shouldn't have bits that vanish when it takes off.

#### Steps to reproduce
Launch the Bee and watch some tiles vanish.

#### Specific information for locating

These are the two tiles I noticed, but this may affect the opposite side of the shuttle equally.
![image](https://github.com/NebulaSS13/Nebula/assets/2939692/8a7569b4-a6ce-4a30-8726-5952faddac7e)

#### Length of time in which bug has been known to occur

Since the recent test round we just did, around 01:00GMT on 24/09/2023.

#### Client version, Server revision & Game ID

**Client Version:** 514
**Server Revision:** 88ae4d3c8e33b4f51fbef970a1890596fd020a10 - staging - 2023-09-24
**Game ID:** cpX-acgh
**Current map:** Tradeship Ocelot Alpha

#### Issue bingo

- [X] Issue could be reproduced at least once
- [ ] Issue could be reproduced by different players
- [ ] Issue could be reproduced in multiple rounds
- [X] Issue happened in a recent (less than 7 days ago) round
- [X] [Couldn't find an existing issue about this](https://github.com/NebulaSS13/Nebula/issues)

**Comment by MistakeNot4892** [comment]
Bee area doesn't cover those turfs.
