### ISSUE TITLE
Overpricing of container items in vending machines

### ISSUE THREAD

**Issue by LuchiousCaine** [NebulaSS13/Nebula#3454]
#### Description of issue
This issue was initially found on ScavStation branch, then tested on Nebula Test Server. Issue is present on both.
I believe it is related to this issue: https://github.com/NebulaSS13/Nebula/issues/3221 but saw it was removed from r3 milestone, so not sure if still accounted for.

There appears to be an issue for vending machine prices when calculating the pricing of items that contain other items.
The screenshots are from items from vending machines:
![image](https://github.com/NebulaSS13/Nebula/assets/136999778/86112071-eba9-405a-b3d6-af8ea0384a9a)
![image](https://github.com/NebulaSS13/Nebula/assets/136999778/8bec2e37-fd4f-49a8-ae07-9fed01966d99)
![image](https://github.com/NebulaSS13/Nebula/assets/136999778/6bfcb903-0d25-469b-941b-e75629ac7be4)
![image](https://github.com/NebulaSS13/Nebula/assets/136999778/b7fa90c4-8e11-4ea3-b58b-8c553f7bfbbc)

It seems the value of every single item contained inside the container item is calculated and added to the price of the item, such as the case of a matchbox.
This is even the case for a character with Master Finance.

#### Difference between expected and actual behavior
Even if you start as an old character with large starting sum, you can't even afford a matchbox. That probably isn't intended.
Expected it to be affordable.

#### Steps to reproduce
Go to any vending machine and look at the prices when attempting to purchase something that contains other items.

#### Specific information for locating

Any object that contain other items sold in vending machines: "pack of...", "box of...", Matchbox, Etc...

#### Length of time in which bug has been known to occur

Personally found it the other day. 17th Oct.

#### Client version, Server revision & Game ID

Nebula Test Server:
Client Version: 514
Server Revision: 131dc3465be11c18d421bd5ff42de204e8786732 - staging - 2023-10-18
Game ID: cql-bxxt
Current map: Tradeship Ocelot Alpha

ScavStation Server:
Client Version: 514
Server Revision: e4186d0b2f5eab21b1f3273caf4d8a45542b304f - main - 2023-10-18
Game ID: cql-amop
Current map: Mollusc Station

#### Issue bingo

- [x] Issue could be reproduced at least once
- [x] Issue could be reproduced by different players
- [x] Issue could be reproduced in multiple rounds
- [x] Issue happened in a recent (less than 7 days ago) round
- [ ] [Couldn't find an existing issue about this](https://github.com/NebulaSS13/Nebula/issues)

**Comment by out-of-phaze** [comment]
Fixed in #3455, I think? I know I fixed most of the ones in the screenshot. Please open a new issue if other things have price issues.
