### ISSUE TITLE
Serpentids cannot access nanoUI programs requiring access

### ISSUE THREAD

**Issue by cyberillithid** [NebulaSS13/Nebula#3461]
#### Description of issue
Apparently, `/atom/movable/proc/GetIdCard()` works in such a way that the only ID Card worth considering for Serpentids is their system controller alien chip (with the only access of `ACCESS_ASCENT`). 

#### Difference between expected and actual behavior
Expected: Serpentids should be able to use modular computers with their job accesses.
Factual: Serpentids do not get any accesses to modular computer programs from their ID cards.

#### Steps to reproduce
1. Login as a Serpentid Captain
2. Try to open "Command and Communications program"

#### Specific information for locating
Obviously, `OS flashes "Access Denied" warning`.

I suspect issues with  `/atom/movable/proc/GetIdCards()` ordering.

#### Length of time in which bug has been known to occur
No idea.

#### Client version, Server revision & Game ID
Local `Nebula:stable`. 

#### Issue bingo
- [x] Issue could be reproduced at least once
- [ ] Issue could be reproduced by different players
- [x] Issue could be reproduced in multiple rounds
- [x] Issue happened in a recent (less than 7 days ago) round
- [x] [Couldn't find an existing issue about this](https://github.com/NebulaSS13/Nebula/issues)

**Comment by MistakeNot4892** [comment]
This is because GetAccess() defaults to union = FALSE I suspect. It just takes the access from the first ID card it finds.

**Comment by MistakeNot4892** [comment]
Should be fixed on stable.
