### ISSUE TITLE
Runtime error due to thrusters

### ISSUE THREAD

**Issue by trerri** [NebulaSS13/Nebula#3467]
#### Description of issue

You can reliably cause the game to runtime following the steps below.

#### Steps to reproduce

1. Start server
2. Go to bridge before there's any gas in the fuel pipenet
3. Turn on engines
4. Press the "minus" button on the thing that says "100%"

#### Specific information for locating

VSCode whined about line 34 of gas_thruster.dm and that's as far as my code knowledge takes me.

#### Length of time in which bug has been known to occur

No idea, I learned about the existence of Nebula like a week ago

#### Client version, Server revision & Game ID

Client Version: 514
Server Revision: f7b7e32b4e3a68163231e3bf702712fea2168ef5 - test - 2023-10-22
branch: stable
#### Issue bingo

- [x] Issue could be reproduced at least once
- [ ] Issue could be reproduced by different players
- [x] Issue could be reproduced in multiple rounds
- [x] Issue happened in a recent (less than 7 days ago) round
- [x] [Couldn't find an existing issue about this](https://github.com/NebulaSS13/Nebula/issues)

**Comment by out-of-phaze** [comment]
It sounds like you were running the game with the VSCode debugger attached, which by default pauses execution when a runtime error occurs. This wouldn't cause a live server to crash, but it still shouldn't runtime, so I'll look into the issue.

**Comment by MistakeNot4892** [comment]
````
[04:01:12] Runtime in gas_thruster.dm,34: Cannot read null.volume
  proc name: get propellant (/datum/extension/ship_engine/gas/proc/get_propellant)
  usr: Paris Patterson (/mob/living/carbon/human) ([0x3000025]) (the floor) (40,50,3 - Tradeship Ocelot Alpha) (/turf/simulated/floor/tiled/dark) (mistakenot4892)
  usr.loc: The floor (/turf/simulated/floor/tiled/dark) ([0x1015eef]) (40,50,3 - Tradeship Ocelot Alpha) (/area/ship/trade/command/bridge)
  src: /datum/extension/ship_engine/g... (/datum/extension/ship_engine/gas)
  call stack:
  /datum/extension/ship_engine/g... (/datum/extension/ship_engine/gas): get propellant(1, 1)
  /datum/extension/ship_engine/g... (/datum/extension/ship_engine/gas): get status()
  the engine control console (/obj/machinery/computer/ship/engines): ui interact(Paris Patterson (/mob/living/carbon/human), "main", /datum/nanoui (/datum/nanoui), 0, null, /datum/topic_state/default (/datum/topic_state/default))
  /datum/nanoui (/datum/nanoui): update(0)
  /datum/nanoui (/datum/nanoui): try update(1)
  NanoUI (/datum/controller/subsystem/processing/nano): update uis(the engine control console (/obj/machinery/computer/ship/engines))
  /datum/nanoui (/datum/nanoui): Topic("src=\[0x2101b7a1];global_limit...", /list (/list))
  MistakeNot4892 (/client): Topic("src=\[0x2101b7a1];global_limit...", /list (/list), /datum/nanoui (/datum/nanoui))
  ````

**Comment by MistakeNot4892** [comment]
Should be fixed on stable.
