### ISSUE TITLE
Extended emergency tank (yellow one) inhand is flipped

### ISSUE THREAD

**Issue by trerri** [NebulaSS13/Nebula#3474]
#### Description of issue

Emergency tank inhand renders on the wrong arm

#### Steps to reproduce

Hold a yellow small tank in your hand (not double!)

#### Client version, Server revision & Game ID

cb536fc534df2c1f3162a55c0c96fc6e93a25f4a (stable branch)

#### Issue bingo

- [x] Issue could be reproduced at least once
- [ ] Issue could be reproduced by different players
- [ ] Issue could be reproduced in multiple rounds
- [x] Issue happened in a recent (less than 7 days ago) round
- [x] [Couldn't find an existing issue about this](https://github.com/NebulaSS13/Nebula/issues)

**Comment by MistakeNot4892** [comment]
Should be fixed on stable.
