### ISSUE TITLE
Open space darkness remains despite it being toggled off by a ghost

### ISSUE THREAD

**Issue by trerri** [NebulaSS13/Nebula#3481]
#### Description of issue

![image](https://github.com/NebulaSS13/Nebula/assets/63235460/8289c9a3-6742-4ec1-8066-d7bfb9fc4210)

#### Difference between expected and actual behavior

If a ghost toggles darkness off, this should apply to all darkness. Instead, when viewing lower z-levels from above, their lighting is still applied as normal. This means the ghost has to go down a z-level to see it in fullbright. This is of course a very minor issue.

#### Steps to reproduce

Toggle darkness off as ghost and hover above a dark location

#### Client version, Server revision & Game ID

stable branch

**Comment by MistakeNot4892** [comment]
This isn't a bug so much as an inherent limitation of zmimic. The darkness of lower layers isn't actually darkness, it's a mimicked appearance on the turf above. Toggle Darkness just hides the darkness plane, which mimicked lighting doesn't use.

As far as I know this is functionally unfixable without some big overhead and rewrites, @Lohikar may have more input.

**Comment by out-of-phaze** [comment]
It's actually as trivial as setting invisibility on the shadower atoms to `invisibility = INVISIBILITY_LIGHTING`. That has other issues, though...
![image](https://github.com/NebulaSS13/Nebula/assets/110272328/1fa46d76-1924-42f0-a8f7-369c727b7b2a)
Shadowers are also used for depth cues. This would mean things like mesons and Quantum Mechanic no-lighting vision mode would remove multiz depth cues, which is kind of undesirable.

**Comment by MistakeNot4892** [comment]
Going to close this for now as it's unlikely to get looked at unless someone wants to implement Penny's thought above and works out a way to make QM goggles still useful.
