### ISSUE TITLE
blurry and unreadable photos from camera also cameras don't start with film installed

### ISSUE THREAD

**Issue by MistakeNot4892** [NebulaSS13/Nebula#3513]
Copied from https://github.com/ScavStation/ScavStation/issues/806

#### Description of issue
cameras on spawn don't start with film, and even if you do put film in them any photos from said camera are totally blurred if not outright a white square as seen in these two examples

![poop camera](https://github.com/ScavStation/ScavStation/assets/65055421/50a8fb8b-64e8-4f61-96b8-24b65b5c508b)
![poopcaera 2](https://github.com/ScavStation/ScavStation/assets/65055421/e2e22a06-d81f-4d79-bf5e-4fbe0c06bdba)

#### Difference between expected and actual behavior
needing to find film only to take totally useless photos anyway

#### Steps to reproduce
spawn with camera in your loadout, check to see if film is in it, if not steal film rolls from the courtroom or detectives office, then take a photo.

#### Specific information for locating

camera, camera film

#### Length of time in which bug has been known to occur

more than one month, mental skill issues kept me from making this ticket sooner

#### Client version, Server revision & Game ID

Revision: ScavStation
Date
2023-10-22
Branch
dev
Game ID
cqp-dJsl
Runtime Version
514.1589
Compiler Version
514.1589
Revision
432a7689b1cd1d0e0f271a5e2ac32209bc5f0505

#### Issue bingo

- [x] Issue could be reproduced at least once
- [x] Issue could be reproduced by different players
- [x] Issue could be reproduced in multiple rounds
- [x] Issue happened in a recent (less than 7 days ago) round
- [x] [Couldn't find an existing issue about this](https://github.com/ScavStation/ScavStation/issues)

**Comment by out-of-phaze** [comment]
Was fixed by #3488.
