### ISSUE TITLE
Culinary Mishaps

### ISSUE THREAD

**Issue by Recon104** [NebulaSS13/Nebula#3522]
#### Description of issue
Some recipes within the code dont properly produce their intended effect. Specifically, meatloaf produces a single cooked meatball and spits the rest of the ingredients out without creating a meatloaf.

#### Difference between expected and actual behavior
Meatloaf
Meatball

#### Steps to reproduce
Obtain all ingredients to create a regular meatloaf. Insert into microwave, receive one cooked meatball. 

#### Specific information for locating

Meatloaf

#### Length of time in which bug has been known to occur

Only tested roughly 4 months ago, but presumably an issue for longer.

#### Client version, Server revision & Game ID

Date
2023-12-09
Branch
main
Game ID
crb-cUhK
Runtime Version
514.1589
Compiler Version
514.1589
Revision
b8eae690be904a37869af8645d900b449dd55dbc

#### Issue bingo

- [X] Issue could be reproduced at least once
- [X] Issue could be reproduced by different players
- [X] Issue could be reproduced in multiple rounds
- [ ] Issue happened in a recent (less than 7 days ago) round
- [X] [Couldn't find an existing issue about this](https://github.com/NebulaSS13/Nebula/issues)

**Comment by MistakeNot4892** [comment]
Can't reproduce this - we don't have a meatloaf recipe, and raw meatball + raw cutlet successfully makes a sausage. Feel free to reopen if you can reproduce.
