### ISSUE TITLE
helmet light overlay stacks

### ISSUE THREAD

**Issue by 43082ujfgrj** [NebulaSS13/Nebula#3592]
#### Description of issue
![image](https://github.com/NebulaSS13/Nebula/assets/155900968/7d800dda-d098-4f93-bf0b-61d2d1464df2)
voidsuit helmet light overlays stacks
space helmets are the same
the helmets light overlays in general should be reviewed

#### Client version, Server revision & Game ID

89c57d192ad0aa7f72c2354deaa1a4c9dffbf4ce - stable - 2024-01-14

#### Issue bingo

- [x] Issue could be reproduced at least once
- [ ] Issue could be reproduced by different players
- [x] Issue could be reproduced in multiple rounds
- [x] Issue happened in a recent (less than 7 days ago) round
- [x] [Couldn't find an existing issue about this](https://github.com/NebulaSS13/Nebula/issues)

**Comment by MistakeNot4892** [comment]
I think I fixed this on dev recently, will check.
