### ISSUE TITLE
price/worth oddities

### ISSUE THREAD

**Issue by 43082ujfgrj** [NebulaSS13/Nebula#3625]
#### Description of issue
![image](https://github.com/NebulaSS13/Nebula/assets/155900968/a228ac26-a295-4511-8e09-b48bf714dc6a)
projectile/automatic/assault_rifle changes its worth depending on the firemode

vending in general?
![image](https://github.com/NebulaSS13/Nebula/assets/155900968/bb64e84e-ff99-4941-ab4f-a5795f008df6)
![image](https://github.com/NebulaSS13/Nebula/assets/155900968/02a48098-825e-460f-8b2f-1d314929e684)
(not sure if intended, also afaik it worked before but incorrectly because it used values WITH markup which creates worth out of nowhere)
UPD: for some reason prices appear fine (e.g. over 5000) when I fiddle with them, maybe there's something that needs to be initialized like products or something
![image](https://github.com/NebulaSS13/Nebula/assets/155900968/7d511f49-5176-4f7b-8538-161a1c01bf98)
two different vendors (first one fresh spawn, second one I took a power cell and then returned it, looks like initing more cells increases the price)
![image](https://github.com/NebulaSS13/Nebula/assets/155900968/754d39ed-ce6d-4c57-95df-280f9f72fb3b)
same behavior observed for vending/tool
![image](https://github.com/NebulaSS13/Nebula/assets/155900968/1172343e-0459-4c44-8e86-94aa3ea288cc)
but for some vendors like cigs its fine from the init
![image](https://github.com/NebulaSS13/Nebula/assets/155900968/9f4507c6-bee5-4935-8e4e-549f36416986)
and yeah pretty obvious that it happens only for non-paid vendors

will update if I find anything else

#### Client version, Server revision & Game ID

d70c25d1dbf65a4cf2290304bdd99006f8ad27b4 - stable - 2024-01-21

#### Issue bingo

- [x] Issue could be reproduced at least once
- [ ] Issue could be reproduced by different players
- [x] Issue could be reproduced in multiple rounds
- [x] Issue happened in a recent (less than 7 days ago) round
- [?] [Couldn't find an existing issue about this](https://github.com/NebulaSS13/Nebula/issues)

**Comment by MistakeNot4892** [comment]
The gun issue will be due to worth using gun vars directly and not checking firemodes.

Vendor issue will be due to vendors lazy-creating their atom contents.
