### ISSUE TITLE
Syringe in medical vendor has no chemical name

### ISSUE THREAD

**Issue by 43082ujfgrj** [NebulaSS13/Nebula#3626]
#### Description of issue
![image](https://github.com/NebulaSS13/Nebula/assets/155900968/476e1ed9-109a-410b-9b6d-611c7045659d)
medical vendor, syringe with spaceacl- antibiotics is named the same as a normal one

currently the only way to refill blood bags is the syringe which is very slow (not sure if intended)
also maybe consider adding them to autholathe along with stack healing items (gauze, etc)

idk if grouping issues is fine I will just update this one if I find more

#### Client version, Server revision & Game ID

d70c25d1dbf65a4cf2290304bdd99006f8ad27b4 - stable - 2024-01-21

#### Issue bingo

- [ ] Issue could be reproduced at least once
- [ ] Issue could be reproduced by different players
- [ ] Issue could be reproduced in multiple rounds
- [ ] Issue happened in a recent (less than 7 days ago) round
- [ ] [Couldn't find an existing issue about this](https://github.com/NebulaSS13/Nebula/issues)

**Comment by MistakeNot4892** [comment]
You're expected to refill blood bags with an IV drip.

**Comment by MistakeNot4892** [comment]
Also, one issue per issue unless they're directly related is preferred.

**Comment by MistakeNot4892** [comment]
Can confirm IV stand works fine, you hook yourself up to it and toggle the mode with a verb.
