### ISSUE TITLE
pizza box icon is broken

### ISSUE THREAD

**Issue by 43082ujfgrj** [NebulaSS13/Nebula#3627]
#### Description of issue
![image](https://github.com/NebulaSS13/Nebula/assets/155900968/4ff89b06-c09e-4802-9b3f-434d97534383)
![image](https://github.com/NebulaSS13/Nebula/assets/155900968/e5758d70-bc08-42a9-8410-170bd3238925)
no overlay

#### Client version, Server revision & Game ID

d70c25d1dbf65a4cf2290304bdd99006f8ad27b4 - stable - 2024-01-21

#### Issue bingo

- [x] Issue could be reproduced at least once
- [ ] Issue could be reproduced by different players
- [x] Issue could be reproduced in multiple rounds
- [x] Issue happened in a recent (less than 7 days ago) round
- [x] [Couldn't find an existing issue about this](https://github.com/NebulaSS13/Nebula/issues)

**Comment by MistakeNot4892** [comment]
Appearance plane issues, fixed in #3601
