### ISSUE TITLE
Acids melt beakers

### ISSUE THREAD

**Issue by Recon104** [NebulaSS13/Nebula#3735]
#### Description of issue

Advanced and Cryo beakers melt when used as a container for acids 

#### Difference between expected and actual behavior

Expected: Should carry the acid like a regular round start beaker
Actual behavior: Once sulphuric/hydro acid is placed in via dispenser the beaker dissolves.

#### Steps to reproduce
Spawn advanced or cryostasis beaker, place in chem dispenser, load up with acid.

#### Specific information for locating

Cryostasis Beaker, Advanced Beaker both from the RnD protoype section of the lathe

#### Length of time in which bug has been known to occur

Roughly a week

#### Client version, Server revision & Game ID

Date
2024-02-24
Branch
dev
Game ID
csq-bnPS
Runtime Version
514.1589
Compiler Version
514.1589
Revision
b5154d6449ac75a916ddef71c88cf66373ac52cd

#### Issue bingo

- [X] Issue could be reproduced at least once
- [X] Issue could be reproduced by different players
- [ ] Issue could be reproduced in multiple rounds
- [X] Issue happened in a recent (less than 7 days ago) round
- [X] [Couldn't find an existing issue about this](https://github.com/NebulaSS13/Nebula/issues)

**Comment by MistakeNot4892** [comment]
Swear I fixed this already. Will check if it made it to Scav.

**Comment by MistakeNot4892** [comment]
Fixed upstream.
