### ISSUE TITLE
Small mob sprites being weird

### ISSUE THREAD

**Issue by Recon104** [NebulaSS13/Nebula#3737]
#### Description of issue
I was told to "ticket bowties rendering on avians eyes"  and presumably a few other head pieces and other objects that previously looked fine on small mob species currently have various visual issues, particularly leaving the world sprite on top of their chest despite also showing the headgear properly

#### Difference between expected and actual behavior
When worn they should appear on the proper location on the body
Currently they are offset and some pieces of clothes leave a secondary sprite of the object on top of the mob

#### Steps to reproduce
Attach bowtie to a neo-avian I assume? Fedoras leave behind the secondary sprite on small mobs as well

#### Specific information for locating

Fedora
BowTie
Avian

#### Issue bingo

- [X] Issue could be reproduced at least once
- [X] Issue could be reproduced by different players
- [X] Issue could be reproduced in multiple rounds
- [X] Issue happened in a recent (less than 7 days ago) round
- [X] [Couldn't find an existing issue about this](https://github.com/NebulaSS13/Nebula/issues)

**Comment by MistakeNot4892** [comment]
Seems to occur only when a tie that needs to be offset is attached to clothing that does not apply offsets (a smock on an avian with a bowtie attached). 

Fedora issue was separate and has been fixed earlier.

**Comment by MistakeNot4892** [comment]
Should be fixed on stable.
