### ISSUE TITLE
513 Unicode Support

### ISSUE THREAD

**Issue by quardbreak** [NebulaSS13/Nebula#380]
#### Description of issue

Currently byond 513 is unstable. We waiting to stable version out.
We already can compile Nebula on 513 and even play, but there's already gameplay issues which need to be fixed.

We should investgate how to prepare Nebula work with unicode so we can get a right and full text support (Cyrillic for example).

#### Difference between expected and actual behavior

Nebula should have unicode support for different multilanguage downstreams.

Here's some info about how byond handle a text in 513 now:
http://www.byond.com/forum/post/2520672

**Comment by MistakeNot4892** [comment]
Moved to FR repo.
