### ISSUE TITLE
Facial hair is not properly cleared.

### ISSUE THREAD

**Issue by MistakeNot4892** [NebulaSS13/Nebula#3888]
#### Description of issue
Facial hair can render on the mob with the wrong colour even if cleared/reset.

#### Difference between expected and actual behavior
Facial hair should match your prefs.

#### Steps to reproduce
Select Tajaran in character generation, observe facial hair.

#### Specific information for locating
https://cdn.discordapp.com/attachments/1198609573657968684/1229662194203889724/taj.png?ex=66307f29&is=661e0a29&hm=8075629b70d1e0c5e43fa89f2125714aa6bc8f528c2a9938c051b21fbcbbc5ed&

#### Length of time in which bug has been known to occur
Likely since the accessories rewrite.

#### Client version, Server revision & Game ID
Client Version: 514
Server Revision: 6a93056e69b7b74bbcedd93157543f673f8251bc - staging - 2024-04-16
Game ID: ctg-aV9j
Current map: Ministation Zebra

#### Issue bingo

- [X] Issue could be reproduced at least once
- [X] Issue could be reproduced by different players
- [X] Issue could be reproduced in multiple rounds
- [X] Issue happened in a recent (less than 7 days ago) round
- [X] [Couldn't find an existing issue about this](https://github.com/NebulaSS13/Nebula/issues)

**Comment by MistakeNot4892** [comment]
Can't repro this on local staging, aiee.

**Comment by out-of-phaze** [comment]
Fixed in #3984.
