### ISSUE TITLE
Pill Bottles can not be put into Containters/Storage Such as Medkits and Tailbags

### ISSUE THREAD

**Issue by EvilDrCoconut** [NebulaSS13/Nebula#3982]
#### Description of issue
Pill bottle, whether empty or filled, can not be inserted into a storage container even if it started in one

#### Difference between expected and actual behavior
It should be able to be placed in the container, ie. Medkit, tailbags, duffelbag, etc.

But it is not going into any of these.

#### Steps to reproduce
Take any pill bottle, attempt to insert into object that can hold other objects such as medkit/tailbags/duffelbag

#### Specific information for locating

Pill Bottle -> Medkit (start as a doctor), no message outputted

#### Length of time in which bug has been known to occur

Found the bug within testing the staging branch of today (05/08/2024)

#### Client version, Server revision & Game ID

514.1589

#### Issue bingo

- [x] Issue could be reproduced at least once
- [x] Issue could be reproduced by different players
- [ ] Issue could be reproduced in multiple rounds
- [x] Issue happened in a recent (less than 7 days ago) round
- [x] [Couldn't find an existing issue about this](https://github.com/NebulaSS13/Nebula/issues)

**Comment by MistakeNot4892** [comment]
Fixed on staging.
