### ISSUE TITLE
Using up hint outside shows that you see the ceiling.

### ISSUE THREAD

**Issue by Greenjoe12345** [NebulaSS13/Nebula#3985]
#### Description of issue
When using the button in the top right, it will show "you can see the ceiling" when outside on the shadedhills map (and maybe other places?)

#### Difference between expected and actual behavior
You're outside, there isn't a ceiling. It should say something about being able to see the sky, or there being no ceiling.

#### Steps to reproduce
Use the up hint outside.

#### Issue bingo

- [x] Issue could be reproduced at least once
- [ ] Issue could be reproduced by different players
- [ ] Issue could be reproduced in multiple rounds
- [x] Issue happened in a recent (less than 7 days ago) round
- [x] [Couldn't find an existing issue about this](https://github.com/NebulaSS13/Nebula/issues)

**Comment by MistakeNot4892** [comment]
Implemented in #3988
