### ISSUE TITLE
small mobs picked up and used as items bug out

### ISSUE THREAD

**Issue by ZirconiumWit** [NebulaSS13/Nebula#40]
Description of issue
ADDENDUM:  This apparently happens when using small player mobs as tools or when a small player mob is placed in a backpack.  So.  There's that new information.  

Transferred from scavstation on Loaf's request:

picking yinglets up makes them permanantly turn when the person who picks them up turns. As in, the ying gets put down, and when the person who picked them up turns, the yinglet turns.

This is very aggravating as it leads to impromptu dances while you're injured and your injuries are being disregarded because it's possible for someone to force you to dance. I guess I've only noticed it when picked up on exoplanets. Also, are yinglets supposed to be retrievable when not on help intent? I've been picked up on harm intent. I don't know if that's supposed to be as easy as a simple click and an aggressive threat has been completely 100% pacified into a squeaky toy. This might be a feature now but that might be a good thing to restore.

Difference between expected and actual behavior

when a ying gets put down, they expect to have a little dignity, not be forced into thriller dances for the captain's amusement.

Steps to reproduce

I don't know if being on the exoplanet is necessary for this to happen, but both times it's happened, it happened on the exoplanet, and it endured to the ship when returning to the ship
Specific information for locating

in the brain of yinglets afflicted with dance fever. Please help
Length of time in which bug has been known to occur

at least a month now, it's happened on one other occasion. but I forgot to report it until now, 2/25/20. It's also only happened with Aura's female captain character, who loves to abuse this oddity.
Client version, Server revision & Game ID

logged out, dunno
Issue bingo

Issue could be reproduced at least once
[xI ssue could be reproduced by different players
Issue could be reproduced in multiple rounds
Issue happened in a recent (less than 7 days ago) round
Couldn't find an existing issue about this

**Comment by TheKnightofAura** [comment]
As a note, Winter did some testing, and confirmed it always happens after the yinglet is put into a bag.

**Comment by MistakeNot4892** [comment]
Applies to all held mobs when placed into storage items. Chasing down the cause atm.

**Comment by MistakeNot4892** [comment]
Holders do something funky with registering and unregistering movement to the holder loc, looks like maybe it doesn't unregister properly when the holder is destroyed. Testing a fix.

**Comment by MistakeNot4892** [comment]
No dice, still not clear on where it's registering to the owner dir set event or why it's not unregistering.
