### ISSUE TITLE
Sandals in the Shaded Hills loadout are not sandals.

### ISSUE THREAD

**Issue by liz-lavenza** [NebulaSS13/Nebula#4052]
#### Description of issue
![image](https://github.com/NebulaSS13/Nebula/assets/81447825/ec52f084-236c-4874-8b68-22c1f3d92db9)
These are not sandals.
![image](https://github.com/NebulaSS13/Nebula/assets/81447825/a2ade5f6-9945-42ef-a57f-16eb5f7b036d)

#### Difference between expected and actual behavior
They should be sandals.

#### Steps to reproduce
1. Load the Shaded Hills map.
2. Select sandals in the loadout.
3. Note that they are not sandals in the character preview.

#### Specific information for locating
```
/decl/loadout_option/fantasy/shoes/sandal
	name = "sandals"
	slot = slot_shoes_str
	available_materials = list(
		/decl/material/solid/organic/leather,
		/decl/material/solid/organic/wood,
		/decl/material/solid/organic/wood/mahogany,
		/decl/material/solid/organic/wood/maple,
		/decl/material/solid/organic/wood/ebony,
		/decl/material/solid/organic/wood/walnut
	)
```
`path` is not specified, so it's inherited.

#### Length of time in which bug has been known to occur
I don't know.

#### Client version, Server revision & Game ID
Client Version: 515
Server Revision: 2d50ca4c856c699237e82fe36ab325bb0d76c67d - dev - 2024-05-25
Game ID: ctU-amT1
Current map: Shaded Hills

#### Issue bingo

- [ ] Issue could be reproduced at least once
- [ ] Issue could be reproduced by different players
- [ ] Issue could be reproduced in multiple rounds
- [x] Issue happened in a recent (less than 7 days ago) round
- [x] [Couldn't find an existing issue about this](https://github.com/NebulaSS13/Nebula/issues)

**Comment by MistakeNot4892** [comment]
Fixed in #4060
