### ISSUE TITLE
Offal refuses to become soaked

### ISSUE THREAD

**Issue by Recon104** [NebulaSS13/Nebula#4075]
#### Description of issue

Attempting to soak the offal for tanning via barrel or bucket does not result in any change during the tanning process

#### Difference between expected and actual behavior
expected : Offal becomes soaked and allows the next step to becoming dried 
actual :Offal  will linger on the tanning rack if placed even after soaking it regardless of method; drying slabs of meat and veggies work fine though.

#### Steps to reproduce
butcher meat, obtain offal, clean offal off on table with knife, soak offal in either the barrel near the mining camp or using a bucket to soak it, then place on tanning rack

#### Specific information for locating

Raw cleaned offal
Bucket, Barrel
Water

#### Length of time in which bug has been known to occur

One day

#### Client version, Server revision & Game ID

Client Version: 515
Server Revision: 996ac692463405ee41e687d6e9b5c4524f3c8171 - dev - 2024-06-02
Game ID: ct1-a8Aj
Current map: Shaded Hills

#### Issue bingo

- [X] Issue could be reproduced at least once
- [ ] Issue could be reproduced by different players
- [X] Issue could be reproduced in multiple rounds
- [X] Issue happened in a recent (less than 7 days ago) round
- [X] [Couldn't find an existing issue about this](https://github.com/NebulaSS13/Nebula/issues)

**Comment by MistakeNot4892** [comment]
Struggling to repro this one - as discussed on Discord, the only way to soak stuff currently is via a fluid flow, so you need to fill a bowl or bucket with water, put the offal on the floor, and click the turf with the bowl/bucket. Offal and skin both work on Neb dev.

**Comment by MistakeNot4892** [comment]
Issue as it stands can't be reproduced but #4120 will implement the barrel and river interactions.
