### ISSUE TITLE
Wizard gamemode needs to be modpacked

### ISSUE THREAD

**Issue by out-of-phaze** [NebulaSS13/Nebula#4117]
Wizard needs to be modpacked.
- [ ] Wizard gamemode and special_role modpacked
- [ ] Wizard familiars modpacked
- [ ] `ability_master` merged into/replaced with `/datum/extension/abilities`
- [ ] Wizard spells modpacked
Deity and cult must be modpacked first, and spells will probably need to be overhauled. This is going to be the longest-term gamemode modularization, probably.

**Comment by MistakeNot4892** [comment]
'fixed' by #4606
