### ISSUE TITLE
Collected issues from Pyrelight test

### ISSUE THREAD

**Issue by MistakeNot4892** [NebulaSS13/Nebula#4191]
Posting this mainly for my own reference, so pardon the condensed ticket.

- ~~shrine needs salt, hoe, bowls/cups~~
- ~~area ambience is still using space sounds~~
- ~~days are way too short~~
- ~~weather needs to be weighted to clear conditions, most of round was spent in rain or hail~~
- ~~drakes cannot eat items held in mouth (dexterity check)~~
- ~~carrot sticks are white (chopped carrot is not)~~
- ~~broth is being created in 3u increments instead of 10/15u~~ pot was full
- ~~barrels in the rain don't refill (might not be an issue, barrels have a lid)~~ calling it not an issue due to need for barrels to process to refill like this
- ~~flowers should fit in ear slots~~ too complicated, todo
- ~~moving onto lit fires should check deliberate movement.~~
- ~~can't use a grab to position things on open space~~
- ~~dead hnoll still animate their tail wags~~

- tree shadows are off by 1 tile to the bottom left and leave baked in ambient lighting
- bandages and poultices have no failure message on use, and will attack even on help intent

**Comment by Greenjoe12345** [comment]
To add here,  drakes cannot eat small mobs such as mice whole.

**Comment by MistakeNot4892** [comment]
Going to sort out the rest of these via a list in Pyrelight, or open them as Neb issues.
