### ISSUE TITLE
putting symbols in 'me' statements causes weird syntax issues

### ISSUE THREAD

**Issue by ZirconiumWit** [NebulaSS13/Nebula#4201]
#### Description of issue
![image](https://github.com/user-attachments/assets/94c8b8cf-2cd8-4ca7-83d6-520874ba0584)
This is an example of putting quote marks into me statements, but I think I saw someone experience similar for ' half quote/apostrophes' 

#### Difference between expected and actual behavior
ideally the symbols would just appear when we put them into 'me' statmeents

#### Steps to reproduce
enter 'me' and then hit space and enter a statement with special symbols like " or '

#### Specific information for locating

In your text chat

#### Length of time in which bug has been known to occur

last couple games

#### Client version, Server revision & Game ID

Client Version: 515
Server Revision: 4af3f265d980627663f96ce1a32d889ffc411a21 - dev - 2024-07-14
Game ID: cuH-afFs
Current map: Shaded Hills

#### Issue bingo

- [x] Issue could be reproduced at least once
- [x] Issue could be reproduced by different players
- [x] Issue could be reproduced in multiple rounds
- [x] Issue happened in a recent (less than 7 days ago) round
- [x] [Couldn't find an existing issue about this](https://github.com/NebulaSS13/Nebula/issues)

**Comment by MistakeNot4892** [comment]
I think this is due to the html_encode() added to custom_emote() recently. Not completely sure how to resolve it.
