### ISSUE TITLE
Embedding happens way too much

### ISSUE THREAD

**Issue by Greenjoe12345** [NebulaSS13/Nebula#4202]
#### Description of issue
Blades embedding in mobs happens far too often

#### Difference between expected and actual behavior
I feel it should be a rare thing and not constantly stealing my knife from my hand and sticking it in a body

#### Steps to reproduce
Stab a mob.

#### Issue bingo

- [x] Issue could be reproduced at least once
- [x] Issue could be reproduced by different players
- [ ] Issue could be reproduced in multiple rounds
- [x] Issue happened in a recent (less than 7 days ago) round
- [x] [Couldn't find an existing issue about this](https://github.com/NebulaSS13/Nebula/issues)

**Comment by MistakeNot4892** [comment]
Should be fixed in #4204
