### ISSUE TITLE
Mad Magician Casts Fireball and Locks Mech Warrior Out Of House

### ISSUE THREAD

**Issue by Recon104** [NebulaSS13/Nebula#4234]
#### Description of issue
Wizards casting fireball and striking the exosuit or near the exosuit causes enough force to knock the user out of the suit and unable to climb back in if they lock the hatch(This might have relevance to anything that causes high knockback force like the fireball)

#### Difference between expected and actual behavior
Expected: Pilot buckled up for safety, and thus maybe gets rattled around but not blasted half way across the room out of his suit like a cartoon
Actual:See above

#### Steps to reproduce
Get blasted by a wizard while in an exosuit with fireball

#### Specific information for locating

Fireball 
Wizard
Exosuit

#### Length of time in which bug has been known to occur

Unknown

#### Client version, Server revision & Game ID

Client Version: 515
Server Revision: 42ac599488bc4202bda183761af732f1c12c42b5 - main - 2024-07-20
Game ID: cuN-dpRY
Current map: Tradepost Mollusc

#### Issue bingo

- [X] Issue could be reproduced at least once
- [ ] Issue could be reproduced by different players
- [ ] Issue could be reproduced in multiple rounds
- [X] Issue happened in a recent (less than 7 days ago) round
- [X] [Couldn't find an existing issue about this](https://github.com/NebulaSS13/Nebula/issues)

**Comment by MistakeNot4892** [comment]
I actually couldn't reproduce this on Neb stable. Are you sure it was fireball rather than the mental focus staff? Explosions only hit stuff on the turf, mental focus can potentially hit the mech, get passed to the pilot via rollcage, and throw them out of the mech as described.
