### ISSUE TITLE
Turrets/Sentry guns refused to acknowledge commands to not target specific crewmembers

### ISSUE THREAD

**Issue by Recon104** [NebulaSS13/Nebula#4264]
#### Description of issue
Turrets/Sentry gun control panel will accept but refuse to acknowledge commands to not target specific crewmembers, and attack all targets that enter the zone regardless of settings.

#### Difference between expected and actual behavior

Expected:Turrets stand down if Captain or command enters 
Actual: Captain suffers a heart attack from multiple stun lasers barraging him

#### Steps to reproduce
Open up Ministation
Go to AI room, try to mess with turret panel and then walk in

#### Specific information for locating

Ministation
Sentry gun or Turret
AI Room 
Satellite Station

#### Length of time in which bug has been known to occur

Unknown

#### Client version, Server revision & Game ID

Client Version: 515
Server Revision: 29922fe6daafc136b73ee608b0a8399042ea7b11 - main - 2024-07-27
Game ID: cuU-dEcu
Current map: Tradepost Mollusc

#### Issue bingo

- [X] Issue could be reproduced at least once
- [X] Issue could be reproduced by different players
- [X] Issue could be reproduced in multiple rounds
- [X] Issue happened in a recent (less than 7 days ago) round
- [X] [Couldn't find an existing issue about this](https://github.com/NebulaSS13/Nebula/issues)

**Comment by MistakeNot4892** [comment]
This appears to be a mapping issue, the turret controls need to be in the same area as the turrets.
