### ISSUE TITLE
Serpentid Movement Issue

### ISSUE THREAD

**Issue by tiramisuapimancer** [NebulaSS13/Nebula#4268]
#### Description of issue
Messing with serpentids on a friend's locally hosted server. The second I move over an open space tile I become unable to move by walking, completely frozen up, could not even change the direction I was facing by examine or by attempting movement. Move Down and Move Up commands did not work. I was able to move by climbing over railings and by clicking on ladders, but actually climbing Down a ladder did not work. Other players were able to move and drag my character.

#### Difference between expected and actual behavior
Should be able to freely move around instead of being locked up, including being able to move downward on open space tiles you are flying/hovering over.

#### Steps to reproduce
Be serpentid. Walk over an open tile. Attempt to move of your own intention.

#### Client version, Server revision & Game ID

Client Version: 515
Server Revision: 65f73b4969d3389861c23ede7f6b09e022377509 - dev - 2024-07-28
was on a friend's local
Current map: Tradeship Ocelot Alpha

#### Issue bingo

- [x] Issue could be reproduced at least once
- [ ] Issue could be reproduced by different players
- [ ] Issue could be reproduced in multiple rounds
- [x] Issue happened in a recent (less than 7 days ago) round
- [x] [Couldn't find an existing issue about this](https://github.com/NebulaSS13/Nebula/issues)

**Comment by tiramisuapimancer** [comment]
doesn't trigger with adherent flight

**Comment by tiramisuapimancer** [comment]
![image](https://github.com/user-attachments/assets/00791dc5-7ead-4e1c-8b74-4ed12fa2ffc1)
what

**Comment by MistakeNot4892** [comment]
Noting that serpentid just float indefinitely and can move up/down on openspace on stable, no apparent movement issues.

**Comment by MistakeNot4892** [comment]
There is a recursion in Enter() on dev that is causing moving to never be unset.

**Comment by MistakeNot4892** [comment]
Seems to have been the wonky serpentid can_overcome_gravity() block with the releated CanZPass() calls.
