### ISSUE TITLE
Elevator Gibs Upwards

### ISSUE THREAD

**Issue by tiramisuapimancer** [NebulaSS13/Nebula#4269]
#### Description of issue
Classic Baycode serpentid-eviscerating issue where elevators will gib things when moving upwards. Except it might be related to #4268 and issues with serpentids being unable to move or fall downwards. 

Notably my gibs were placed on the below z-level (on tiles they couldn't have reasonably "fallen" onto after my gibbing on the above Z), although I never myself moved to that below level and when I was ghosted due to the gibbing I remained on the tile and z level I had been on before gibbing.

#### Difference between expected and actual behavior
You should only be gibbed by moving floors if you are below them.

#### Steps to reproduce
Be floating on empty space above an elevator platform when it moves upwards. Become bits and pieces

#### Client version, Server revision & Game ID

Client Version: 515
Server Revision: 65f73b4969d3389861c23ede7f6b09e022377509 - dev - 2024-07-28
was on a friend's local
Current map: Tradeship Ocelot Alpha

#### Issue bingo

- [ ] Issue could be reproduced at least once
- [ ] Issue could be reproduced by different players
- [ ] Issue could be reproduced in multiple rounds
- [x] Issue happened in a recent (less than 7 days ago) round
- [x] [Couldn't find an existing issue about this](https://github.com/NebulaSS13/Nebula/issues)

**Comment by tiramisuapimancer** [comment]
floating adherent was not gibbed by upward elevator movement

**Comment by tiramisuapimancer** [comment]
reproducing issue proving difficult even using further serpentids

**Comment by MistakeNot4892** [comment]
```
	if(!moving_upwards)
		for(var/turf/T in destination)
			for(var/atom/movable/AM in T)
				if(isliving(AM))
					var/mob/living/M = AM
					M.gib()
				else if(AM.simulated)
					qdel(AM)
```
I suspect the elevator is not what gibbed you in your repro case, at least not directly. Might be some kind of weird input issue or delayed move up or down from fall() as a knock-on effect from serpentid flight being busted per your other issue.

**Comment by MistakeNot4892** [comment]
Going to close this for now as the issue as described is explicitly gated, I suspect this will be tied to whatever is going on with Serpentid movement in general. Will reopen if it recurs after that is fixed.
