### ISSUE TITLE
seeing items in inventory of person dragging you around with a grab over your own UI

### ISSUE THREAD

**Issue by sharah-za-fluffy** [NebulaSS13/Nebula#4290]
#### Description of issue
as the title says, you can see what i mean by the pistol mags
![image](https://github.com/user-attachments/assets/5a891083-1bd4-4374-83c9-87181505cbbc)

#### Difference between expected and actual behavior
I assume it's return of that liver ghost of scavstation

#### Steps to reproduce
get grabbed by someone who then removes items from you and keeps them and see if you still see said items on your end dispite not being on your person 

#### Length of time in which bug has been known to occur

found it today 

#### Client version, Server revision & Game ID

Client Version: 515
Server Revision: 575f296dcf33231decb550eb14c6beffc0ff6eb7 - main - 2024-07-31
Game ID: cuY-baRB

#### Issue bingo

- [x] Issue could be reproduced at least once
- [ ] Issue could be reproduced by different players
- [ ] Issue could be reproduced in multiple rounds
- [x] Issue happened in a recent (less than 7 days ago) round
- [x] [Couldn't find an existing issue about this](https://github.com/NebulaSS13/Nebula/issues)

**Comment by MistakeNot4892** [comment]
Repro details in #4296

**Comment by MistakeNot4892** [comment]
This has been fixed on staging, so I'm calling this wontfix as I am unwilling to go through and fix a system that will disappear when we merge staging to stable.
