### ISSUE TITLE
found way to repro storage datum bug

### ISSUE THREAD

**Issue by sharah-za-fluffy** [NebulaSS13/Nebula#4296]
#### Description of issue
I found out if you put a potato or other "fruit" in your backpack then click on it while it's in the backpack with a botany satchel it causes this to happen 
![image](https://github.com/user-attachments/assets/bae54b12-0a09-4217-ac0a-ac1ba1b0b1f4)

#### Difference between expected and actual behavior
no spooky ghost taters because I am lazy and just directly grab from a bag with a diffrent bag

#### Steps to reproduce
put some sort of plant in your backpack, then click on it with a botany satchel while the backpack is still open. I assume the same is true of ores and mining satchel

#### Specific information for locating

botany satchel, mining satchel, any plant or ore and any backpack including yinglet tailbags

#### Length of time in which bug has been known to occur

found it now

#### Client version, Server revision & Game ID

Date
2024-08-03
Branch
main
Game ID
cu1-dvvE
Runtime Version
514.1589
Compiler Version
514.1589
Revision
575f296dcf33231decb550eb14c6beffc0ff6eb7

#### Issue bingo

- [x] Issue could be reproduced at least once
- [ ] Issue could be reproduced by different players
- [ ] Issue could be reproduced in multiple rounds
- [x] Issue happened in a recent (less than 7 days ago) round
- [ ] [Couldn't find an existing issue about this](https://github.com/NebulaSS13/Nebula/issues)

**Comment by MistakeNot4892** [comment]
Curious if this still happens on staging/dev given the big storage rewrite.
