### ISSUE TITLE
Cyborgs / robots can grab+pull objects but then can't put them down.

### ISSUE THREAD

**Issue by SodiumShine** [NebulaSS13/Nebula#431]
Issue I had, was playing as a robot, specifically an engineering robot. Could ctrl+click objects to pull them around but there wasn't a way to let go. (Moving into an object to push it would cause the object to be let go but obviously this doesn't work with small items)

**Comment by MistakeNot4892** [comment]
Currently they have to use the Home or End hotkey. Adding a UI element is on my todo.
