### ISSUE TITLE
Water+Potassium mixture doesnt properly blow up

### ISSUE THREAD

**Issue by Recon104** [NebulaSS13/Nebula#4319]
#### Description of issue
Water+Potassium mixture doesnt properly blow up when combined; noise and special effect is created but no explosive

#### Difference between expected and actual behavior

Expected: Explosion is generated
Actual:See above

#### Steps to reproduce

Combine water+potass in large quantities or drink it

#### Specific information for locating

water
potassium

#### Length of time in which bug has been known to occur

Unsure

#### Client version, Server revision & Game ID

Client Version: 515
Server Revision: cd52d9ef96bc9a783488c509caea52bb66565b24 - main - 2024-08-10
Game ID: cu8-aCU9
Current map: Tradepost Mollusc

#### Issue bingo

- [X] Issue could be reproduced at least once
- [X] Issue could be reproduced by different players
- [X] Issue could be reproduced in multiple rounds
- [X] Issue happened in a recent (less than 7 days ago) round
- [X] [Couldn't find an existing issue about this](https://github.com/NebulaSS13/Nebula/issues)

**Comment by MistakeNot4892** [comment]
![image](https://github.com/user-attachments/assets/6d5252d1-a0bb-4bb6-8187-33ffdd0387d6)

60u of each. You might just not be using enough?

**Comment by MistakeNot4892** [comment]
Per convo on Discord, going to close this for now, feel free to reopen if there are issues with grenades or there are still no explosions even with higher volumes.
