### ISSUE TITLE
glass pane duplication

### ISSUE THREAD

**Issue by sharah-za-fluffy** [NebulaSS13/Nebula#4322]
#### Description of issue
I found out that if you use screw driver to loosen a full block window then deconstruct with a wrench you get 4 panes of glass when doing so dispite it only costing one pane to build said window in first place

#### Difference between expected and actual behavior
I should not be able to quadruple our glass supply this way 

#### Steps to reproduce
build a full tile window or use screwdriver to loosen existing one then use wrench on it to deconstruct and note the materials you get for doing so 

#### Specific information for locating

full tile window

#### Length of time in which bug has been known to occur

realized it just now after noting how little glass it takes to actually make a window

#### Client version, Server revision & Game ID

Client Version: 515
Server Revision: cd52d9ef96bc9a783488c509caea52bb66565b24 - main - 2024-08-10
Game ID: cu8-cW9F

#### Issue bingo

- [ ] Issue could be reproduced at least once
- [ ] Issue could be reproduced by different players
- [ ] Issue could be reproduced in multiple rounds
- [x] Issue happened in a recent (less than 7 days ago) round
- [x] [Couldn't find an existing issue about this](https://github.com/NebulaSS13/Nebula/issues)

**Comment by MistakeNot4892** [comment]
Fixed in #4367
