### ISSUE TITLE
codex lacks info about fixing prostetic faults and possble unfixable faults 

### ISSUE THREAD

**Issue by sharah-za-fluffy** [NebulaSS13/Nebula#4333]
#### Description of issue
![image](https://github.com/user-attachments/assets/0e6c2082-055c-4914-a8f8-0d0a8ed86c43)
no info in how to fix faults and it's possble it's not even possble to fix them right now

#### Difference between expected and actual behavior
robot tail squealing is annoying and I want it to be fixed but apperently it's not possble

#### Steps to reproduce
get a prostetic fault to happen
look it up in codex
see that it says nothing to use

#### Specific information for locating

prosthetic limbs

#### Length of time in which bug has been known to occur

found it now granted moonin says it's been a thing for a while and people keep failing to ticket it

#### Client version, Server revision & Game ID

Client Version: 515
Server Revision: cd52d9ef96bc9a783488c509caea52bb66565b24 - main - 2024-08-11
Game ID: cu9-dKbg
Current map: Tradepost Mollusc

#### Issue bingo

- [ ] Issue could be reproduced at least once
- [ ] Issue could be reproduced by different players
- [ ] Issue could be reproduced in multiple rounds
- [x] Issue happened in a recent (less than 7 days ago) round
- [x] [Couldn't find an existing issue about this](https://github.com/NebulaSS13/Nebula/issues)

**Comment by MistakeNot4892** [comment]
Fairly sure it's nanopaste ftr.
