### ISSUE TITLE
The Shaded Hills inn kitchen has a giant hole in the floor

### ISSUE THREAD

**Issue by out-of-phaze** [NebulaSS13/Nebula#4351]
the placement of the kitchen is set up for the Pyrelight inn cellar but we don't have that upstream (and even downstream it cuts a hole through the wall). the old sewers upstream instead have a misaligned staircase that results in a 3-tile long gash through the floor and wall of the kitchen.

**Comment by MistakeNot4892** [comment]
Fixed in #4365
