### ISSUE TITLE
Cannot use minihoe for weeds unless on harm intent

### ISSUE THREAD

**Issue by out-of-phaze** [NebulaSS13/Nebula#4389]
#### Description of issue
`/obj/item/tool/hoe/mini` has `edge = TRUE` and `w_class < ITEM_SIZE_NORMAL` and so it takes a sample instead of weeding the tray, unless you are on harm intent.
This is because `/obj/item/tool/hoe` adds `edge = TRUE`; prior to minihoes being made a tool subtype it didn't have that.

**Comment by MistakeNot4892** [comment]
Should taking a sample be made an alt interaction instead?

**Comment by out-of-phaze** [comment]
> Should taking a sample be made an alt interaction instead?

that could be a good solution tbh yeah
