### ISSUE TITLE
Sampling plants results in seed packets on Shaded Hills

### ISSUE THREAD

**Issue by out-of-phaze** [NebulaSS13/Nebula#4390]
#### Description of issue
Sampling plants with a small edged object results in seed packets on Shaded Hills. Maybe a map datum should specify a "default seed packet type" or similar? Then we can make things that create seeds just use that...?

#### Difference between expected and actual behavior
It should give you extracted seeds rather than seed packets, given the tech level.

**Comment by MistakeNot4892** [comment]
Fixed on dev, I just made sampling always give the unpackaged seeds, since it doesn't make much sense for a package to appear ex nihilo regardless of tech level.
