### ISSUE TITLE
SWAT suit is unpressurized 

### ISSUE THREAD

**Issue by Recon104** [NebulaSS13/Nebula#4392]
#### Description of issue

Attempting to go into space while wearing the blood red helmet and the SWAT suit causes pressure and freezing damage

#### Difference between expected and actual behavior

Should be as any other voidsuit

#### Steps to reproduce

Wear suit then go into space

#### Specific information for locating

Blood red helmet
Swat suit

#### Length of time in which bug has been known to occur

Several weeks 

#### Client version, Server revision & Game ID

Client Version: 515
Server Revision: 04e095cc8da9a9fa124d63a9a3488b22b876df90 - main - 2024-08-22
Game ID: cvk-bcQL
Current map: Tradepost Mollusc

#### Issue bingo

- [X] Issue could be reproduced at least once
- [ ] Issue could be reproduced by different players
- [X] Issue could be reproduced in multiple rounds
- [X] Issue happened in a recent (less than 7 days ago) round
- [X] [Couldn't find an existing issue about this](https://github.com/NebulaSS13/Nebula/issues)

**Comment by MistakeNot4892** [comment]
Where did they get the suit? Are you sure it wasn't a replica?

**Comment by MistakeNot4892** [comment]
The SWAT suit does not cover hands, and the pressure checking is all or nothing. Not really a bug, the SWAT suit icon doesn't have gloves so I suspect it wasn't intended to be space capable.
