### ISSUE TITLE
Graphite does not smelt and is instead ejected by smelter (possbly other ores too) 

### ISSUE THREAD

**Issue by sharah-za-fluffy** [NebulaSS13/Nebula#4418]
#### Description of issue
smelters just spit out graphite when fed into machine instead of being processed into carbon for steel smelting. also yoki says some other ores do the same thing but didn't specify WHAT ones (note, this was on scav so apologies if this isn't actually true of nebula in general) 

#### Difference between expected and actual behavior
I just want to make steel/plasteel and not wonder where I get carbon because graphite no worky

#### Steps to reproduce
mine graphite and other ores
feed them into smelter
see if they are actually used and not just rejected by smelter 

#### Specific information for locating

electric smelter, graphite

#### Length of time in which bug has been known to occur

found it today but yoki claims it has been issue with other ores for some time now 

#### Client version, Server revision & Game ID

Date
2024-08-31
Branch
main
Game ID
cvt-ayGj
Runtime Version
514.1589
Compiler Version
514.1589
Revision
8b3f2776b67f8d1dde4137190ff35b4befad9c46

#### Issue bingo

- [ ] Issue could be reproduced at least once
- [ ] Issue could be reproduced by different players
- [ ] Issue could be reproduced in multiple rounds
- [x] Issue happened in a recent (less than 7 days ago) round
- [x] [Couldn't find an existing issue about this](https://github.com/NebulaSS13/Nebula/issues)

**Comment by out-of-phaze** [comment]
fixed on dev in this commit https://github.com/NebulaSS13/Nebula/commit/86164c0b89cbdb0f0091f6328f6ce0ebfdd17084

**Comment by MistakeNot4892** [comment]
Should be fixed on stable.
