### ISSUE TITLE
batch crafting of cones and other unstackables causes waste of material 

### ISSUE THREAD

**Issue by sharah-za-fluffy** [NebulaSS13/Nebula#4458]
#### Description of issue
I attempted to make 24 warning cones from 24 plastic sheets and only got one 

#### Difference between expected and actual behavior
either I should not be allowed to attempt to batch craft cones and other unstackable objects or I should just get like 23 cones under me after making the one

#### Steps to reproduce
get a lot of materials, click a crafting amount more than 1 (for example 5x) and watch what happens

#### Specific information for locating

construction skill menu

#### Length of time in which bug has been known to occur

since a while but I am reporting it now to stop waste of more important materials in the future 

#### Client version, Server revision & Game ID

Server Revision: 5c689e810a0ec8bd3dd7c6030d0c823f0ea5e852 - main - 2024-09-14

#### Issue bingo

- [x] Issue could be reproduced at least once
- [ ] Issue could be reproduced by different players
- [ ] Issue could be reproduced in multiple rounds
- [x] Issue happened in a recent (less than 7 days ago) round
- [x] [Couldn't find an existing issue about this](https://github.com/NebulaSS13/Nebula/issues)

**Comment by MistakeNot4892** [comment]
![image](https://github.com/user-attachments/assets/ffc746f3-eb74-4627-bc58-281fb2687d87)
Could you do me a favour and check if this is reproducable on Scav this weekend? I can't repro it locally on stable, you can't multicraft cones.

**Comment by MistakeNot4892** [comment]
Never mind, reproduced on stable, I had dev checked out.
