### ISSUE TITLE
steel combi-knife only works as knife, the screwdriver bits are useless. 

### ISSUE THREAD

**Issue by markoatonc** [NebulaSS13/Nebula#4513]
#### Description of issue
Despite the description saying:
```
 That's a steel combi-knife. It is a small item.

A small, colourable, multi-purpose folding knife.
It looks like a mediocre crowbar, a mediocre screwdriver, mediocre wirecutters, and a mediocre hatchet.
```
only the knife part seems to work, and only for stabbing things. The screwdriver parts when unfolded do not seem to work as screwdriver, and none of the parts work as crowbar. 

#### Difference between expected and actual behavior

as per description it should be able to un-screw simple panels and stuff, but it doesn't. It does not even seem able to interact with anything aside from stabbing things. (I don't get any feedback or text in log, and the character doesn't seem to even attempt to use it.)

#### Steps to reproduce

Just try to use it as you would any other screwdriver.

#### Specific information for locating

  That's a steel combi-knife. It is a small item.

A small, colourable, multi-purpose folding knife.
It looks like a mediocre crowbar, a mediocre screwdriver, mediocre wirecutters, and a mediocre hatchet.

#### Length of time in which bug has been known to occur
I only started playing three days ago, and tried to use it for two, but it didn't work at all for me. (tried clearing cache)

#### Client version, Server revision & Game ID
Client Version: 515
Server Revision: eb6d8da69286af915d6e7d4ad6f80b2c5e564472 - main - 2024-10-07
Game ID: cv4-biNh

#### Issue bingo

- [x] Issue could be reproduced at least once
- [x] Issue could be reproduced by different players
- [x] Issue could be reproduced in multiple rounds
- [x] Issue happened in a recent (less than 7 days ago) round
- [x] [Couldn't find an existing issue about this](https://github.com/NebulaSS13/Nebula/issues)

**Comment by MistakeNot4892** [comment]
Just noting that the problem revision is Scav's main branch, so our stable branch.
