### ISSUE TITLE
Can't scoop from a bowl of soup with a spoon

### ISSUE THREAD

**Issue by noelle-lavenza** [NebulaSS13/Nebula#4519]
#### Description of issue
Clicking a bowl of soup with a spoon causes absolutely no reagent transfer.

#### Difference between expected and actual behavior
You should be able to sip soup from a bowl using a spoon, but can't.

#### Steps to reproduce
1. Put soup in handmade (wood or pottery) bowl.
2. Use spoon on it.
3. Nothing happens.

#### Length of time in which bug has been known to occur
I assume since the bowl was added.

#### Client version, Server revision & Game ID
Latest dev.

#### Issue bingo

- [x] Issue could be reproduced at least once
- [ ] Issue could be reproduced by different players
- [x] Issue could be reproduced in multiple rounds
- [x] Issue happened in a recent (less than 7 days ago) round
- [x] [Couldn't find an existing issue about this](https://github.com/NebulaSS13/Nebula/issues)

**Comment by MistakeNot4892** [comment]
Fixed/implemented in #4344
