### ISSUE TITLE
small mobs cannot wear chameleon suit dispite it being able to disguise itself as small mob clothing

### ISSUE THREAD

**Issue by sharah-za-fluffy** [NebulaSS13/Nebula#4553]
#### Description of issue
chameleon suit can be disguised as a small mob exclusive clothing like yinglet and avian clothing but only humans can wear the suit in question even when set to said small mob disguise

#### Difference between expected and actual behavior
I should be able to play pretty dress up as a bird thing, whenever oops or not

#### Steps to reproduce
be either traitor or science, (build a coilgun to feed to analyzer to break into esoteric tech)
if science go up into esoteric tech until the really expensive "backpack" is printable, then make it and take the chameleon equipment out of the bag and get the suit and turn it to a small mob clothing, then as a small mob species try to wear it.

#### Specific information for locating

chameleon backpack and all the items it includes 

#### Length of time in which bug has been known to occur

found it today trying to use my newfound traitor science gained by coil gun to disguise myself as the vimmy version of scavstation's yinglet "flex suit" 

#### Client version, Server revision & Game ID

Revision: ScavStation
Date
2024-11-09
Branch
main
Game ID
cwB-dyDp
Runtime Version
515.1643
Compiler Version
515.1643
Revision
cd6051e4e77d6bbb801076b6b9c5c559843b0102

#### Issue bingo

- [ ] Issue could be reproduced at least once
- [ ] Issue could be reproduced by different players
- [ ] Issue could be reproduced in multiple rounds
- [x] Issue happened in a recent (less than 7 days ago) round
- [x] [Couldn't find an existing issue about this](https://github.com/NebulaSS13/Nebula/issues)

**Comment by MistakeNot4892** [comment]
Just need to clear bodytype equip flags on the cham clothes, or have it copy them from the duplicated clothing.
