### ISSUE TITLE
You can endlessly add water to containers like Janitorial Cart. 

### ISSUE THREAD

**Issue by markoatonc** [NebulaSS13/Nebula#4560]
#### Description of issue

I got the janicart filled with water, but once it hit 179.99 units of liquid, that extra 0.01 vanishes. So you can keep adding it, and it keeps vanishing. it does remove 0.01 units from the bucket, but doesn't seem to add it to the cart. After further testing the same thing sometimes happens when adding water to the bucket from tank. As you can see on the logs attached below there seem to be happening something weird with the fractions of units.
It might be happening with other containers too, haven't had time for more tests. might update the ticket If I find other containers do it too.
#### Difference between expected and actual behavior
It should fill the Cart to full. 

#### Steps to reproduce
1.Fill bucket from water tank
2. pour the contents into Janitor Cart. 
3. refill the bucket
4. Pour it into the cart, Once it is almost full, it allows you to keep adding 0.01 units endlessly

I 

#### Specific information for locating
![image](https://github.com/user-attachments/assets/ecb8407c-2af6-4de5-8b1e-42b5f9493af3)
![image](https://github.com/user-attachments/assets/3dec2126-e2cd-4e7d-8683-2466713e32ac)

#### Length of time in which bug has been known to occur
I only noticed it Today, which is the first time I played on the map with the Janicart in it since server changed version.

#### Client version, Server revision & Game ID
Client Version: 515
Server Revision: 1976ade77218700d626522073d596d9963f5b37b - dev - 2024-11-11
Game ID: cwD-a6Ti
Current map: Tradepost Mollusc

#### Issue bingo

- [x] Issue could be reproduced at least once
- [x] Issue could be reproduced by different players
- [x] Issue could be reproduced in multiple rounds
- [x] Issue happened in a recent (less than 7 days ago) round
- [x] [Couldn't find an existing issue about this](https://github.com/NebulaSS13/Nebula/issues)

**Comment by MistakeNot4892** [comment]
Noting this is Scav dev, so Neb staging. I suspect this was fixed by Liz's reagent quantize PR. Will need to retest when staging is updated from dev.

**Comment by MistakeNot4892** [comment]
Fixed on staging.
