### ISSUE TITLE
Defib and some two handed equipment cant be used as a small mob

### ISSUE THREAD

**Issue by Recon104** [NebulaSS13/Nebula#4566]
#### Description of issue
Neo avians and other(**YINGLET**) cant use the defib and similar items even with open hands

#### Difference between expected and actual behavior
Should be able to defib people as a neo avian or other small mob

#### Steps to reproduce
Put on defib then try to defib a mob as a small creature

#### Specific information for locating

Auto-Resuscitator 

#### Length of time in which bug has been known to occur

One week

#### Client version, Server revision & Game ID

Client Version: 515
Server Revision: eb228b8170624b0a81d84a78afe5d6cad551a696 - dev - 2024-11-16
Game ID: cwI-cSDy
Current map: Tradepost Mollusc

#### Issue bingo

- [X] Issue could be reproduced at least once
- [X] Issue could be reproduced by different players
- [X] Issue could be reproduced in multiple rounds
- [X] Issue happened in a recent (less than 7 days ago) round
- [X] [Couldn't find an existing issue about this](https://github.com/NebulaSS13/Nebula/issues)

**Comment by MistakeNot4892** [comment]
What's meant by 'similar items'?
