### ISSUE TITLE
Cannot close "Robco Tool Maker" machine's access panel

### ISSUE THREAD

**Issue by MistakeNot4892** [NebulaSS13/Nebula#4571]
Copied from https://github.com/ScavStation/ScavStation/issues/1113

#### Description of issue
Trying to use a screwdriver on the vending machine on Help intent causes the player to deposit the tool into the machine.  Using a screwdriver on a closed machine with Grab intent allows the player to open it, but not close it.  Using a screwdriver on an open machine in any non-Help intent leads to the player attacking the circuit board, as shown by the message "The circuitboard (vending machine) has been hit by [playername] with the screwdriver."  This happens on Grab, Disarm, and Harm.  On Help, the player still deposits the screwdriver into the machine despite it still having the maintenance hatch open.

#### Difference between expected and actual behavior
Using a screwdriver on a vending machine in Grab/Disarm intent should close the maintenance hatch.  This is how it worked previously.  I was unable to find a way to close the maintenance hatch, rendering the machine unusable.

#### Steps to reproduce
Equip a screwdriver and change to Grab intent.  Use screwdriver on "Robco Tool Maker" or any vending machine that accepts a screwdriver.  The maintenance hatch will open.  The player now cannot close the maintenance hatch with a screwdriver on any intent.

#### Specific information for locating

Robco Tool Maker (discovered with the one in Engineering)

#### Length of time in which bug has been known to occur

Discovered 11/12/2024 at about 10:30 PM Central time.  

#### Client version, Server revision & Game ID

Client Version: 515
Server Revision: 1976ade77218700d626522073d596d9963f5b37b - dev - 2024-11-11
Game ID: cwD-a6Ti
Current map: Tradepost Mollusc

#### Issue bingo

- [x] Issue could be reproduced at least once
- [ ] Issue could be reproduced by different players
- [x] Issue could be reproduced in multiple rounds
- [x] Issue happened in a recent (less than 7 days ago) round
- [x] [Couldn't find an existing issue about this](https://github.com/ScavStation/ScavStation/issues)

**Comment by noelle-lavenza** [comment]
~~This is likely the same as #4573, this affects all machines with access requirements, I think.~~

**Comment by MistakeNot4892** [comment]
This one is specific to the Robco vendor as it stocks screwdrivers. Other vendors can be screwdrivered fine.

**Comment by noelle-lavenza** [comment]
Oh, I didn't read closely enough, whoops.
