### ISSUE TITLE
Brain damage seems to be perma

### ISSUE THREAD

**Issue by Recon104** [NebulaSS13/Nebula#4590]
#### Description of issue
I think this is relating to a previous issue with brains not being capable of fully healing with or without medicine, but with seemingly no injuries I kept getting brain damage that came back everytime neuro ran out.

#### Difference between expected and actual behavior
Should recover the brain fully when no injuries are causing it
Currently racks up brain damage for some reason

#### Steps to reproduce
Walk off the top floor down the elevator shaft as a neo avian and obliterate every single body part and get damage everywhere. Get surgery and survive, and obtain free brain damage over and over.

#### Specific information for locating

Neuroanneler
Brain

#### Length of time in which bug has been known to occur

Unsure, since we merged to staging probably

#### Client version, Server revision & Game ID

Client Version: 515
Server Revision: db8bd2dc81b2282378fb43076f5089a91f23cfe7 - dev - 2024-11-30
Game ID: cwW-cScz
Current map: Tradepost Mollusc

#### Issue bingo

- [X] Issue could be reproduced at least once
- [ ] Issue could be reproduced by different players
- [X] Issue could be reproduced in multiple rounds
- [X] Issue happened in a recent (less than 7 days ago) round
- [X] [Couldn't find an existing issue about this](https://github.com/NebulaSS13/Nebula/issues)

**Comment by MistakeNot4892** [comment]
This seems more like something is causing brain damage to accumulate. Did you have any injuries/infections?

**Comment by MistakeNot4892** [comment]
Other possible causes could be blood loss.

**Comment by MistakeNot4892** [comment]
I suspect this may be related to the issue with meat causing organ damage, but I'm not sure. Couldn't reproduce it on Neb - feel free to reopen with more specific repro conditions if possible.
