### ISSUE TITLE
Binary Key Unable to Speak

### ISSUE THREAD

**Issue by biscuitWizard** [NebulaSS13/Nebula#495]
#### Description of issue
Cannot talk on binary keys installed in headsets.

#### Issue bingo

- [x] Issue could be reproduced at least once
- [x] Issue could be reproduced by different players
- [x] Issue could be reproduced in multiple rounds
- [x] Issue happened in a recent (less than 7 days ago) round
- [x] [Couldn't find an existing issue about this](https://github.com/NebulaSS13/Nebula/issues)

**Comment by MistakeNot4892** [comment]
Took me a bit to work this out, it's not very well signposted. You speak on Binary with the 'special' radio key, default `:+`, rather than `,b` or `:b`. Works fine on current dev.
