### ISSUE TITLE
sunglasses don't seem to work to protect the eyes

### ISSUE THREAD

**Issue by ZirconiumWit** [NebulaSS13/Nebula#560]
#### Description of issue
HUD sunglasses protect, but regular sunglasses don't seem to do much of anything when it comes to flashes of light.

#### Difference between expected and actual behavior
I don't expect them to protect me from welding torches, but a handheld flash or flashbang?  Yeah, I expect at least some protection.

#### Steps to reproduce
Have a friend grab a flash, throw on your sunglasses, and pretend you're both back at the security training academy.  You know what to do.  

#### Specific information for locating

Preferably on your face, when you're wearing regular plain ol' sunglasses.

#### Length of time in which bug has been known to occur

Today only, 5/29/20

#### Client version, Server revision & Game ID

Client Version: 512
Server Revision: a0ff7475cedd2411ee5eacad38eed162be6e0c98 - dev - 2020-05-29
Game ID: b7o-bc8l
Current map: Ministation Zebra

#### Issue bingo

- [x] Issue could be reproduced at least once
- [ ] Issue could be reproduced by different players
- [ ] Issue could be reproduced in multiple rounds
- [x] Issue happened in a recent (less than 7 days ago) round
- [x] [Couldn't find an existing issue about this](https://github.com/NebulaSS13/Nebula/issues)

**Comment by MistakeNot4892** [comment]
Investigated - basic sunglasses are `FLASH_PROTECTION_MINOR` and make flashes blur your vision but not blind you, the large sunglasses and sechud are `FLASH_PROTECTION_MODERATE` which entirely blocks the flash.
