### ISSUE TITLE
Overmap Events Do Not Trigger

### ISSUE THREAD

**Issue by biscuitWizard** [NebulaSS13/Nebula#576]
#### Description of issue
Sector events/effects need to be fixed to actually trigger.

#### Issue bingo

- [x] Issue could be reproduced at least once
- [x] Issue could be reproduced by different players
- [x] Issue could be reproduced in multiple rounds
- [x] Issue happened in a recent (less than 7 days ago) round
- [x] [Couldn't find an existing issue about this](https://github.com/NebulaSS13/Nebula/issues)

**Comment by MistakeNot4892** [comment]
Can't reproduce on current dev:
![image](https://user-images.githubusercontent.com/2468979/87806915-f0482480-c89a-11ea-80ee-2fd85f202679.png)
