### ISSUE TITLE
Exploration Shuttle unable to land on planets.

### ISSUE THREAD

**Issue by SodiumShine** [NebulaSS13/Nebula#58]
Specifically using the bearcat exploration shuttle, if that matters.

Sometimes, when attempting to move the shuttle to a nearby planet, the destination does not appear available on the console listing. It provides no information regarding the reason, but I am told it is likely due to there not being enough open turf for the shuttle to land. 

I don't know if this would be considered a bug or not. Perhaps it is a feature request.
The shuttle should force itself into position, deleting things where it would go if that's the case.

![image](https://user-images.githubusercontent.com/4461697/75510401-fdc15700-5a3e-11ea-9b22-92f689ec2898.png)

**Comment by afterthought2** [comment]
The landmark already clears an area. This sounds like either the shuttle is too big, the landmark inside the shuttle is too off-center, or stuff was moved into a blocking position on the planet.

**Comment by SodiumShine** [comment]
Shit. Guess I need to do some extra testing.

**Comment by SodiumShine** [comment]
Okay yeah it was just that the landmark in the shuttle was on the nose of the shuttle, which is longer than 10 turfs.
