### ISSUE TITLE
Planet atmos gen picks too funny reagents

### ISSUE THREAD

**Issue by comma** [NebulaSS13/Nebula#583]
#### Description of issue
![Upt1UEJ](https://user-images.githubusercontent.com/1300258/83942824-24461980-a808-11ea-83c0-91e883882ae1.png)
Planetgetn picks random chems instead of just gasses.

#### Difference between expected and actual behavior
Expected to have gases
Actually have sublimated watermelon juice

#### Steps to reproduce
Start round
Go to planet
Scan air

#### Length of time in which bug has been known to occur

Since reagent-matter merge

#### Issue bingo

- [ ] Issue could be reproduced at least once
- [ ] Issue could be reproduced by different players
- [ ] Issue could be reproduced in multiple rounds
- [ ] Issue happened in a recent (less than 7 days ago) round
- [ ] [Couldn't find an existing issue about this](https://github.com/NebulaSS13/Nebula/issues)

**Comment by MistakeNot4892** [comment]
Should have been fixed by #608
