### ISSUE TITLE
Steel supports cannot support steel cladding

### ISSUE THREAD

**Issue by TheKnightofAura** [NebulaSS13/Nebula#597]
As per title. If you dissassemble a steel wall, you cannot re-build it with the parts you got from it. The steel guts cannot support the steel wall. The steel guts CAN support fur walls, however, but not bone.

**Comment by TheKnightofAura** [comment]
Plasteel supports likewise cannot support steel cladding, leading me to further believe that any fabric will work, and any solid material won't.

**Comment by MistakeNot4892** [comment]
I'll do a values pass after the big materials PR that is currently open.
