### ISSUE TITLE
Fabricator design lists are empty

### ISSUE THREAD

**Issue by ZirconiumWit** [NebulaSS13/Nebula#600]
#### Description of issue
Equipment that constructs items based on schematics/lists seem to be lacking all schematics.  Examples of this equipment include autolathe, pipe dispenser, circuit imprinter, and book binder.  Attempting to utilize this equipment shows an unoccupied list with no options.

(Edit:  Immediately after posting this I realize I don't know what these pieces of equipment draw from so 'schematic-based' in title is probably inappropriate/wrong, but they all seem to have very similar interfaces/menus)

#### Difference between expected and actual behavior
Expected:  Equipment designed to build can build
Actual:  Not so much

#### Steps to reproduce
approach an autolathe, pipe dispenser, circuit imprinter, book binder, or other equipment that pulls construction options from a list and attempt to use it

#### Specific information for locating

See above

#### Length of time in which bug has been known to occur

Several weeks, I waited way too long to report.  

#### Client version, Server revision & Game ID

Client Version: 512
Server Revision: 2055c87cd3d9fcd01f0fab9f56bc6997770a1714 - dev - 2020-06-08
Game ID: b7y-aP5m
Current map: Tradeship Ivenmoth

#### Issue bingo

- [x] Issue could be reproduced at least once
- [x] Issue could be reproduced by different players
- [x] Issue could be reproduced in multiple rounds
- [x] Issue happened in a recent (less than 7 days ago) round
- [x] [Couldn't find an existing issue about this](https://github.com/NebulaSS13/Nebula/issues)

**Comment by comma** [comment]
Fixed by #618
