### ISSUE TITLE
assorted icon issues

### ISSUE THREAD

**Issue by ZirconiumWit** [NebulaSS13/Nebula#613]
#### Description of issue
Double barreled shotgun (/obj/item/gun/projectile/shotgun/doublebarrel) + 
biohazard suit (/obj/item/clothing/suit/bio_suit/scientist ) + 
‘the gun’ (/obj/item/gun/projectile)  + 
'the dart gun' /obj/item/gun/projectile/dartgun +
Pirate’s laser cutlass when ACTIVATED (/obj/item/melee/energy/sword/pirate ) all bugged when held or worn – visible when not viewed in inventory, but not visible in inventory icons.  Probably more, I don’t quite know what ties all these together besides several are guns

-related – wirecutter handle appears in inventory icon, but wirecutter head does not.
  Kabobs made in oven have only the metal kabob handle, but no visible food contents.  
Teleportation pad (/obj/machinery/merchant_pad) has no on-ground icon, but is visible in a right-click menu.

Similarly, on-character icons are weird for several guns.  Dart gun is overwhelmingly large when you hold it

![dart gun eats your character](https://user-images.githubusercontent.com/59771903/84227737-c422d200-aaaa-11ea-8535-d48d53c62f0a.png)

but is invisible when on the ground and has no hand inventory icon
![dart gun is invisible](https://user-images.githubusercontent.com/59771903/84227805-f2081680-aaaa-11ea-8923-c978e50af0cc.png)

alternatively, the advanced laser gun is FINE in your inventory and in your hand, and shows up properly on your character (An infestation of rats surrounded me for my testing, they're excited by the prospect of this report going out)
![advanced laser gun fine in hand](https://user-images.githubusercontent.com/59771903/84227888-3398c180-aaab-11ea-96a8-8a3701cdcbfb.png)

but the advanced laser gun appears huge on your character, or like you've dropped it when you loop it into your belt slot.

![advanced laser gun in belt appears huge again](https://user-images.githubusercontent.com/59771903/84228033-8bcfc380-aaab-11ea-8b81-1d1a099fe6fa.png)

There's so many oddities that have cropped up fairly recently, I'm completely unable to document them all

#### Difference between expected and actual behavior
expected:  Icons appear
Actual:  Icons fucky, but only some

#### Steps to reproduce
play with various pieces of equipment.  spot oddities. 

#### Specific information for locating

object names listed in description for precise discussion.  I don't necessarily care to copy/paste 'em all down here, sorry.

#### Length of time in which bug has been known to occur

couple weeks, sorry it's not reported sooner

#### Client version, Server revision & Game ID

Client Version: 512
Server Revision: 49687b99e2f79a4dd8a2030538ec9e5dff91a902 - dev - 2020-06-09
Game ID: b7z-dHQj
Current map: Tradeship Ivenmoth

#### Issue bingo

- [x] Issue could be reproduced at least once
- [x] Issue could be reproduced by different players
- [x] Issue could be reproduced in multiple rounds
- [x] Issue happened in a recent (less than 7 days ago) round
- [x] [Couldn't find an existing issue about this](https://github.com/NebulaSS13/Nebula/issues)

**Comment by MistakeNot4892** [comment]
I blame @comma

**Comment by comma** [comment]
- Double barreled shotgun (/obj/item/gun/projectile/shotgun/doublebarrel) - icon and iconstate weren't set by default, fixing that
- biohazard suit (/obj/item/clothing/suit/bio_suit/scientist ) -   seems to be working fine?
- ‘the gun’ (/obj/item/gun/projectile) -  not really an obtainale type, made it use pistol icon anyway
- 'the dart gun' /obj/item/gun/projectile/dartgun - missing world icon actually, fixing that
- Pirate’s laser cutlass when ACTIVATED (/obj/item/melee/energy/sword/pirate ) - iconstate was overriden to normal e-sord, fixing that
- advanced laser gun - seems to be working fine in belt slot?
- Dart gun is overwhelmingly large when you hold it - couldn't reproduce
- wirecutter was fixed at some point
- Teleportation pad - visible ingame, maybe got fixed at some point
- kabob - both normal and tofu versions have meat on the icon currently
