### ISSUE TITLE
Guitar doesn't play

### ISSUE THREAD

**Issue by TheKnightofAura** [NebulaSS13/Nebula#614]
#### Description of issue

Tried to play guitar, no noise happened

#### Difference between expected and actual behavior
Playing a song that used to work should still work

#### Steps to reproduce

play some music on the guitar in the tradeship lounge

#### Specific information for locating

Guitar

#### Length of time in which bug has been known to occur

Only found out today

#### Issue bingo

- [x] Issue could be reproduced at least once
- [ ] Issue could be reproduced by different players
- [ ] Issue could be reproduced in multiple rounds
- [x] Issue happened in a recent (less than 7 days ago) round
- [x] [Couldn't find an existing issue about this](https://github.com/NebulaSS13/Nebula/issues)

**Comment by quardbreak** [comment]
Tested. It doesn't work because sustain timer lower than `2`. Higher value works fine.

**Comment by MistakeNot4892** [comment]
Can confirm quard's comment, works fine if you bump sustain up by 1. Given the fractal nightmare that instruments are and their niche use I'm going to mark this `wontfix` at least for the time being, as I can't see anyone willing to rewrite that mess.
