### ISSUE TITLE
Light in Tradeship tool storage assigned to wrong switch

### ISSUE THREAD

**Issue by TheKnightofAura** [NebulaSS13/Nebula#615]
#### Description of issue

Light in Tradeship tool storage assigned to wrong switch
bottomright most light is not assigned to that room's switch. instead, it turns on via the lightswitch in the next room, below engineering

#### Difference between expected and actual behavior
A room's lightswitch should turn on all lights in that room. The darkest corner shouldn't be locked behind an engineering-only door

#### Steps to reproduce

Flip some light switches in the Tradeship tool storage

#### Length of time in which bug has been known to occur

3+ days

#### Issue bingo

- [x] Issue could be reproduced at least once
- [ ] Issue could be reproduced by different players
- [x] Issue could be reproduced in multiple rounds
- [x] Issue happened in a recent (less than 7 days ago) round
- [x] [Couldn't find an existing issue about this](https://github.com/NebulaSS13/Nebula/issues)

**Comment by MistakeNot4892** [comment]
Fixed in #802.
