### ISSUE TITLE
vending machines don't accept card

### ISSUE THREAD

**Issue by ZirconiumWit** [NebulaSS13/Nebula#708]
#### Description of issue
Vending machines don't accept card for payment.  ID can be in or out of PDA and machine does not accept.  Adequate funds were verified to be on card.  Machine does accept cash.  If memory serves, there used to even be a message output regarding insufficient funds or something.  Now, the ID just doesn't seem to interact with the machine in any substantive way.

#### Difference between expected and actual behavior
Vending machine card readers break all too often, but that doesn't make it expected behavior

#### Steps to reproduce
Approach vending machine, select product of choice, experience dissatisfaction upon swiping card.

#### Specific information for locating

/obj/machinery/vending/snack

/obj/machinery/vending/cigarette

/obj/machinery/vending/coffee

--- Probably all vending machines, but these were the ones I tested.

#### Length of time in which bug has been known to occur

I thought it was related to the doors being unopenable except by bumping into them/being unclosable since you can't bump into an open airlock/the bug where hands didn't interact with doors, but now that's fixed and this isn't and I found out cash works so it's a very different issue.  It's been around for a couple weeks now, at least.

#### Client version, Server revision & Game ID

Client Version: 512
Server Revision: 9e31062250422a862959ff2c29d8e6e5afeb11e9 - dev - 2020-07-19
Game ID: b8d-bmoa
Current map: Tradeship Ivenmoth

#### Issue bingo

- [x] Issue could be reproduced at least once
- [x] Issue could be reproduced by different players
- [x] Issue could be reproduced in multiple rounds
- [x] Issue happened in a recent (less than 7 days ago) round
- [x] [Couldn't find an existing issue about this](https://github.com/NebulaSS13/Nebula/issues)

**Comment by MistakeNot4892** [comment]
Not a bug, vending machines take cash or charge cards but not ID cards.
