### ISSUE TITLE
Cannot use non-hand unarmed attacks on other humans if you have two broken hands.

### ISSUE THREAD

**Issue by MistakeNot4892** [NebulaSS13/Nebula#75]
#### Description of issue
Trying to use an unarmed attack that does not involve hands will fail if both hands are broken.

#### Difference between expected and actual behavior
A stomp should not require you to have working hands.

#### Steps to reproduce
- Select stomp as a default attack.
- Amputate or break both your hands.
- Try to stomp on someone.

#### Specific information for locating
/mob/living/carbon/human/attack_hand(), line 38.

#### Length of time in which bug has been known to occur
Indefinite.

#### Client version, Server revision & Game ID
Didn't grab it, shouldn't matter.

#### Issue bingo

- [X] Issue could be reproduced at least once
- [ ] Issue could be reproduced by different players
- [X] Issue could be reproduced in multiple rounds
- [X] Issue happened in a recent (less than 7 days ago) round
- [X] [Couldn't find an existing issue about this](https://github.com/NebulaSS13/Nebula/issues)

**Comment by afterthought2** [comment]
Fixed in #74.

**Comment by MistakeNot4892** [comment]
No it wasn't.
