### ISSUE TITLE
Fluid puddles evaporate too quickly for molotovs etc to work.

### ISSUE THREAD

**Issue by MistakeNot4892** [NebulaSS13/Nebula#768]
More of a note to self than anything. Spilled liquids below the evaporation threshold vanish instantly instead of hanging around as puddles for a bit.

**Comment by TheKnightofAura** [comment]
As a note for your note: The liquid quantity seems to change between the same fresh bottle depending on if you smash it on the ground, or over your head: Thrown molitovs never spread in fire, but when I bashed the bottle over my head, the puddle lasted about a second longer: Just enough to slip on before it poofed out of existence.
