### ISSUE TITLE
Modular Computer Telescreens runtime because of an extension not existing.

### ISSUE THREAD

**Issue by Mazianni** [NebulaSS13/Nebula#782]
#### Description of issue
Trying to use a telescreen. Turn it on. It doesn't turn on and runtimes instead. It then becomes uninteractable.

#### Difference between expected and actual behavior
Computer turn on.

Computer does not turn on. 

#### Steps to reproduce
1. Acquire fully kitted telescreen.
2. Attempt to turn on.
3. ???
4. Catastrophic failure.

#### Specific information for locating
[13:03:05] Runtime in extensions.dm,48: Cannot read null.extensions
  proc name: get extension (/proc/get_extension)
  usr: Tatiana Kanaga (/mob/observer/ghost) ([0x3000092]) (the pale blue carpet) (70,66,4 - FTE Odyssey) (/turf/simulated/floor/carpet/blue2) (kerbal22)
  usr.loc: The pale blue carpet (/turf/simulated/floor/carpet/blue2) ([0x100d71d]) (70,66,4 - FTE Odyssey) (/area/ship/wolf/command/office/cmo)
  src: null
  call stack:
  get extension(null, /datum/extension/interactive/n... (/datum/extension/interactive/ntos))
  /datum/extension/assembly/modu... (/datum/extension/assembly/modular_computer/telescreen): turn on(Tatiana Kanaga (/mob/observer/ghost))
  the telescreen (/obj/item/modular_computer/telescreen/preset/generic): attack ghost(Tatiana Kanaga (/mob/observer/ghost))
  Tatiana Kanaga (/mob/observer/ghost): ClickOn(the telescreen (/obj/item/modular_computer/telescreen/preset/generic), "icon-x=27;icon-y=22;left=1;scr...")
  /datum/click_handler/default (/datum/click_handler/default): OnClick(the telescreen (/obj/item/modular_computer/telescreen/preset/generic), "icon-x=27;icon-y=22;left=1;scr...")
  the telescreen (/obj/item/modular_computer/telescreen/preset/generic): Click(the red carpet (70,60,4) (/turf/simulated/floor/carpet/red), "mapwindow.map", "icon-x=27;icon-y=22;left=1;scr...")

#### Length of time in which bug has been known to occur
8/5/2020 - Present

#### Issue bingo

- [x] Issue could be reproduced at least once
- [ ] Issue could be reproduced by different players < Need someone else to confirm.
- [x ] Issue could be reproduced in multiple rounds
- [x] Issue happened in a recent (less than 7 days ago) round
- [x ] [Couldn't find an existing issue about this](https://github.com/NebulaSS13/Nebula/issues)

**Comment by MistakeNot4892** [comment]
I am wondering if it's calling turn_on before or during New() somehow, so it's hitting the extension checks before it actually sets holder to anything.
