### ISSUE TITLE
newhands OP

### ISSUE THREAD

**Issue by ZirconiumWit** [NebulaSS13/Nebula#800]
#### Description of issue
Hand refactor appears to allow players to wantonly open and shut external blast doors with their bare hands. 

#### Difference between expected and actual behavior
External blast doors should probably be stronger than the crew.  Probably.  I know the ship was bought on discount, and damaged blast door motors is probably an excellent heretofore unknown reason for the discount.

#### Steps to reproduce
1) Approach blast door with empty hands
2) let it know who is really in charge here

#### Specific information for locating

any blast door.  On tradeship, most accessible (and least likely to kill you) is probably the hallway leading to the shuttle.

#### Length of time in which bug has been known to occur

Today only

#### Client version, Server revision & Game ID

version directly following hand refactor.

#### Issue bingo

- [x] Issue could be reproduced at least once
- [x] Issue could be reproduced by different players
- [ ] Issue could be reproduced in multiple rounds
- [x] Issue happened in a recent (less than 7 days ago) round
- [x] [Couldn't find an existing issue about this](https://github.com/NebulaSS13/Nebula/issues)

**Comment by MistakeNot4892** [comment]
Airlock refactor _actually_. Will have a fix up shortly.
