### ISSUE TITLE
In hand sprites do not display for any item.

### ISSUE THREAD

**Issue by TheBucketBip** [NebulaSS13/Nebula#806]
#### Description of issue
In hands arent displaying for every item.

#### Difference between expected and actual behavior
Items in the players hand should display a sprite on the mob that shows they are holding the item in question if the item has an in hand sprite dedicated to it.

#### Steps to reproduce
1. Pick up any object off the ground that should normally have an in hand icon.

#### Specific information for locating

Just pick up any object. Check the DMI files for items if you want to check if a sprite should have an in-hand icon or not.

#### Length of time in which bug has been known to occur

Since I installed the codebase yesterday off of the github.

#### Client version, Server revision & Game ID

Client Version: 513
Server Revision: c908b50487a80f11dfaa2d3ecea80460135ad3d4 - dev - 2020-08-16
Game ID: b8F-dKoK

#### Issue bingo

- [X] Issue could be reproduced at least once
- [ ] Issue could be reproduced by different players
- [X] Issue could be reproduced in multiple rounds
- [X] Issue happened in a recent (less than 7 days ago) round
- [X] [Couldn't find an existing issue about this](https://github.com/NebulaSS13/Nebula/issues)

**Comment by MistakeNot4892** [comment]
Fixed in #803.
