### ISSUE TITLE
Blurred skybox background on 64x64 and lower view size

### ISSUE THREAD

**Issue by quardbreak** [NebulaSS13/Nebula#828]
#### Description of issue

See title
<details>
  <summary>Spoiler</summary>

 ![image](https://user-images.githubusercontent.com/44920739/91089768-b8cc5500-e65c-11ea-91ad-3fac572f456b.png)
</details>

#### Difference between expected and actual behavior

Should not be blurred if you change view size

#### Steps to reproduce

set 64x64, 48x48 or 32x32 in Size

#### Specific information for locating

Size tab 
![image](https://user-images.githubusercontent.com/44920739/91089514-56735480-e65c-11ea-9091-665f3935db30.png)

#### Length of time in which bug has been known to occur

Dunno, probably since when view settings got their config options.

#### Client version, Server revision & Game ID

513 stable, downstream fork with minimal code edits.

#### Issue bingo

- [X] Issue could be reproduced at least once
- [ ] Issue could be reproduced by different players
- [X] Issue could be reproduced in multiple rounds
- [X] Issue happened in a recent (less than 7 days ago) round
- [X] [Couldn't find an existing issue about this](https://github.com/NebulaSS13/Nebula/issues)

**Comment by MistakeNot4892** [comment]
The skybox is scaled to fit your client view, as far as I know there is no other way to do this as the skybox is a specific size. This isn't a bug.
