### ISSUE TITLE
 being prone makes you shine through walls to any entity south of you

### ISSUE THREAD

**Issue by TheKnightofAura** [NebulaSS13/Nebula#83]
#### Description of issue

 being prone makes you shine through walls to any entity south of you

#### Difference between expected and actual behavior
When I take a nap, I don't expect people to see me through walls and privacy curtains if they happen to be laying/standing to the south of me, but they do

#### Steps to reproduce

On scavstation map, (Bearcat?) lay down in the crew dorms. People in southern dorms can see people in northern ones, through walls, and the dark, and privacy curtains.

#### Length of time in which bug has been known to occur

At least two days

#### Client version, Server revision & Game ID

?

#### Issue bingo

- [x] Issue could be reproduced at least once
- [x] Issue could be reproduced by different players
- [x] Issue could be reproduced in multiple rounds
- [x] Issue happened in a recent (less than 7 days ago) round
- [x] [Couldn't find an existing issue about this](https://github.com/NebulaSS13/Nebula/issues)

**Comment by MistakeNot4892** [comment]
This was fixed by the reversion to the original PR that caused it.
