### ISSUE TITLE
protolathe doesn't populate known recipes automatically

### ISSUE THREAD

**Issue by ZirconiumWit** [NebulaSS13/Nebula#860]
#### Description of issue
Protolathe doesn't populate known recipes at gamestart, it requires that something must be sacrificed in the destructive analyzer before it's willing to show you the recipes it already knows.

This might be a misunderstanding on my part about what known recipes means.

#### Difference between expected and actual behavior
If a recipe is known to the protolathe, you would expect it to populate the options without a sacrifice.  

#### Steps to reproduce
Start game, and examine the known recipes in the design database console, then examine the protolathe and gape in awe at how much difference there is between the two

#### Specific information for locating

design database console, protolathe

#### Length of time in which bug has been known to occur

A few months, it's easily fixed by breaking something down on the destructive analyzer

#### Client version, Server revision & Game ID

Client Version: 513
Server Revision: 456919e928c9a7c860cb6446e3fc1d5fa7dc96f2 - dev - 2020-09-05
Game ID: b81-dg0R
Current map: Tradeship Ivenmoth

#### Issue bingo

- [x] Issue could be reproduced at least once
- [x] Issue could be reproduced by different players
- [x] Issue could be reproduced in multiple rounds
- [x] Issue happened in a recent (less than 7 days ago) round
- [x] [Couldn't find an existing issue about this](https://github.com/NebulaSS13/Nebula/issues)

**Comment by MistakeNot4892** [comment]
So this isn't actually a bug exactly. All research fields start at 0, so no recipes are available (since all of them have a research requirement).
I'll make some of the more basic sciences start with 1 level so there'll be some recipes in the fab at roundstart.
