### ISSUE TITLE
Cheese receipt is broken

### ISSUE THREAD

**Issue by quardbreak** [NebulaSS13/Nebula#888]
#### Description of issue

You can't create cheese in-game as a chief,

#### Difference between expected and actual behavior

Receipt should give you cheese.

#### Steps to reproduce

Mix 40 milk and 5 universal enzyme. Heat to 40C or above. Get nothing.

#### Length of time in which bug has been known to occur

Today, just got report from player on my server.

#### Issue bingo

- [X] Issue could be reproduced at least once
- [ ] Issue could be reproduced by different players
- [ ] Issue could be reproduced in multiple rounds
- [X] Issue happened in a recent (less than 7 days ago) round
- [X] [Couldn't find an existing issue about this](https://github.com/NebulaSS13/Nebula/issues)

**Comment by MistakeNot4892** [comment]
![image](https://user-images.githubusercontent.com/2468979/101495343-91578900-39bc-11eb-913d-5bd913bcc744.png)
