### ISSUE TITLE
PROPER Blood transfer causes organ failure

### ISSUE THREAD

**Issue by TheKnightofAura** [NebulaSS13/Nebula#892]
#### Description of issue

any blood infusion, of blood that matches the acceptable types for the patient, will cause rejection

#### Difference between expected and actual behavior

Matching blood does good, not bad

#### Steps to reproduce

find a thing of O- blood, and stick yourself with it, then wait for organs to fail

#### Specific information for locating

bloodbags/transfer

#### Length of time in which bug has been known to occur

unsure exact duration. Weeks at least

#### Issue bingo

- [x] Issue could be reproduced at least once
- [x] Issue could be reproduced by different players
- [x] Issue could be reproduced in multiple rounds
- [x] Issue happened in a recent (less than 7 days ago) round
- [x] [Couldn't find an existing issue about this](https://github.com/NebulaSS13/Nebula/issues)

**Comment by comma** [comment]
Weird, just put O- bag in IV drip and stuck in self (human), all was good.
Was patient non-human per chance?

**Comment by MistakeNot4892** [comment]
Closing for now as unreproducible, please reopen if it recurrs.
