### ISSUE TITLE
Z-mimic blood uncleanable, but still there

### ISSUE THREAD

**Issue by TheKnightofAura** [NebulaSS13/Nebula#893]
#### Description of issue
Blood on a lower floor had been cleaned, but was still showing on the catwalk on the floor above. All other blood on catwalk had been removed, but _this_ blood was 'too far away'
Blood on lower floor had been properly cleaned up.

#### Difference between expected and actual behavior

Ghost of Blood Cleaned should be beaten soundly by ghostbusters before anyone notices, and removed from view

#### Steps to reproduce
Unsure. only one spot out of almost a dozen did this.

#### Specific information for locating

blood splatters across two floors, blood being on both layers

#### Length of time in which bug has been known to occur

Unsure

#### Issue bingo

- [ ] Issue could be reproduced at least once
- [ ] Issue could be reproduced by different players
- [ ] Issue could be reproduced in multiple rounds
- [x] Issue happened in a recent (less than 7 days ago) round
- [x] [Couldn't find an existing issue about this](https://github.com/NebulaSS13/Nebula/issues)

**Comment by afterthought2** [comment]
Possibly need to have `set_invisibility` queue a zmimic update, as it makes an appearance change.
