### ISSUE TITLE
Drink Machines prohibitively expensive

### ISSUE THREAD

**Issue by ZirconiumWit** [NebulaSS13/Nebula#894]
#### Description of issue
Drink Machines cost a great deal more than you would expect

#### Difference between expected and actual behavior
most employees on the ship should probably be able to afford more than just a single dirnk

#### Steps to reproduce
approach robust softdrinks vender.  prepare yourself for the ultimate in fizzy drinks experiences, followed rapidly by disappointment and unquenched thirst

#### Specific information for locating

/obj/machinery/vending/cola
--

#### Length of time in which bug has been known to occur

since forever

#### Client version, Server revision & Game ID

Client Version: 513
Server Revision: fa5f5a3a9c8e0f7f9e8f145bc0c70b46c6bf41ba - dev - 2020-09-12
Game ID: b88-akEb
Current map: Tradeship Ivenmoth

#### Issue bingo

- [x] Issue could be reproduced at least once
- [x] Issue could be reproduced by different players
- [x] Issue could be reproduced in multiple rounds
- [x] Issue happened in a recent (less than 7 days ago) round
- [ ] [Couldn't find an existing issue about this](https://github.com/NebulaSS13/Nebula/issues)

**Comment by afterthought2** [comment]
Relevant PR:  #1352.

Current prices are about 310 Cr for bottled drinks, 60 Cr for juiceboxes. Seem still high, so not closing. @MistakeNot4892 to double-check that these are still higher than desired.

**Comment by MistakeNot4892** [comment]
Finally fixed on dev - cans of cola are 15cr to candy bar's 8cr.
