### ISSUE TITLE
Credit lines overlap

### ISSUE THREAD

**Issue by SodiumShine** [NebulaSS13/Nebula#90]
![Screenshot](https://cdn.discordapp.com/attachments/678865076299497472/685645425117888558/unknown.png)
Circumstances are unknown, sorry! I got nothing.
Screen size was 64x

**Comment by TheKnightofAura** [comment]
Credits where perfectly normal on my end, also on 64x64

**Comment by MistakeNot4892** [comment]
I haven't seen this on my end either. Wondering if it was an issue with your screen resolution?

**Comment by MistakeNot4892** [comment]
Haven't seen this since, closing for the time being.
