### ISSUE TITLE
Monkeys have Experienced in every skill

### ISSUE THREAD

**Issue by SodiumShine** [NebulaSS13/Nebula#91]
Normally this isn't a problem but if for any reason a person becomes in control of a monkey they become extremely good at everything. While funny, not sure if this is ideal. Especially when combat becomes involved.

Monkey op plz nerf.

**Comment by afterthought2** [comment]
This is intentional, although it can be re-examined. Most mobs will have such a skillset to let them pass mobility or combat skill checks.

**Comment by MistakeNot4892** [comment]
As this isn't a bug, going to close it to clear the tracker out. We can examine it in discussion if it ends up being a problem.
