### ISSUE TITLE
limbs printed in robotics fabricator appear to be bugged

### ISSUE THREAD

**Issue by ZirconiumWit** [NebulaSS13/Nebula#915]
#### Description of issue
attempted installing right arm on a character.  codex guide indicates that any robotic limb needs to be installed by connecting the robotic limb onto the stump and then attaching tendons with a hemostat.  However, currently, the limb does not appear to be manipulated by the hemostat, and does not appear to have a hand - though this might be the result of being unable to completely install the limb.

#### Difference between expected and actual behavior
robotic limb installations don't work

#### Steps to reproduce
install robotic limb, at the very least right arm appears broken.

#### Specific information for locating

in robotic limbs printed on exosuit fabricator

#### Length of time in which bug has been known to occur

today only

#### Client version, Server revision & Game ID

Client Version: 513
Server Revision: fa5f5a3a9c8e0f7f9e8f145bc0c70b46c6bf41ba - dev - 2020-09-12
Game ID: b89-atwu
Current map: Tradeship Ivenmoth

#### Issue bingo

- [x] Issue could be reproduced at least once
- [ ] Issue could be reproduced by different players
- [ ] Issue could be reproduced in multiple rounds
- [x] Issue happened in a recent (less than 7 days ago) round
- [x] [Couldn't find an existing issue about this](https://github.com/NebulaSS13/Nebula/issues)

**Comment by MistakeNot4892** [comment]
Missing hand is due to these being robotic limbs rather than the robotics arm object.
