### ISSUE TITLE
Some slime interactions no-longer working

### ISSUE THREAD

**Issue by TheKnightofAura** [NebulaSS13/Nebula#931]
#### Description of issue
Several slime activations yield nothing, where as before they did

#### Difference between expected and actual behaviour

The few I've found specifically are Yellow Slime cores no-longer make EMP pulses when injected with blood, and orange slime cores no-longer make large fireballs when injected with Uranium. I imagine several other interactions are likewise busted, (Beyond the ones that have been intentionally removed/unworking, such as the green slime's transformation into a slime-person (removed from codebase) and Bluespace slime (Never implimented in the first place))

#### Steps to reproduce

grow, mutate, and harvest slimes until you get a yellow/orange one, and collect it's core. Attempt to use blood on the yellow, or uranium on the orange, and witness.... nothing.

#### Specific information for locating

Slimes, xenobiology, slimecores

#### Length of time in which bug has been known to occur

Unsure. I suspect since reagent puddling, but no proof

#### Issue bingo

- [x] Issue could be reproduced at least once
- [ ] Issue could be reproduced by different players
- [ ] Issue could be reproduced in multiple rounds
- [x] Issue happened in a recent (less than 7 days ago) round
- [x] [Couldn't find an existing issue about this](https://github.com/NebulaSS13/Nebula/issues)

**Comment by MistakeNot4892** [comment]
Yellow core EMP: can't reproduce, EMP happened with blood.
Orange core fireball: can't reproduce, fire happened with uranium.

It's possible that it got fixed along with the various other reagent/material/reaction fixes, not sure.
