### ISSUE TITLE
NanoUI sometimes funky

### ISSUE THREAD

**Issue by quardbreak** [NebulaSS13/Nebula#936]
#### Description of issue

Sometimes nanoui can't load self while you open window.
This is an ancient bug from bay.

#### Difference between expected and actual behavior

Nanoui should load self and don't trip on himself.

#### Steps to reproduce

Open nanoui, get chance to broke your window.

#### Length of time in which bug has been known to occur

Dunno, I think since assets load changes. Pretty ancient error since bay.

#### Issue bingo

- [X] Issue could be reproduced at least once
- [X] Issue could be reproduced by different players
- [X] Issue could be reproduced in multiple rounds
- [X] Issue happened in a recent (less than 7 days ago) round
- [X] [Couldn't find an existing issue about this](https://github.com/NebulaSS13/Nebula/issues)

**Comment by afterthought2** [comment]
This isn't fixable, at least without exact reproduction steps.

As far as I'm aware, there is a general issue (to be expected) with loading nanoui windows before assets are fully sent, most noticeable during latejoin or in dev testing (the lobby time is long enough that all assets will generally be sent). Besides that, I don't know of reproduceable nanoui issues.

**Comment by MistakeNot4892** [comment]
This seems to have been mitigated to a degree by the asset bundling PR - going to close it for now as that's about as good as we can expect it to get by my current understanding, short of making people sit in limbo until the assets load.
