### ISSUE TITLE
North-facing chairs not visible in map editor

### ISSUE THREAD

**Issue by ghost** [NebulaSS13/Nebula#946]
#### Description of issue

Any chair, when set to face north, is not visible in the map editor.

#### Difference between expected and actual behavior

I believe the intended behavior is to be able to see north-facing chairs.

#### Specific information for locating

`obj/structure/bed/chair`

#### Length of time in which bug has been known to occur

Unknown.

#### Client version, Server revision & Game ID

Current dev branch, inside FastDMM2.

#### Issue bingo

- [x] Issue could be reproduced at least once
- [ ] Issue could be reproduced by different players
- [ ] Issue could be reproduced in multiple rounds
- [x] Issue happened in a recent (less than 7 days ago) round
- [x] [Couldn't find an existing issue about this](https://github.com/NebulaSS13/Nebula/issues)

**Comment by MistakeNot4892** [comment]
Chair overlays are generated at runtime due to how they need to layer behind the mobs sitting in them. Not a bug.
If you want to add a preview icon system back to them feel free.
