### ISSUE TITLE
[Bug] Unable to enable psy armor with psionics mod enabled 

### ISSUE THREAD

**Issue by ghost** [NebulaSS13/Nebula#953]
#### Description of issue
It is currently impossible to toggle on psy armor. Regardless of operative level, two runtimes will appear, at line 9, 12 in ui_toggles.dm

#### Difference between expected and actual behavior
Expected:The Psi-armor icon should toggle indicating it is on.
Actual: There is no UI change

#### Steps to reproduce
1) Enable Psionics in the the map, start a server and spawn in (Usually as admin)
2) Obtain psi-operative powers. It is generally easier to test all powers at PARAMOUNT.

#### Specific information for locating

```
proc name: on update icon (/obj/screen/psi/armour/on_update_icon)
src: Psi-Armour (/obj/screen/psi/armour)
src.loc: null
call stack:
Psi-Armour (/obj/screen/psi/armour): on update icon()
Psi-Armour (/obj/screen/psi/armour): update icon()
Psi-Armour (/obj/screen/psi/armour): update icon()
Psi (/obj/screen/psi/hub): on update icon()
Psi (/obj/screen/psi/hub): update icon()
Psi (/obj/screen/psi/hub): update icon()
Psi (/obj/screen/psi/hub): Process(10, 109, Processing (/datum/controller/subsystem/processing))
Processing (/datum/controller/subsystem/processing): fire(0)
Processing (/datum/controller/subsystem/processing): ignite(0)
Master (/datum/controller/master): RunQueue()
Master (/datum/controller/master): Loop()
Master (/datum/controller/master): StartProcessing(0)
```
and
```
proc name: on update icon (/obj/screen/psi/armour/on_update_icon)
src: Psi-Armour (/obj/screen/psi/armour)
src.loc: null
call stack:
Psi-Armour (/obj/screen/psi/armour): on update icon()
Psi-Armour (/obj/screen/psi/armour): update icon()
Psi-Armour (/obj/screen/psi/armour): update icon()
Psi (/obj/screen/psi/hub): on update icon()
Psi (/obj/screen/psi/hub): update icon()
Psi (/obj/screen/psi/hub): update icon()
Psi (/obj/screen/psi/hub): Process(10, 102, Processing (/datum/controller/subsystem/processing))
Processing (/datum/controller/subsystem/processing): fire(0)
Processing (/datum/controller/subsystem/processing): ignite(0)
Master (/datum/controller/master): RunQueue()
Master (/datum/controller/master): Loop()
Master (/datum/controller/master): StartProcessing(0)
```

#### Length of time in which bug has been known to occur

Less than a second.

#### Client version, Server revision & Game ID
BYOND Version:513.1536
Server revision: N/A
Game ID: N/A

#### Issue bingo

- [x ] Issue could be reproduced at least once
- [ ] Issue could be reproduced by different players
- [x ] Issue could be reproduced in multiple rounds
- [x ] Issue happened in a recent (less than 7 days ago) round
- [x] [Couldn't find an existing issue about this](https://github.com/NebulaSS13/Nebula/issues)

**Comment by afterthought2** [comment]
Noting from past investigation:
```
/obj/screen/psi/hub/Initialize()
	. = ..()
	on_cooldown = image(icon, "cooldown")
	components = list(
		new /obj/screen/psi/armour(loc),
		new /obj/screen/psi/toggle_psi_menu(loc, src)
		)
	START_PROCESSING(SSprocessing, src)
```
here `loc` is a clear error; should be `owner` in both places; likely a nonlocal side-effect of the New -> Initialize conversion.

However, it has been reported that this alone does not fix the issue.
